### ISSUE TITLE
docxtpl doesn't work on Python 3

### ISSUE THREAD

**Issue by wiz21b** [elapouya/python-docx-template#1]
Hey, I use Python 3.4 and docxtpl doesn't work there...

Fortunately, fixing it is not difficult : 
```
    def get_xml(self):
        return etree.tostring(self.docx._element.body, pretty_print=True)
```
becomes
```
    def get_xml(self):
        return etree.tostring(self.docx._element.body, encoding=str, pretty_print=True)
```

but that breaks compatibility with python 2.7 :-(

thanks for the nice code, it's very powerful !

**Comment by elapouya** [comment]
Hi,

Thank you :)

unfortunately, I have not port the code to Python 3 yet. but it is in the
pipe...

2015-05-12 11:15 GMT+02:00 wiz21b <notifications@github.com>:

**Comment by wiz21b** [comment]
No problem, my fix just works fine. I was just posting it in case somebody has the issue.

**Comment by elapouya** [comment]
OK, I believed that there was some extra work to do to get it running with
py3
does 'encoding=str' works also with py2 ?

2015-05-12 13:45 GMT+02:00 wiz21b <notifications@github.com>:

**Comment by wiz21b** [comment]
Encoding issues are always a bit tricky. From the lxml doc : 

> You can also serialise to a Unicode string without declaration by passing
> the unicode function as encoding (or str in Py3), or the name 'unicode'. 
> This changes the return value from a byte string to an unencoded unicode string.

So, one could use `encoding='unicode'` (note the quotes) ? It looks py2/3 compatible to me... I'll try on P3 when I can...

**Comment by robert-malai** [comment]
I can confirm that encoding='unicode' does work on Python 3.
