### ISSUE TITLE
Issues with colspan

### ISSUE THREAD

**Issue by MLubinski** [elapouya/python-docx-template#102]
I'm trying to spam columns, failing, and ending up with one big table with lots and lots of columns in a single row.

It looks like this:

{% colspan colspanvar %} |   |  
-- | -- | --
{%tc for row in ib_www %} | {{ row }} | {%tc endfor %}

**Comment by elapouya** [comment]
have seen full example : tests/test_files/dynamic_table_tpl.docx and tests/dynamic_table.py

**Comment by MLubinski** [comment]
Yes and I believe i'm using it right but have included it here.
<img width="466" alt="tablepic" src="https://user-images.githubusercontent.com/3891280/34872563-f1ac30ea-f756-11e7-8d03-4661e4f931ba.png">

**Comment by MLubinski** [comment]
Anyone else have this problem?

**Comment by e81u4g** [comment]
is {% colspan colspanvar|count %}
![image](https://user-images.githubusercontent.com/12731101/40955408-705a491e-68bc-11e8-829c-fb5a98924add.png)
