### ISSUE TITLE
Odd Error on Output when ampersand (&) placed in footer

### ISSUE THREAD

**Issue by JSv4** [elapouya/python-docx-template#105]
Hey Guys,

I have a program that is working just fine 99.9% of the time and creates documents from a single word template. It works flawlessly *but* when and only when I try to place a string in the footer that contains an ampersand, the resulting output is corrupt and word won't open it. Libreoffice is less picky and opens the resulting doc, but the footer is empty only for those docs that won't open in word. I noticed this seemed to be happening only when the text I was trying to place included an Ampersand. I hacked my code to find and replace ampersands with a space and, voila, no more problems. Can you think of why this might be happening?

The error is not in python, it's in word, so I've attached an image of the exact error message and window. Definitely related to how the library is inserting the footer IMHO. 
![python docx template error 1](https://user-images.githubusercontent.com/5049984/35005771-95076692-fac2-11e7-8eea-70ec6ddc621f.png)

Happy to place my code in here, but I'm not sure how helpful it will be.

**Comment by elapouya** [comment]
What version of Word are you using ?
docxtpl has been developped with Word 1997

**Comment by elapouya** [comment]
...and please, could you give your word template (a minimal version, just to reproduce) and the python file you used (a minimal version if possible)

**Comment by unixo** [comment]
@jmanjohns2 is it possible because, as stated in the [documentation](http://docxtpl.readthedocs.io/en/latest/#escaping-newline-new-paragraph-listing), 

> you are modifying an XML word document, this means you cannot use all chars, 
> especially <, > and &. In order to use them, you must escape them

**Comment by JSv4** [comment]
@unixo, that's spot, thanks. Sorry I never closed this. Resolved.
