### ISSUE TITLE
Can I initialize DocxTemplate() by bytes?

### ISSUE THREAD

**Issue by devkingsejong** [elapouya/python-docx-template#106]
Hello.
I want to use docxtpl with `Azure Storage`.

from the example, 
```
from docxtpl import DocxTemplate
doc = DocxTemplate("my_word_template.docx")
```
DocxTemplate class is initialized by file path,
But I want to init by file's bytes(because of worry about save file at server)
Can I do it?

**Comment by elapouya** [comment]
Hello,

I am sorry but I do not understand your question, could you tell me more ?

2018-01-24 8:11 GMT+01:00 devkingsejong <notifications@github.com>:

**Comment by devkingsejong** [comment]
Sorry for my weak English.
I want to include .docx file as `byte`.
For example, some .docx files locale at Azure Storage(Aws S3).
And, I want to include file without file save,
for example using below APIs.  

https://azure-storage.readthedocs.io/ref/azure.storage.file.fileservice.html#azure.storage.file.fileservice.FileService.get_file_to_bytes

**Comment by elapouya** [comment]
Not tested yet, but DocTemplate() should also accept file-like object. So
the question is : Does Aws S3 "File" object has been coded this way : just
try...

2018-01-24 8:39 GMT+01:00 devkingsejong <notifications@github.com>:
