### ISSUE TITLE
The Jinja2 'Include' statement is not supported by docxtpl

### ISSUE THREAD

**Issue by oddrationale** [elapouya/python-docx-template#107]
Hello!

I'm trying to use the [Jinja2 `Include` statement](http://jinja.pocoo.org/docs/templates/#include) in my template. However, it does not appear to be supported by docxtpl.

Here's what I've tried and the issues I've run into:

I have a simple `test.docx` file with the following contents:

```
{% include 'sub.docx' %}
```

In the same folder, I have the file `sub.docx` with the following contents:

```
A sub-document
```

# No loader specified

I try the following code:

```python
from docxtpl import DocxTemplate

doc = DocxTemplate('test.docx')
context = {}
doc.render(context)
```

This gives me the error:

```
TypeError: no loader for this environment specified
```

# Unicode Decode Error

I noticed that the `render` function takes an optional `jinja_env` parameter. So I tried to specify the `Environment` manually:

```python
from jinja2 import Environment, FileSystemLoader
env = Environment(loader=FileSystemLoader("/path/to/template/folder"))
doc.render(context, env)
```

But then I get this error message:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 16: invalid continuation byte
```

# Template Syntax Error

Since that didn't work, I figured out from the Jinja2 documentation that you can specify the template encoding when creating the loader. So I tried:

```python
env = Environment(loader=FileSystemLoader("/path/to/template/folder", encoding='latin-1'))
doc.render(context, env)
```

Then I get this error message:

```
jinja2.exceptions.TemplateSyntaxError: unexpected char '\x05' at 8902
```

I'm out of ideas. Any suggestions on how to make this work? Thanks!

**Comment by elapouya** [comment]
hello,

You cannot include a docx in another docx this way.

the jinja2 {% include xxx %} should work but only to include xml strings,
not a docx binary file (This is why you have chars/unicode issues)

Have you seen tests/subdoc.py example ?

2018-01-30 16:41 GMT+01:00 Dariel Dato-on <notifications@github.com>:

**Comment by oddrationale** [comment]
Thanks for the quick reply!

So if I already have a sub-document that I want to include, and I don't want to recreate the document using `python-docx`, should I be able to import the document using?

```python
from docx import Document

subdoc = Document("/path/to/subdoc.docx")
context = { 'subdoc': subdoc }
doc.render(context)
```

I just tried this and got a different error:

```
lxml.etree.XMLSyntaxError: Specification mandates value for attribute object, line 1, column 1488
```

Also, is it possible to include Jinja2 tags in the sub-document?

Thanks, again!

**Comment by elapouya** [comment]
That's not possible yet because it is hard to merge 2 documents.

2018-01-30 17:45 GMT+01:00 Dariel Dato-on <notifications@github.com>:

**Comment by oddrationale** [comment]
OK. Thanks, again!

For now, I'll explore other options such as using the INCLUDETEXT field code in MS Word itself, or using the MS Word Master Document feature. In case anyone else it trying to do the same thing, these two options might help.
