### ISSUE TITLE
cellbg or colspan variable name starting with r fails.

### ISSUE THREAD

**Issue by ptr0x01** [elapouya/python-docx-template#109]
Hi,

When using cellbg or colspan, the variable name given, will be placed by the cellbg and colspan functions:

{% cellbg regular_color %}
{% colspan regular_color %}

The variable name will be inserted into the jinja tag without spaces. If your variable name starts with r it will become: {{regular_color}}

Which will match the following regex in patch_xml since it starts with {{r:

```
# avoid {{r and {%r tags to strip MS xml tags too far
        src_xml = re.sub(r'({{r.*?}}|{%r.*?%})',r'</w:t></w:r><w:r><w:t>\1</w:t></w:r><w:r><w:t>',src_xml,flags=re.DOTALL)
```

Finally this produces an ill-defined XML and creates a nice looking stack trace.

The fix is to change those {{%s}} into {{ %s }} in colspan and cellbg function. I would gladly do it but I'm not sure how to create a pull request. 

Also, as awful as it was, it was very fun tracking down this bug 👍 :)

**Comment by elapouya** [comment]
good point, I will fix the code and the documentation

2018-02-02 16:43 GMT+01:00 Peter <notifications@github.com>:

**Comment by elapouya** [comment]
I pushed the new fixed version 0.4.7 : could you check it ?

**Comment by ptr0x01** [comment]
Hi,

Very quick turnaround on the issue, this solved the problem.

Any reason why you decided to match the whitespace instead of subbing in the variables with spaces around them? Just curious, but either way, thanks a lot!

**Comment by elapouya** [comment]
Because the problem is in fact more general than just colspan/cellbg

**Comment by ptr0x01** [comment]
Ah I see 👍  Thank you again, for the awesome repo!
