### ISSUE TITLE
Please add a support for headers and footers

### ISSUE THREAD

**Issue by tess1o** [elapouya/python-docx-template#11]
Hello,

The template doesn't support headers and footers. I cannot replace jinja2 tags in neither header nor footer.  Could you please fix it?

Thank you!

**Comment by elapouya** [comment]
This is normal : I use python-docx that does not manage headers and footers.
Nevertheless, it is possible to manage them though Microsoft word : the idea is to create a variable inside word document and then use it in the header, the footer and the body. When setting it in the body, it will update headers and footers too automatically.
I do not know how to do it with microsoft word, but I already used such a document as a template and headers and footers are modified correctly
If you can find a procedure, I will be pleased to add it in the documentation.
