### ISSUE TITLE
docx with formular-fields ...

### ISSUE THREAD

**Issue by goschtl** [elapouya/python-docx-template#111]
Hi,

i try to compose an existing docx template with some text-fields in it. 
Is it possible to fill them with python-docx-template?
Or does anyone know a other tool todo it?

Christian

**Comment by elapouya** [comment]
hi,

what do you mean by "text field" ?

Le ven. 2 mars 2018 à 10:05, Christian Klinger <notifications@github.com> a
écrit :

**Comment by goschtl** [comment]
Hey,

i try to work with this kind of fields...

https://wordribbon.tips.net/T008303_Working_with_Form_Fields.html

**Comment by elapouya** [comment]
i  am affraid it is not possible yet

Le ven. 2 mars 2018 à 10:31, Christian Klinger <notifications@github.com> a
écrit :
