### ISSUE TITLE
No such file or directory `pyquery`

### ISSUE THREAD

**Issue by jamesstidard** [elapouya/python-docx-template#112]
I'm currently getting this error when installing the library in my poject via pipenv. I'm not that familier with the Manifest.in files but here's the stack trace:

``` bash
  Using cached https://files.pythonhosted.org/packages/77/98/05e056d76cfac5a04e2cc9be4f984103c1ac8e82587e2c5a176959ff9c6d/docxtpl-0.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/docxtpl.egg-info
    writing requirements to pip-egg-info/docxtpl.egg-info/requires.txt
    writing dependency_links to pip-egg-info/docxtpl.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/docxtpl.egg-info/top_level.txt
    writing eager_resources to pip-egg-info/docxtpl.egg-info/eager_resources.txt
    writing pip-egg-info/docxtpl.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/docxtpl.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/docxtpl.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    error: [Errno 2] No such file or directory: 'pyquery'
```

This stack trace is for a 0.4.6, I got the same on the latest 0.4.7 - I was just seeing if it was a regression as the install has worked in the past.

Any ideas what's going on here? Should `pygraph` be included as a requirement in the `setup.py`?

Thanks

**Comment by elapouya** [comment]
I think my Manifest file comes from a bad cut&paste : I will fix that today
or tomorrow

2018-04-20 11:05 GMT+02:00 James Stidard <notifications@github.com>:

**Comment by jamesstidard** [comment]
@elapouya Ah great, thank you for the quick response and library.

**Comment by elapouya** [comment]
I tried pipenv my side, I cannot reproduce your problem :

$ pipenv install docxtpl
Creating a virtualenv for this project…
Using /usr/bin/python (2.7.12) to create virtualenv…
Already using interpreter /usr/bin/python
New python executable in
/home/elapouya/.local/share/virtualenvs/myproj2-AmbvvHqj/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location:
/home/elapouya/.local/share/virtualenvs/myproj2-AmbvvHqj
Creating a Pipfile for this project…
Installing docxtpl…
Looking in indexes: https://pypi.python.org/simple
Collecting docxtpl
  Downloading
https://files.pythonhosted.org/packages/91/6b/a19420e40344c858b1f6e9d8d575ba8411acf7cfea18572bf9976aa09350/docxtpl-0.4.7.tar.gz
(1.6MB)
Collecting six (from docxtpl)
  Using cached
https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting python-docx (from docxtpl)
Collecting jinja2 (from docxtpl)
  Using cached
https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting lxml (from docxtpl)
  Using cached
https://files.pythonhosted.org/packages/57/38/25b2acd2a179cb1900a32ab2daeec2967e511192c9ce0763ce16cece6366/lxml-4.2.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting MarkupSafe>=0.23 (from jinja2->docxtpl)
Building wheels for collected packages: docxtpl
  Running setup.py bdist_wheel for docxtpl: started
  Running setup.py bdist_wheel for docxtpl: finished with status 'done'
  Stored in directory:
/home/elapouya/.cache/pip/wheels/5b/b0/af/3702b9ecd3a3bf050fc445010ee113b8fedad39301fb96d70e
Successfully built docxtpl
Installing collected packages: six, lxml, python-docx, MarkupSafe, jinja2,
docxtpl
Successfully installed MarkupSafe-1.0 docxtpl-0.4.7 jinja2-2.10 lxml-4.2.1
python-docx-0.8.6 six-1.11.0

Adding docxtpl to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (c74b6c)!
Installing dependencies from Pipfile.lock (c74b6c)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 6/6 — 00:00:00


=> Could you give me the command you entered and the traces ?

2018-04-20 14:36 GMT+02:00 James Stidard <notifications@github.com>:

**Comment by elapouya** [comment]
Please could you try with the new version 0.4.8  I generated ?

2018-04-20 17:13 GMT+02:00 Eric Lapouyade <elapouya@gmail.com>:

**Comment by jamesstidard** [comment]
@elapouya sorry for the delayed response. I'm no longer experiencing this problem. I've been having a bunch of problems around the release of pip 10 with my dependencies so it might have been a knock-on from something else. Thanks for your time.
