### ISSUE TITLE
Context encoding issue

### ISSUE THREAD

**Issue by QuentinBrosse** [elapouya/python-docx-template#113]
Hi,

Here is a minimal example to try to explain my issue:
```py
print(name)  # Output: Bross & Co
print(type(name))  # Output: <class 'str'>

doc = DocxTemplate(template_path)
context = { 'name': name }
doc.render(context)
```

## Versions
* `Python 3.4.8`
* `docxtpl  0.4.8`

## Problem

I have a simple `docx` template with a `name` attribute in my context. This `name` contain a `&` and seems to be encoded in `unicode`.

When I try to execute my example I get this error (during the `render()` phase) :
```
lxml.etree.XMLSyntaxError: error parsing attribute name, line 1, column 2377
```
I think that I have an encoding with my context beacause if I remove the `&` it works well. I can't find a solution in this repo or in the `python-docx`. Would anyone have a suggestion to fix that?

Thanks a lot ! :)

**Comment by elapouya** [comment]
Hi

See documentation at section :
Escaping, newline, new paragraph, Listing
...

Le dim. 22 avr. 2018 à 17:27, Quentin Brosse <notifications@github.com> a
écrit :

**Comment by QuentinBrosse** [comment]
@elapouya thanks a loooot ! :)

```py
from cgi import escape

context = { 'name': escape(name) }
```
