### ISSUE TITLE
base64 images

### ISSUE THREAD

**Issue by QuentinBrosse** [elapouya/python-docx-template#114]
Hi,

Is it possible to use `base64` encoded images with `InlineImage`?

I have tried this kind of implementation (and many others) but It raises me a `UnrecognizedImageError ` exception:

```py
img = io.StringIO(base64_str_image)
image = InlineImage(doc, img)
```

Thanks a lot! :)

**Comment by elapouya** [comment]
Hi

I don't think Microsoft Word accepts that

Le mar. 1 mai 2018 à 18:13, Quentin Brosse <notifications@github.com> a
écrit :

**Comment by QuentinBrosse** [comment]
@elapouya Thanks, so I must use a temporary file?

**Comment by elapouya** [comment]
Yes

Le mar. 1 mai 2018 à 20:54, Quentin Brosse <notifications@github.com> a
écrit :

**Comment by QuentinBrosse** [comment]
@elapouya thanks a lot for your help! :)

So I have finally implemented it with `tempfile`:

```py
doc = DocxTemplate(template_path)

tmp_img_file = tempfile.NamedTemporaryFile(delete=None, suffix='.jpg')
img_blob = base64.urlsafe_b64decode(profile.signature_base64)
tmp_img_file.write(img_blob)
tmp_img_file.close()
signature = InlineImage(doc, tmp_img_file.name)

jinja_env = jinja2.Environment(autoescape=True)

context = {
    # ...
    'signature': signature,
}

doc.render(context, jinja_env)

# Delete tmp file
os.unlink(tmp_img_file.name)
```

I don't have error anymore but my generated document have this XML code (in red) and not the image.

<img width="639" alt="screen shot 2018-05-01 at 22 18 45" src="https://user-images.githubusercontent.com/10938538/39491820-dd238910-4d8d-11e8-819b-cf349f8f5952.png">

In the XML, the original file name is kept (in blue) but in `UNZIPPED_FILE/word/media` I have my image named `image1.jpg`. The XML doesn't have the right image name (`tmpfyu88dim.png`) but the `media` directory has it `image1.jpg`, so there is a mismatch.

I can't find why, do you have an idea?

Thanks a lot :)

**Comment by elapouya** [comment]
In your example you are deleting temporary file *before* saving the
generated docx : did you tried *after* doc.save('destfile.docx') ?

2018-05-01 22:28 GMT+02:00 Quentin Brosse <notifications@github.com>:

**Comment by QuentinBrosse** [comment]
Yes, I have already try this. :/
Here is my full rendering code (it is a Django view):
```py
def convention_show(request, convention_id):

    # [...]
    profile = Profile.objects.filter(user=request.user).get()
    # [...]

    doc = DocxTemplate(template_path)

    signature = None
    tmp_img_file = None
    if profile.signature_base64:
        tmp_img_file = tempfile.NamedTemporaryFile(delete=None, suffix='.jpg')
        img_blob = base64.urlsafe_b64decode(profile.signature_base64)
        tmp_img_file.write(img_blob)
        tmp_img_file.close()

        signature = InlineImage(doc, tmp_img_file.name)

    jinja_env = jinja2.Environment(autoescape=True)

    context = {
        # [...]
        'signature': signature,  # `{{ signature }}` in my template
    }

    doc.render(context, jinja_env)

    content_type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    response = HttpResponse(content_type=content_type)
    response['Content-Disposition'] = 'attachment; filename={}.docx'.format(
        convention_title
    )

    doc.get_docx().save(response)

    # I just test to save the document to my local hard drive.
    # It does not work neither.
    # doc.get_docx().save("/Users/quentinbrosse/Desktop/file.docx")

    if tmp_img_file:
        os.unlink(tmp_img_file.name)

    return response
```

Il work the same as the previous example.
> In the XML, the original file name is kept (in blue) but in UNZIPPED_FILE/word/media I have my image named image1.jpg. The XML doesn't have the right image name (tmpfyu88dim.png) but the media directory has it image1.jpg, so there is a mismatch.

Thanks a lot for your help @elapouya :)

**Comment by elapouya** [comment]
It seems to work with my example, the only difference is that the source image is not taken from database (I modified the inline_image.py test script): 

```
from docxtpl import DocxTemplate, InlineImage
# for height and width you have to use millimeters (Mm), inches or points(Pt) class :
from docx.shared import Mm, Inches, Pt
import tempfile
import os

tpl=DocxTemplate('test_files/inline_image_tpl.docx')

tmpfile = tempfile.NamedTemporaryFile(delete=None, suffix='.png')
with open('test_files/django.png') as fh:
    tmpfile.write(fh.read())
    tmpfile.close()

context = {
    'myimage' : InlineImage(tpl,'test_files/python_logo.png',width=Mm(20)),
    'myimageratio': InlineImage(tpl, 'test_files/python_jpeg.jpg', width=Mm(30), height=Mm(60)),

    'frameworks' : [{'image' : InlineImage(tpl,tmpfile.name,height=Mm(10)),
                      'desc' : 'The web framework for perfectionists with deadlines'},

                    {'image' : InlineImage(tpl,'test_files/zope.png',height=Mm(10)),
                     'desc' : 'Zope is a leading Open Source Application Server and Content Management Framework'},

                    {'image': InlineImage(tpl, 'test_files/pyramid.png', height=Mm(10)),
                     'desc': 'Pyramid is a lightweight Python web framework aimed at taking small web apps into big web apps.'},

                    {'image' : InlineImage(tpl,'test_files/bottle.png',height=Mm(10)),
                     'desc' : 'Bottle is a fast, simple and lightweight WSGI micro web-framework for Python'},

                    {'image': InlineImage(tpl, 'test_files/tornado.png', height=Mm(10)),
                     'desc': 'Tornado is a Python web framework and asynchronous networking library.'},
                    ]
}

tpl.render(context)
tpl.save('test_files/inline_image.docx')
os.unlink(tmpfile.name)
```

May be your image is bad. 
Note that this is normal to not have the same image name in document.xml and the file in media/ : 
You have to look word/_rels/document.xml.rels which links the filename in documents.xml and the one in media/ directory.

Could you send me an exemple of value for `profile.signature_base64`, so I can test myself ?

**Comment by elapouya** [comment]
could you try {{myimage|safe}}

Le lun. 7 mai 2018 à 22:23, Quentin Brosse <notifications@github.com> a
écrit :

**Comment by elapouya** [comment]
You can close.
I will work to modify my code so it will be marked as safe internally

Le mar. 8 mai 2018 à 08:24, Quentin Brosse <notifications@github.com> a
écrit :

**Comment by QuentinBrosse** [comment]
Ok, thanks for your help and for the library! :)

**Comment by elapouya** [comment]
I published docxtpl 0.4.10 that now manages autoescaping : no need to put
the '| safe' filter anymore !

2018-05-08 8:56 GMT+02:00 Quentin Brosse <notifications@github.com>:

**Comment by QuentinBrosse** [comment]
What a reactivity, thanks a lot !

**Comment by rishi1804** [comment]
how can I fetch image from web and pass it in InlineImage? please provide an example if possible?
