### ISSUE TITLE
Can python-docx-template parse Word document? 

### ISSUE THREAD

**Issue by benbendemo** [elapouya/python-docx-template#115]
Hi,

I wanna use this package to parse the tags and records in document.xml(Assume document.xml was the file which contains the content of my WORD document.) file after my WORD document was unzipped.

Can python-docx-template do this? I didn't find how to figure this in package documentation.

**Comment by elapouya** [comment]
Assume your xml document has been read and put in the 'my_xml' variable, try this hack:

```python
        tpl = DocxTemplate(None)
        xml = tpl.patch_xml(my_xml)
        xml = tpl.render_xml(xml, context, jinja_env)  #jinja_env is optional
```

**Comment by benbendemo** [comment]
Thanks for your reply,i have tried as your instruction,it didn't work. 

My request is,use python-docx and python-doc-template package to read an already exist XXX.docx document,then replace the content i wanna change that was defined in jinja template.

Can this be worked out? Really appreciate your work.
