### ISSUE TITLE
Simple problem with expressions (math and strings)

### ISSUE THREAD

**Issue by Sup3rGeo** [elapouya/python-docx-template#116]
Hi,

I am having a problem where while this works inside a template file:

`{{ '\t\t\t\t\t\t\t\t\t\t' }} Test`

This doesn't:

`{{ 10*'\t' }} Test`

I get only just `Test`, with no space from the left margin at all.

Does anyone know why? Thanks!

**Comment by elapouya** [comment]
I am not sure Jinja2 is able to do that (10*'a string')
You should do that at python side :
context['tabulations'] = 10*'\t'
and then in the template :
{{ mytabluations }} Test

**Comment by elapouya** [comment]
typo : context['mytabulations'] = 10*'\t'

**Comment by Sup3rGeo** [comment]
Jinja2 docs say it should be possible:
http://jinja.pocoo.org/docs/2.10/templates/#math

Can you confirm it does not work with `python-docx-template` ?

**Comment by elapouya** [comment]
I confirm there is an escaping issue : jinja2 actually see {{ 10 *
&apos;\t&apos; }}  I will fix that soon...

**Comment by Sup3rGeo** [comment]
Here they are:

[report.docx](https://github.com/elapouya/python-docx-template/files/2005956/report.docx)
[report_template.docx](https://github.com/elapouya/python-docx-template/files/2005957/report_template.docx)

**Comment by elapouya** [comment]
The document is correctly generated (Yours and mine), I can see the 10 '\t' inside the generated document, see my snapshot (libreoffice) I have what you expected. Could you send me a snapshot of your screen including the top rule (so I can see tabs markers).

![test_tabs](https://user-images.githubusercontent.com/888300/40082156-708674d0-5890-11e8-8728-e727af42dc2b.png)

**Comment by Sup3rGeo** [comment]
Well, I guess it is a good thing that it works on your case!
What I see when opening the attachment in my last post is this:

![image](https://user-images.githubusercontent.com/20566367/40101276-41bcdb9c-58e7-11e8-8652-d39706c48d38.png)

**Comment by Sup3rGeo** [comment]
So it really seems to be something with Word 2016, because I get same results as you in WordPad:

![image](https://user-images.githubusercontent.com/20566367/40101434-b3b5fcb0-58e7-11e8-873e-4bdf9f41d6fc.png)

Is it fixable for Word 2016?
Thanks for the help so far!

**Comment by elapouya** [comment]
I created a new version 0.4.11 to better manage tabs : the solution is to use Richtext : see documentation in 'Word 2016' chapter.

**Comment by Sup3rGeo** [comment]
First of all, thanks for the help so far!

The RichText does the trick, although I have now to format whitespaces in the python code instead of leaving it on the template file (e.g. my dictionaries now have formatted RichText instead of just plain data).

I am facing another troubling issue now, out of the blue I cannot open the generated docx report on word 2016 anymore:

![image](https://user-images.githubusercontent.com/20566367/40166912-ff9bc8ac-59bf-11e8-8a43-a334b4c53106.png)

This is the generated docx file:

[report.docx](https://github.com/elapouya/python-docx-template/files/2012387/report.docx)

Do you know what is the problem? Also, I get very different results when opening this on WordPad (which looks ok) and LibreOffice Writer (richtext doesn't appear, other things messed up as well).

**Comment by Sup3rGeo** [comment]
It was working fine for me too, but when I was playing with it suddenly I could not open the generated docx anymore.
Will post the template and script as soon as I can.

Another interesting fact is that when I use `python-docx` directly I have no problem at all with tabs, spaces or newlines.

**Comment by elapouya** [comment]
This is normal, with python-docx you are building an docx file from zero,
so it is "easy" to manage every aspect of the document generation.
With docxtpl, the document is already created and must be cleaned to have
jinja2 running, and it is not obvious to modify xml parts (escaping etc...)
after jinja2 rendering.
this is the reason why you have to use Richtext so I can have a little
control on generated xml.
