### ISSUE TITLE
Whitespaces being removed (happens randomly)

### ISSUE THREAD

**Issue by Sup3rGeo** [elapouya/python-docx-template#117]
Hi, 

I have a simple template file document like
```
{{ '        ' }} Test
```
And from time  to time, when I compiled it, the resulting doc does not have the leading whitespaces.

However this is not 100% reproducible. Sometimes it happens when you just change the number of spaces and run.

Last time it happened to me when I changed changing to this:
```
{{ 1==1 }}
{{ '           ' }} Test
```
And then whitespaces disappeared again. Then sometimes when I change some little thing (change from whitespaces to ------ and then back) it works. 

I am using word from Office 2016.

**Comment by elapouya** [comment]
Please, provide the template and the generated document when the problem occurs.

**Comment by elapouya** [comment]
the solution is to use Richtext : see documentation in 'Word 2016' chapter.
