### ISSUE TITLE
Icons aren't right in 'Large' view on Windows

### ISSUE THREAD

**Issue by joncoop** [elapouya/python-docx-template#119]
In list view, the icon for the created document looks fine. However when viewed in large or extra large mode, the icons aren't right. They only show a tiny Word icon in the lower right corner. 

It looks like this is because the template files don't have the right icons. I'm working on Windows 8 and using Word 2013. I checked the document properties and noticed that it was created on Macintosh Word.

![icons](https://user-images.githubusercontent.com/12698453/40386195-06ee3c28-5dd7-11e8-888b-d6d59a118e2a.PNG)

**Comment by elapouya** [comment]
closing as not reproducible
