### ISSUE TITLE
Apply or keep a paragraph style using subdoc()?

### ISSUE THREAD

**Issue by 3catacres** [elapouya/python-docx-template#12]
I have a template with {{p IC2}} as a tag. The tag has a custom style applied to it in the template, such as bullet, indent, font size, etc. I run the following code using the `subdoc()` function. The text successfully replaces the tag but the style is lost. Instead of the custom style, the paragraph has the `Normal` style applied. Here is the code, which clearly is a reduced version of your `subdoc.py` example.

***
from docxtpl import DocxTemplate
tpl=DocxTemplate('test_tpl.docx')
sd = tpl.new_subdoc()
p = sd.add_paragraph('This is the text for IC2.')
context = {
	'IC2' : sd,
}
tpl.render(context)
tpl.save('test.docx')
***
I can insert text following the example given in`richtext.py` and using {{r IC2}} as the tag. The inserted text will properly inherit the paragraph style but new lines (separated by `\n`) do not.  For example, the line will be properly indented according to the style but will not have the bullet that is also part of the style.

**Comment by elapouya** [comment]
That sounds normal:
{{p }} will replace the current paragraph, style included.
{{r }} is the solution for simple strings : no need to use subdocument.
otherwise, for complex subdocument (do you really need that ?) use {{p }} and put styling INSIDE subdoc
(please consult python-docx documentation for that)

**Comment by 3catacres** [comment]
I do not need to use subdoc. I tried to use {{r }} following the RichText.py example.  The problem is this:

If I enter something like `RichText{'This is the first entry, it should have a bullet.\n The second entry should have a bullet but does not.')`, I get the following.
***
* This is the first entry. It should have a bullet.

The second entry should have a bullet but does not.
***
Word shows that the second entry has the custom style but, as shown above, it does actually show the bullet. I've tried with both one newline character (`\n`) and two (`\n\n`). I also tried `RichText('Some text', style = 'CustomStyle')` but no luck.

**Comment by elapouya** [comment]
I think MS Word will put one bullet per 'run' only, in your case, you have
only one run, so ...
If the goal is to have multiple lines, a loop could be a good workaround :
{%p for richline in richlines %}
{{r richline}}
{{%p endfor %}}

2015-11-09 23:29 GMT+01:00 3catacres <notifications@github.com>:

**Comment by 3catacres** [comment]
I will have to sit down and play around with your suggestion. Thank you for your help and especially for writing python-docx-template. It will save me lots of time.

**Comment by 3catacres** [comment]
I was not able to play around with your suggest until now. Happily, I was able to get my bullet lists for each entry using your loop suggestion.  Thank you again.
