### ISSUE TITLE
My database has a html inserted by a rich text editor. I want to insert it into the word document as it is

### ISSUE THREAD

**Issue by juventusforever** [elapouya/python-docx-template#120]
How to solve it?
Thanks

**Comment by elapouya** [comment]
{{yourhtmlvar|e}} 'e' will escape your html code to be visible as an html
example.
if you want your html to be rendered as entered in your editor, it is not
possible.

Le mar. 29 mai 2018 à 06:21, juventusforever <notifications@github.com> a
écrit :

**Comment by juventusforever** [comment]
Thanks.
And I want to know how to insert some content in a word file(.docx) as the subdoc now?

**Comment by elapouya** [comment]
Please, have a look at documentation here : http://docxtpl.readthedocs.org/
There are also a lot of exemples in tests/

Le ven. 1 juin 2018 à 11:13, juventusforever <notifications@github.com> a
écrit :

**Comment by juventusforever** [comment]
Thanks for replying so quickly
if I want html to be rendered as entered in the rich editor.What should I do?

**Comment by elapouya** [comment]
develop a tool that converts html into xml tags for Microsoft Word (that I
absolutely don't know how to do it).

Le ven. 1 juin 2018 à 11:44, juventusforever <notifications@github.com> a
écrit :

**Comment by premudeshi** [comment]
[html2docx](https://github.com/pqzx/html2docx) is similarly based on python-docx, is there any way to use these two together to place html rendered content in a specific spot?
