### ISSUE TITLE
[change total paragraph or the specific words in one paragraph]

### ISSUE THREAD

**Issue by vatn** [elapouya/python-docx-template#121]
Hello, 

I have a question for "paragraph".
I have seen in the document, the tag of paragraph is {%p ......  %}. I just didn't succeed to know how to use these tags to do more operations on paragraph ?

Is that possible to replace totally one paragraph  by an another one, or delete one paragraph or just replace a specific word in one paragraph ?

_**For example , I have a .docx as the following (3 paragraph):**_ 

1) The idea is to begin to create an example of the document you want to generate with microsoft word, it can be as complex as you want : pictures, index tables, footer, header, variables, anything you can do with word.

2) Now you can use python-docx-template to generate as many word documents you want from this .docx template and context variables you will associate.

3) Note : python-docx-template as been tested with MS Word 97, it may not work with other version.

**_I want to do :_** 
Replace the paragraph 2) by " Then, as you are still editing the document with microsoft word, you insert jinja2-like tags directly in the document."

Delete 3) 

Replace the word "want" in the first paragraph by "like".

**_So finally, the result should be :_** 

 1) The idea is to begin to create an example of the document you **like** to generate with microsoft word, it can be as complex as you **like** : pictures, index tables, footer, header, variables, anything you can do with word.

2) Then, as you are still editing the document with microsoft word, you insert jinja2-like tags directly in the document.

Thank so much !

**Comment by elapouya** [comment]
when you use {%p %} this means : "remove the paragraph where the tag is
located", so this permit to do such a thing :

{%p if iwantthis %}

here is the conditionnal paragraph

{%p endif }

When you write above in MS Word, you have created 3 paragraphs, and
obviously, you do not want to have paragraphs containing {%p if iwantthis
%} and  {%p endif }  in your final document, that is why it is necessary to
use 'p'.
If you forget to use 'p', you may have unexpected results like having blank
lines

If you want to replace/delete a word : just use standard tag :

here is the{% if iwantthis %} conditionnal{% endif %} word

**Comment by vatn** [comment]
Hello, 
I test and it works !!!!!!
Thank you so much !
