### ISSUE TITLE
No option to set font

### ISSUE THREAD

**Issue by f1remind** [elapouya/python-docx-template#122]
I'm currently creating a tool to generate reports using strings and style-settings from a database.
This also requires me to set the font.

I'm adding runs dynamically using the following annotation:
{%r for entry in entries %}{{r entry }}{%r endfor %}

I can add runs using R(text, **settings) which works great for most things.
These options seem to be restricted to the following options however:
style, color, highlight, size, bold, italic, underline and strike

No option to set the font.

**Comment by elapouya** [comment]
Fonts are not currently supported, nevertheless you can define styles
having the fonts you want in the docx template and then specify these
styles via docxtpl RichText

**Comment by f1remind** [comment]
That's not really viable in my scenario. I've created a simple modification to use fonts, maby you can integrate it aswell, if it's any help.
#123

**Comment by elapouya** [comment]
fixed in 0.4.12
