### ISSUE TITLE
Odd error on Windows while opening docx

### ISSUE THREAD

**Issue by cristianocca** [elapouya/python-docx-template#125]
Document works fine, however, it always raises an error before opening.

"Can't open document <name> because there is an error with its contents"
Details:
Unspecified Error
Location: /word/header1.xml

I'm still messing around with the document to see when the error goes away but seems to be either related with images (existing images) or headers (it's odd I know the error talks about headers but it's not strictly that).

Document opens fine on Mac

**Comment by cristianocca** [comment]
Hmm that's strange, I'm using (Windows) Word 2013 and it always opens with an error prompt, which can be accepted and the document opens normally in read-only mode.
If you are using another version makes me thing there's some compatibility issues.

Capture of the error (it's in spanish but the translation is pretty much what I wrote above)

![cap1](https://user-images.githubusercontent.com/8573267/41802011-754244d6-7654-11e8-85f2-935676b48e53.PNG)

**Comment by elapouya** [comment]
I am using Word 2007 on Windows...
I will look inside the docx to check the "error"...

Le sam. 23 juin 2018 à 00:43, Cristiano Coelho <notifications@github.com> a
écrit :

**Comment by elapouya** [comment]
I have checked the header1.xml file inside the generated docx : all seems correct as an XML file.
I cannot go further as I do not have Word 2013.
May you can try to remove little by little what you have in your header to isolate what element caused the error...

**Comment by cristianocca** [comment]
Yes, I have tried that and the issue seems a bit random. If I remove the header completely the issue goes away, but if I put any text there the issue comes back. Also, if I remove 2 or 3 of the pictures in the last page the issue also goes away, which is odd because it's unrelated to the header!
The same error also happens on Word for Android, so it's really something about Microsoft's implementation.

My guess is that the combination of inline pictures and headers is creating some invalid XML somewhere in the document and some readers just ignore it and others are more picky and complain about it.

**Comment by elapouya** [comment]
Please use latest docxtpl version and try workaround in #243

**Comment by cristianocca** [comment]
Still happening with the latest version. The workaround is nice, but I'm definitely not using duplicated images, so it really doesn't apply to this issue.
