### ISSUE TITLE
Using \a without RichText

### ISSUE THREAD

**Issue by fiterV** [elapouya/python-docx-template#126]
So I need to use a line break in my .docx template, but not one that produces an effect like Shift+Enter(\n) but just Enter(starting new paragraph).

```
tpl = DocxTemplate('sample.docx')
context = {
           'newline': '\a',
}
tpl.render(context)
```
This code throws an error: **lxml.etree.XMLSyntaxError: Opening and ending tag mismatch** .
But when instead of '\a' I'd use R('\a') and raw tag works fine, but with one problem: **all the styles are reset to default** - which is also bad in my case.

Why using '\n' without R is fine, but when it comes down to '\a' I get an error?

Links to samples:
**sample.docx**: https://transfer.sh/lOjGr/sample.docx
**main.py working version with \n**: https://transfer.sh/vD9ZF/escape.py
**main.py error version with \a**: https://transfer.sh/qyQ8U/escape.py

As you can see **they differ only in 1 symbol.**

**Comment by elapouya** [comment]
Could you try docxtpl.NEWLINE_XML instead of '\a'

**Comment by elapouya** [comment]
... And use {{newline|safe}} in your template.

**Comment by fiterV** [comment]
Tried NEWLINE_XML , got same result.
Tried NEWPARAGRAPH_XML, seems to work but drops the font to default, not the one I'm using in template.

**Comment by dreamjole** [comment]
I have the same problem as you mentioned above, and how did you finally solve it?

**Comment by elapouya** [comment]
Closing as no more solution without using RichText.
