### ISSUE TITLE
Numbered Lists

### ISSUE THREAD

**Issue by pablosolar** [elapouya/python-docx-template#127]
Hello @elapouya!

First of all, thank you for the marvelous work about docxtpl!! I would like to ask you if there is any simple way of create a numbered list in the template using this repo. For example, something like:

i=1
{%tr for text in infos %}
   {{ i }}. {{ text }}
   i = i+1
{%tr endfor %}

I tried this but without success. 

Thank you so much in advance. Regards!!

**Comment by elapouya** [comment]
your i=i+1 cannot work in a template,

try :

{%tr for text in infos %}
{{ loop.index }}. {{ text }}
{%tr endfor %}

Le mar. 10 juil. 2018 à 16:11, pablosolar <notifications@github.com> a
écrit :
