### ISSUE TITLE
Non dynamic content in a table

### ISSUE THREAD

**Issue by rbadenhorst** [elapouya/python-docx-template#132]
Good day,

I would like to know if its possible to insert content from a tag into a table where I'm not using a for loop as shown in the order_tpl examples. I want to use it in the same way we use {{ tagname }} in a regular paragraph.

**Comment by rbadenhorst** [comment]
Ok sure, I think a screenshot of the table will show it more clearly.

<img width="992" alt="screen shot 2018-07-31 at 8 32 12 am" src="https://user-images.githubusercontent.com/41937063/43441805-5cc511e8-949c-11e8-91f4-f931157de043.png">

As you can see i need to add the Site name, version, description, etc from my context for this render.

This scenario (as far as i see it) is not the same as the examples (e.g. order_tpl) where you'd have a blank table that will be dynamically populated with many rows.

Does that make it clear?

**Comment by elapouya** [comment]
it should work "as is" : your template is OK, save it as
my_word_template.docx for example, then the code is :

from docxtpl import DocxTemplate
doc = DocxTemplate("my_word_template.docx")context = { 'SiteName' :
'my site name', 'DefaultWebAppURL' : 'my url', etc....
}doc.render(context)doc.save("generated_doc.docx")



Le mar. 31 juil. 2018 à 08:36, rbadenhorst <notifications@github.com> a
écrit :

**Comment by rbadenhorst** [comment]
Thanks, I think there was some other bad formatting / characters. I saved only the table and it worked.

Thanks for the help!!
