### ISSUE TITLE
PackageNotFoundError

### ISSUE THREAD

**Issue by simona2017** [elapouya/python-docx-template#136]
Hi, I'm getting a PackageNotFoundError, can you please let me know how I can fix this? Thanks so much.
<img width="919" alt="screen shot 2018-08-09 at 5 02 07 am" src="https://user-images.githubusercontent.com/22427968/43889324-da63650e-9b91-11e8-97f0-1a9d4d1dfcf7.png">

**Comment by elapouya** [comment]
Hi,
Please provide your python code and the docx template.

**Comment by simona2017** [comment]
Thank you so much for your prompt reply here is the code and the file directory screenshot

```
from docxtpl import DocxTemplate
import os

def export_word(request):
    doc = DocxTemplate("my_word_template.docx")
    context = { 'company_name' : "World company" }
    doc.render(context)
    doc.save("generated_doc.docx")
```
<img width="965" alt="screen shot 2018-08-09 at 5 34 44 am" src="https://user-images.githubusercontent.com/22427968/43890930-1716c410-9b96-11e8-8f2b-b79762485c91.png">

**Comment by elapouya** [comment]
Could you try by providing the full path to "my_word_template.docx"

**Comment by simona2017** [comment]
I get the same error message. 

```
def export_word(request):
    doc = DocxTemplate("base/my_word_template.docx")
    context = { 'company_name' : "World company" }
    doc.render(context)
    doc.save("generated_doc.docx")
```

Just to make sure, the word document should be blank in this case , there are no tags embed in it. Correct?

<img width="949" alt="screen shot 2018-08-09 at 6 44 32 am" src="https://user-images.githubusercontent.com/22427968/43894327-bb350c42-9b9f-11e8-898f-01de37db90ac.png">

**Comment by elapouya** [comment]
when I say full path, I mean : /Us

**Comment by elapouya** [comment]
when I say full path, I mean : /Users/simonalambardo/the/path/to/template/my_word_template.docx
And my_word_template.docx should be NOT empty and have tags in it.
Have a look at tests/ directory in source code for examples.

**Comment by simona2017** [comment]
It worked!!! You are a GENIUS! Thank you so much!
