### ISSUE TITLE
issue with Linux

### ISSUE THREAD

**Issue by JoenyBui** [elapouya/python-docx-template#14]
Hi, 

I was able to run create the word doc successfully in windows, but it doesn't seem to render with the linux distribution I'm using (Scientific Linux 6.6).  Am I setting something wrong or is there a workaround.

Joeny

**Comment by elapouya** [comment]
Hello,

What's happening : a python error ? or does it generate a file that cannot
be read ?
On what software the template is created (not rendered) ? Open Office ?
Microsoft Word ? running on Windows or Linux through Wine ? What is the
version of microsoft word ?
For rending, I am using Ubuntu 12.04+ so it should work on every Linux
distribution with Python 2.7 : what is your python version ?
Please send me the template word file and simplified version of your
program (so I can run it easily)

Eric

2015-12-21 9:07 GMT+01:00 Joeny Bui <notifications@github.com>:

**Comment by JoenyBui** [comment]
I actually download your source code and run the test problems again to make sure, and it seems to be working as it should - so I'll keep investigating why my implementation only works on Window.  I'll let you know.  By they way, this project is really great.

**Comment by JoenyBui** [comment]
@elapouya , you can closed this issue - user error.  Sorry about that - just panicked.
