### ISSUE TITLE
Using 'render' multiple times

### ISSUE THREAD

**Issue by ahseena96** [elapouya/python-docx-template#144]
@elapouya,
Why does rendering multiple variables not work? For eg:

```
from docxtpl import DocxTemplate

doc = DocxTemplate("template.docx")
doc_date = { 'date':"14th Sept. '18" }
period_covered = { 'period':"1st January 2018 – 31st December 2018" }

doc.render(doc_date)
doc.render(period_covered)
```
It updates only the first variable.

**Comment by elapouya** [comment]
Please read examples in /tests/

Le ven. 14 sept. 2018 à 19:42, ahseena96 <notifications@github.com> a
écrit :

**Comment by elapouya** [comment]
closing as no answer

**Comment by vhomelab** [comment]
Can you point out the example to refer for multiple render?

**Comment by elapouya** [comment]
first time you render, all the {{ }} are replaced with values, if no values are given, a blank is put. so at 2nd rendering there is no more {{ }} to render.2 solutions : 
- give a context with ALL values to render, so only one rendering is needed, 
- you can escape some {{ }} for 2nd rendering (see escaping in documentation)
