### ISSUE TITLE
Assignments in template

### ISSUE THREAD

**Issue by wildmichael** [elapouya/python-docx-template#146]
Are assignments in the template possible? I.e. the way they are handled in Jinja2: http://jinja.pocoo.org/docs/2.10/templates/#assignments

**Comment by elapouya** [comment]
It should be possible, did you try ?

**Comment by themiwi** [comment]
Yes, but inside a nested loop building a table. Will retry again in a simpler setting once I'm back in the office.

**Comment by elapouya** [comment]
closing as no feedback.
