### ISSUE TITLE
Listing seems to break on ints and probably other non-string-type objects

### ISSUE THREAD

**Issue by jsve** [elapouya/python-docx-template#147]
For RichText there is a check for six.text_type, which is missing on Listing. I havn't tried on RichText, but my guess is that Ints break that to.

I was thinking that casting non-strings to strings would fix this. what do you think?

Ref:
https://github.com/elapouya/python-docx-template/blob/b987864c3f4d0d2572a16a28388fd912f06bc505/docxtpl/__init__.py#L487

**Comment by elapouya** [comment]
Good idea : Will do that soon,

Many thanks.
