### ISSUE TITLE
Deprecation Warning - Python 3.6

### ISSUE THREAD

**Issue by cristianocca** [elapouya/python-docx-template#149]
FYI. Might want to have this updated if you plan on supporting Python 3.7 (I actually don't know when is this going to be removed)

python3.6/site-packages/docxtpl/__init__.py:487: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  self.xml = escape(text).replace('\n', NEWLINE_XML).replace('\a', NEWPARAGRAPH_XML)

**Comment by elapouya** [comment]
Good Idea, will do that soon,

Many thanks.
