### ISSUE TITLE
Jinja2 Image

### ISSUE THREAD

**Issue by JoenyBui** [elapouya/python-docx-template#15]
Love the library.  I was wondering  if there is any thoughts on adding template for embedding images?

**Comment by elapouya** [comment]
You already can add images :
- create a subdocument
- add an image (see python-docx documentation)
- add the subdocument in your context dict and add a tag to your docx template to display it (see example in tests/)

**Comment by sssseossss** [comment]
Is there any way to align picture to centre?
thank you!

**Comment by elapouya** [comment]
I have not tried yet, but something like this : 
```
p =subdoc.add_paragraph(style='a_centered_style_from_template_docx')
p.add_run().add_picture(image_path_or_stream, width, height)
```

**Comment by sssseossss** [comment]
Wow!
this worked:
p=subdoc.add_paragraph()
p.alignment=WD_ALIGN_PARAGRAPH.CENTER
p.add_run().add_picture('image path', width,height)

Many thanks!
