### ISSUE TITLE
 Nested loop building a table

### ISSUE THREAD

**Issue by Echopei** [elapouya/python-docx-template#150]
template:
![image](https://user-images.githubusercontent.com/10030002/46778926-67589c80-cd48-11e8-88ff-c4992a445cc5.png)

actual result:
![image](https://user-images.githubusercontent.com/10030002/46778932-6d4e7d80-cd48-11e8-9001-03b269fe0b83.png)

and I want this:
![image](https://user-images.githubusercontent.com/10030002/46778938-72abc800-cd48-11e8-8330-0a5fd24e4ded.png)

and code
```
from docxtpl import DocxTemplate

tpl=DocxTemplate('test_tpl.docx')
drugs = [
    {
        'drug_name': "Name1",
        'drug_1': 'Name1',
        'drug_2': 'Name1',
        'varys':[
            {'range':'ha1','vari':'ha1','result':'ha1'},
            {'range':'ha2','vari':'ha2','result':'ha2'}
        ]
    },
    {
        'drug_name': "Name2",
        'drug_1': 'Name2',
        'drug_2': 'Name2',
        'varys':[
            {'range':'ha3','vari':'ha3','result':'ha3'},
            {'range':'ha4','vari':'ha4','result':'ha4'}
        ]
    },
]

context = {
    'drugs':drugs
}

tpl.render(context)
tpl.save('test.docx')
```

**Comment by yinlonghui** [comment]
I am having the same problem...

**Comment by carlsummer** [comment]
I am having the same problem...

**Comment by llyzhizhe** [comment]
this is my template:
![image](https://user-images.githubusercontent.com/27886426/56465798-d8d08080-6438-11e9-93a1-cb95487b7ddc.png)

result:
![image](https://user-images.githubusercontent.com/27886426/56465802-f00f6e00-6438-11e9-825e-8f23778dc4d6.png)

**Comment by Echopei** [comment]
> this is my template:
> ![image](https://user-images.githubusercontent.com/27886426/56465798-d8d08080-6438-11e9-93a1-cb95487b7ddc.png)
> 
> result:
> ![image](https://user-images.githubusercontent.com/27886426/56465802-f00f6e00-6438-11e9-825e-8f23778dc4d6.png)

what I want:

![image](https://user-images.githubusercontent.com/10030002/56479799-d417d500-64e9-11e9-87ed-1f6282ac4c6e.png)

and your method result:
![image](https://user-images.githubusercontent.com/10030002/56479828-f4479400-64e9-11e9-97fd-613f016efc36.png)

it does not work

**Comment by elapouya** [comment]
I would not use {% vm %} in the first 3 columns.
