### ISSUE TITLE
updateFileds automatically

### ISSUE THREAD

**Issue by Echopei** [elapouya/python-docx-template#151]
I want Word can updateFields automatically.
modify settings.xml

**Comment by Echopei** [comment]
![image](https://user-images.githubusercontent.com/10030002/46787892-65540500-cd6b-11e8-8d56-c354d5bb6b81.png)

insert  <w:updateFields/>

and it works in word2010
![image](https://user-images.githubusercontent.com/10030002/46787942-8c123b80-cd6b-11e8-8418-9412cefd0a1f.png)


but it does not word in word2007, why 
Thank you very much

**Comment by elapouya** [comment]
What is updateFields ?

**Comment by Echopei** [comment]
when I open word,  I hope word can reminder to update field.  
For example, update fields can update word page number

**Comment by carstenfjelkstrup** [comment]
I solved it like this:
```
def set_updatefields_true(docx_path: str):
    """ Opens the docx and adds <w:updateFields w:val="true"/> to
       (docx_path)/word/settings.xml to enforce update of TOC (and
       other fields marked as dirty) on first open.
       Saves the file afterwards.

    Arguments:
        docx_path {str} -- Absolute path to docx
    Returns:
        Nothing
    """
    namespace = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
    doc = Document(docx_path)
    # add child to doc.settings element
    element_updatefields = lxml.etree.SubElement(
        doc.settings.element, f"{namespace}updateFields"
    )
    element_updatefields.set(f"{namespace}val", "true")
    doc.save(docx_path)
```

**Comment by Echopei** [comment]
I try like this
```
from docx import Document
import lxml
def set_updatefields_true(docx_path):
    namespace = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
    doc = Document(docx_path)
    # add child to doc.settings element
    element_updatefields = lxml.etree.SubElement(
        doc.settings.element, f"{namespace}updateFields"
    )
    element_updatefields.set(f"{namespace}val", "true")
    doc.save(docx_path)
```

and I have 3 questions:
1. this does not support word2007, cannot open docx
![image](https://user-images.githubusercontent.com/10030002/49206914-88577880-f3ee-11e8-8eae-81f91dd1fd8a.png)

word2010 is Ok
2. f"{namespace}updateFields"   thsi may be does not support python2.7
3.  namespace = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"   
  why namespace is website

**Comment by carstenfjelkstrup** [comment]
1) Word 2007 is not OpenXML, so I think you need to use macros? Try to take a look at these: 
[https://www.google.com/search?q=word+2007+update+fields+programatically](url)
2) Try plain string concatenation, e.g. `namespace + 'updateFields'`
3) It is convention, that XML schemas have a namespace which is a URI, read more: [https://www.w3schools.com/xml/xml_namespaces.asp](url)

**Comment by Echopei** [comment]
I got it.
Many thanks.

**Comment by PartPerBillion** [comment]
> I got it. Many thanks.

Hi @Echopei 
Can you share the final solution? 
For me the file is saved new, but the 'table of contents' field is not updated and also the namespace. 
"{[http://schemas.openxmlformats.org/wordprocessingml/2006/main}]" does not exist.
Thanks!

**Comment by ajaydevaraj63** [comment]
hi , i added toc and then updated document with some images and table , then i saved to another folder from my linux system using python,but toc page number is not updated why?

**Comment by elapouya** [comment]
this is not supported yet
