### ISSUE TITLE
Template syntax error unexpected char '

### ISSUE THREAD

**Issue by sandeeprah** [elapouya/python-docx-template#156]
When i try to use a custom filter with a string argument like this 
{{ myvalue|myfilter('myargument') }} i get an error 

jinja2.exceptions.TemplateSyntaxError:unexpected char '''.

Please help with an example of custom filter which shows how to pass a string argument. Integer  arguments are passed without issues. 

I have later discovered while going through other reported issues, that this is due to the fact that the straight quotes ' are automatically converted to curly quotes ‘ which are not identified by jinja as valid character. While pasting the quote from another editor like atom works but this does not look like a good solution. One has to modify the autoreplace default setting of word which automatically changes straight quotes to curly quotes.  

Has any body tried the patch_xml() fix as reported in this thread 
[https://github.com/elapouya/python-docx-template/issues/85](url)

Pasting the code at line 47 does not help me.

**Comment by deric92** [comment]
Hi @sandeeprah , 
I don't have that much experience working with this library yet but I have managed to successfully use many custom filters that pass strings in as arguments and have not experienced this error.

Example of a filter I use regularly:
`{{ some_date_value|toDate('June 3, 1990') }}`

If you provide more context I can try to help you figure out where the error is coming from.

**Comment by sandeeprah** [comment]
Dear Deric,

I have created a small demo project to demonstrate the issue with the custom filter for use along with this library to generate word documents from a word template. The link is given below. Exception occurs if a filter is used which has a string argument (the 4th jinja statement in the word file). Delete the last statement and it works fine. 

I am desperate to see this fixed or would like to know what is the mistake in my usage. 

Executing **_wordgen.py_** creates **test_output.docx** file from **_test_template.docx_**

[https://github.com/sandeeprah/autodoc](url)

> Hi @sandeeprah ,
> I don't have that much experience working with this library yet but I have managed to successfully use many custom filters that pass strings in as arguments and have not experienced this error.
> 
> Example of a filter I use regularly:
> `{{ some_date_value|toDate('June 3, 1990') }}`
> 
> If you provide more context I can try to help you figure out where the error is coming from.

**Comment by sandeeprah** [comment]
Yes Deric, issue is with Word autoreplace. I am closing this issue. thanks for help.

**Comment by deric92** [comment]
No problem. Glad I could help.

**Comment by elapouya** [comment]
Could you provide me the docx template that HAS this "smart-quote", may be I can update the code to manage this automatically ?

**Comment by deric92** [comment]
Here is that same sample document that @sandeeprah sent me for testing. It HAS the smart-quotes in it.

[https://github.com/sandeeprah/autodoc/blob/master/test_template.docx](url)

**Comment by sandeeprah** [comment]
Thanks that would be great. In the settings that I work, people are not
programmers and it is difficult to persuade them to switch off auto
replacement or use ctrl+z after each use
 The github location I shared had the sample minimal file.

**Comment by elapouya** [comment]
Should work now with smart quotes and docxtpl >= 0.5.10

**Comment by deric92** [comment]
Awesome!! Nice work! 
That should remove some friction for new developers using the library for the first time since Word seems to always have the smart quotes enabled by default.

**Comment by sandeeprah** [comment]
Thanks elapouya. thanks a lot.. yes it works now but with single smart quotes. double smart quotes do not work still...I hope you will like to do something about double quotes as well.

**Comment by elapouya** [comment]
Just give me a docx with that smart double quotes

Le mar. 20 nov. 2018 à 19:46, sandeeprah <notifications@github.com> a
écrit :

**Comment by sandeeprah** [comment]
Check this one out. Only the smart double quotes inside the filter needs to be straightened up. 

[test_template.docx](https://github.com/elapouya/python-docx-template/files/2601206/test_template.docx)

**Comment by elapouya** [comment]
I released 0.5.11 : with smart double quote fix.

Le mar. 20 nov. 2018 à 20:16, sandeeprah <notifications@github.com> a
écrit :
