### ISSUE TITLE
Image cannot be displayed 

### ISSUE THREAD

**Issue by KRitter90** [elapouya/python-docx-template#157]
Hi there, 
first of all I really like your project, it's very useful and easy to use. 
Now to the issue:
I generated a template to insert multiple tables and multiple pictures in the same word template .docx and the python code and function I wrote in order to render these has worked very well.
Since yesterday, however the figures are not displayed in the generated word document anymore. I get the error message: 'This image cannot currently be displayed' and the red cross in the upper left corner.
Was there an update that might have affected this?

**Comment by KRitter90** [comment]
[UPDATE]

I found out that it happens when I load the module 'from docxtpl import DocxTemplate' into the subfunction although I do not fully understand where this is comming from. 

**Code that does not work inside a subfunction:**

    import jinja2 # 'pip install jinja2'
    **from docxtpl import DocxTemplate
    tpl=DocxTemplate(template)**
    if dict2 == None:
        MultiDict=dict1
    else:
        MultiDict={**dict1, **dict2}
    jinja_env = jinja2.Environment(autoescape=True) # still unclear
    tpl.render(MultiDict, jinja_env) # replace string lines with figures and tables
    # word document with figures and table contents
    tpl.save(Path +'AutomatedWordDocument.docx')  
    

Instead I have to generate the tpl outside my subfunction, then it seems to work fine. Is there any chance to fix this?

**Comment by elapouya** [comment]
If the code works outside a function, it should work into.
As the problem you described is about the images only (The word document is still generated),
my guess is that you may have a scope problem in that subfunction : did you try to print context dict in both cases (inside or not inside a subfunction) ?
Please provide a simple testcase (docx template, python script and one image) that reproduce your problem so I can debug it.
