### ISSUE TITLE
sub-document (python-docx features not supported - Tables and Default Styles)

### ISSUE THREAD

**Issue by chrismik** [elapouya/python-docx-template#16]
Thanks for writing this module very handy.

I am comparing features of building document content via **(A)** new python-docx document, and **(B)** python-docx-template subdocument. The hope is the two will produce equivalent content, although the following differences are noted below. Are these known limitations? 

1. B does not render any tables, where A does. This is problematic as I need more control over table creation (i.e. merge, style per row and cell, etc.).

2. B throws exception `raise KeyError("no style with name '%s'" % key)` on setting default style, i.e. `paragraph.style = 'List Bullet'`

code snip below:

    def addDocContent(doc):
    "Adds content to a python-docx object"
    recordset = [
                {'qty' : 1, 'id' : 101, 'desc' : "Spam"},
                {'qty' : 2, 'id' : 42, 'desc' : "Eggs"},
                {'qty' : 3, 'id' : 631, 'desc' : "Spam,spam,eggs,and spam"},
                ]
 
    doc.add_heading('Document Title', 0)
    
    p = doc.add_paragraph('A plain paragraph having some ')
    p.add_run('bold').bold = True
    p.add_run(' and some ')
    p.add_run('italic.').italic = True
    
    h = doc.add_heading('Heading, level 1', level=1)
    #h.style = 'Intense Quote'
    #doc.add_paragraph('Intense quote', style='IntenseQuote')
    
    p = doc.add_paragraph(
        'first item in unordered list'#, style='ListBullet'
    )
    #p.style = 'List Bullet'
    
    p = doc.add_paragraph(
        'first item in ordered list'#, style='ListParagraph'
    )
    #p.style = 'List Paragraph'
    
    doc.add_picture('monty-truth.png', width=Inches(1.25))
    
    #python-docx-template subdoc will not render this table
    table = doc.add_table(rows=1, cols=3)
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Qty'
    hdr_cells[1].text = 'Id'
    hdr_cells[2].text = 'Desc'
    for item in recordset:
        row_cells = table.add_row().cells
        row_cells[0].text = str(item['qty'])
        row_cells[1].text = str(item['id'])
        row_cells[2].text = item['desc']
    
    doc.add_page_break()

**Comment by elapouya** [comment]
I confirm there is a bug about tables and styles for subdocs : I am looking for a fix...

**Comment by elapouya** [comment]
I corrected the bug : see tests/subdoc.py to see how tables are inserted.
