### ISSUE TITLE
p tag without a linebreak in it make the output docx error open by word 2013

### ISSUE THREAD

**Issue by yangmqglobe** [elapouya/python-docx-template#161]
I have a trouble using this package recently, after a lot of debug, I though that I should share this issue with all developers.
When using the p tag but you don't have a linebreak in it, the output docx file open by word will get an error and if you choose to fix it, the p tag area will be blank. Here is an example:
```
{%p if some_list|length > 0 %}
{%p for item in some_list %}
{{ item }}
{%p endfor %}
{%p else %}nothing in the list{# no linebreak here #}{%p endif %}
```
when the list is empty, will make the output docx got an error open by word 2013. I try to remove the p in the endif tag but it will course an non-closing tag. And the right code should be:
```
{%p if some_list|length > 0 %}
{%p for item in some_list %}
{{ item }}
{%p endfor %}
{%p else %}
nothing in the list{# a linebreak here #}
{%p endif %}
```
Is this the design of a p tag work or something I missing? I can not find some thing in the source code.
And the debug sucks, it took me so long to find out the bug code(I have a big template), any enhancement on the exception information in the future?

**Comment by elapouya** [comment]
{%p xxx %} is designed to remove the paragraph where it is located.
Here, you have 2 {%p xxx %} on the same paragraph it conducts remove 2 times the same paragraph : obviously it generates bad xml code.
As I am using pattern matching it is not easy  to manage this case, so : 
only one {%p xxx %} is allowed per paragraph.
I agree there is a lack of documentation on this point, I will update it.
