### ISSUE TITLE
powerpoint template?

### ISSUE THREAD

**Issue by joolius** [elapouya/python-docx-template#165]
Hello.

I was curious, could the same approach used in DocxTemplate be used in creating powerpoint slides? There is a package called python-pptx, and I thought that it could also be extended to use jinja. Has anyone tried that?

Thanks

**Comment by elapouya** [comment]
docxtpl uses 'docx' package to read and write docx files. But the templating part is done in docxtpl.
So, if python-pptx is able to read and write pptx, a lot of code from docxtpl could be reused for a "pptxtpl" package to create.

**Comment by tigre-bleu** [comment]
@elapouya Basically, it seems that python-pptx can read and write pptx. I use extensively docxtpl to generate reports using Django and that would be awesome to also generate the presentations using the same database and a similar code base.

**Comment by rbt94** [comment]
Actually there is another project called pptxtpl that supports text fillings. Could someone of this wonderful community contribute for example by porting there InlineImage or table support? Thanks
