### ISSUE TITLE
New Page tag for docx-template

### ISSUE THREAD

**Issue by adilmalik393** [elapouya/python-docx-template#167]
Normally I use `r` for new line e.g. {{r "\n Hy there, I am being printed after new line"}}

I was wondering is there anything that we can use to add a page break ???

**Comment by carstenfjelkstrup** [comment]
To preserve line breaks wrap it in docxtpl.R():

`text_with_linebreak = docxtpl.R("\n Hy there, I am being printed after new line")`

**Comment by mx2048** [comment]
I would use conditions such as:
`{% if page_break %}Ctrl-Enter in Word template{% endif %}`
And your dictionary:
`contents = {'page_break': 'True'}`

**Comment by elapouya** [comment]
Page-break Feature now available in v0.5.15
