### ISSUE TITLE
ValueError: can only parse strings

### ISSUE THREAD

**Issue by gggdomi** [elapouya/python-docx-template#170]
I installed docxtpl on a clean machine today. I ran some code that used to work but couldn't generate any document.

The exact same exception is raised when running the basic usage code from the documentation.

```python
from docxtpl import DocxTemplate

doc = DocxTemplate("my_word_template.docx")
context = { 'company_name' : "World company" }
doc.render(context)
doc.save("generated_doc.docx")
```

Using Python 3.7.1

Traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-70cd50864075> in <module>
----> 1 doc.render(context)
      2 doc.save("generated_doc_.docx")

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docxtpl/__init__.py in render(self, context, jinja_env, autoescape)
    297         headers = self.build_headers_footers_xml(context, self.HEADER_URI,
    298                                                  jinja_env)
--> 299         for relKey, xml in headers:
    300             self.map_headers_footers_xml(relKey, xml)
    301 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docxtpl/__init__.py in build_headers_footers_xml(self, context, uri, jinja_env)
    245 
    246     def build_headers_footers_xml(self,context, uri,jinja_env=None):
--> 247         for relKey, xml in self.get_headers_footers_xml(uri):
    248             encoding = self.get_headers_footers_encoding(xml)
    249             xml = self.patch_xml(xml)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docxtpl/__init__.py in get_headers_footers_xml(self, uri)
    236         for relKey, val in self.docx._part._rels.items():
    237             if val.reltype == uri:
--> 238                 yield relKey, self.xml_to_string(parse_xml(val._target._blob))
    239 
    240     def get_headers_footers_encoding(self,xml):

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docx/opc/oxml.py in parse_xml(text)
     35     ``etree.fromstring()`` replacement that uses oxml parser
     36     """
---> 37     return etree.fromstring(text, oxml_parser)
     38 
     39 

src/lxml/etree.pyx in lxml.etree.fromstring()

src/lxml/parser.pxi in lxml.etree._parseMemoryDocument()

ValueError: can only parse strings
```

I tried to investigate, maybe it's related to this URI being unreachable, but I'm not sure at all   https://github.com/elapouya/python-docx-template/blob/2fad92046e580b6e9a212647f274d5efaae82648/docxtpl/__init__.py#L41

**Comment by jsve** [comment]
I get the same error. Haven't looked into it in any detail though.

Using python 3.6.4

**Comment by gggdomi** [comment]
Thanks ! I can confirm that installing `python-docx==0.8.7` worked for me too.

**Comment by anhphamduy** [comment]
Same problem. Only working on `python-docx==0.8.7`.

**Comment by kenichi-ogawa-1988** [comment]
Thanks @jsve ! I also faced this problem just from yesterday.
Downgrading to `python-docx==0.8.7` works for me, too.

Problem versions that I used:
```
docxtpl==0.5.15
lxml==4.3.0
python-docx==0.8.10
```

**Comment by elapouya** [comment]
It seems there are many changes into the latest python-docx : the author want to manage headers/footer and changed many internals. For exemple header xml code is not stored into @val._target._blob@
but into @val._target.blob@, I tried to fixed that, but after there is another problem : jinja2 rendered xml is not injectable back into the blob as it seems to be immutable.
As there is too much work to correct that with the latest python-docx, il will but a constraint on the version in docxtpl dependencies...

**Comment by CapAllen** [comment]
I change it to `docxtpl==0.5.9` and it worked! thx for you all.

**Comment by elapouya** [comment]
This not normal you have to downgrade docxtpl : could you give me your docx template ?

**Comment by SergeyZaykov** [comment]
Sorry for link: http://acc107_3.acc.tula.ru/only%20string.7z

**Comment by elapouya** [comment]
Strange, it works with me... (python 3.6)
Could you do a 'pip freeze' so I can see what is your python environment ?

Le ven. 15 mars 2019 à 11:28, SergeyZaykov <notifications@github.com> a
écrit :

**Comment by elapouya** [comment]
I was running docxtpl 0.5.17 : did you tried this version ?

**Comment by SergeyZaykov** [comment]
Python 3.7.2 (default, Feb  1 2019, 12:16:21)
[Clang 6.0.1 (tags/RELEASE_601/final 335540)] on freebsd12

**Comment by SergeyZaykov** [comment]
pip-3.7 freeze
acme==0.31.0
alabaster==0.7.6
asn1crypto==0.22.0
Babel==2.6.0
beautifulsoup4==4.6.0
certbot==0.31.0
certifi==2018.11.29
cffi==1.12.2
chardet==3.0.4
Click==7.0
ConfigArgParse==0.14.0
configobj==5.0.6
cryptography==2.3
Cython==0.29
Django==2.1.7
docutils==0.14
docxtpl==0.5.16
et-xmlfile==1.0.1
html5lib==1.0.1
idna==2.8
imagesize==0.7.1
jdcal==1.4
Jinja2==2.10
josepy==1.1.0
libxml2-python==2.9.8
lxml==4.3.1
MarkupSafe==1.1.1
meson==0.49.2
openpyxl==2.6.0
parsedatetime==2.4
Pillow==5.3.0
pip-tools==3.4.0
ply==3.11
psycopg2==2.7.7
pyasn1==0.4.5
pycparser==2.18
pycrypto==2.6.1
Pygments==2.3.0
pyOpenSSL==18.0.0
pyRFC3339==1.1
pysmi==0.3.3
pysnmp==4.4.9
PySocks==1.6.8
PyStemmer==1.3.0
pytesseract==0.2.6
pytest-runner==2.11.1
python-docx==0.8.10
pytils==0.3
pytz==2018.9
requests==2.21.0
requests-toolbelt==0.8.0
setuptools-scm==3.1.0
six==1.12.0
snowballstemmer==1.2.0
Sphinx==1.6.5
sphinx-rtd-theme==0.4.3
sphinxcontrib-websupport==1.1.0
sqlite3==0.0.0
Tkinter==0.0.0
urllib3==1.22
webencodings==0.5.1
xlrd==1.2.0
zope.component==4.2.2
zope.event==4.1.0
zope.interface==4.6.0

**Comment by SergeyZaykov** [comment]
Also I have Python 2.7.16 (default, Mar 13 2019, 12:30:31)
[GCC 4.2.1 Compatible FreeBSD Clang 6.0.1 (tags/RELEASE_601/final 335540)] on freebsd12

**Comment by SergeyZaykov** [comment]
I downgrade to python-docx==0.8.7 - problem are gone.

**Comment by SergeyZaykov** [comment]
How to get docxtpl 0.5.17?

**Comment by elapouya** [comment]
Since docxtpl 0.5.16, I put requirement for python-docx==0.8.7
So, for a fresh install of docxtpl, you will get the right python-docx
package and that should work.

Le ven. 15 mars 2019 à 12:54, SergeyZaykov <notifications@github.com> a
écrit :

**Comment by SergeyZaykov** [comment]
Well, docxtpl 0.5.17 work fine, but with python-docx 0.8.7, not python-docx 0.8.10.

**Comment by diegoyosiura** [comment]
Thanks @jsve, Working  on:
`
docxtpl==0.5.15
lxml==4.3.0
python-docx==0.8.7
`

In my case, I was able to follow the error to the file:
lib / python3.7 / site-packages / docx / opc / oxml.py: 37
`python
def parse_xml (text):
        return etree.fromstring (text, oxml_parser)
`
When it is reading the headers the following situation occurs:
text is None, and I believe that this is what should be generating the error.

**Comment by retsyo** [comment]
I met the same problem with latest (to be clear, on Dec 7th, 2019) cloned `python-docx` and `docxtpl`

**Comment by elapouya** [comment]
What version of python-docx do you have ?

**Comment by retsyo** [comment]
I am using latest cloned python-docx
```
>>> import docx
>>> docx.__version__
'0.8.10'
>>> import docxtpl
>>> docxtpl.__version__
'0.6.3'
```

So till now, the solution is to use python-docx 0.8.7?

**Comment by elapouya** [comment]
Yes, only 0.8.7 works. The author has made a lot internal changes in 0.8.10
which makes this version unusable with docxtpl

**Comment by elapouya** [comment]
The latest docxtpl now uses docx 0.8.10, please use it.
