### ISSUE TITLE
Merge Cells

### ISSUE THREAD

**Issue by carlsummer** [elapouya/python-docx-template#172]
context = {
    'col_labels' : ['fruit', 'vegetable', 'stone', 'stone'],
    'tbl_contents': [
        {'label': 'yellow', "a":'banana',"b":"bh1","c":"c1","d":'d1'},
        {'label': 'yellow', "a":'banana',"b":"bh2","c":"c2","d":'d2'},
        {'label': 'yellow', "a":'232432',"b":"bh3","c":"c3","d":'d3'},
        {'label': 'yellow22', "a":'23af',"b":"bh3","c":"c3","d":'d3'},
        {'label': 'yellow22', "a":'2234235',"b":"bh3","c":"c3","d":'d3'},
        ]
}

![image](https://user-images.githubusercontent.com/16281965/51229216-8776a800-1996-11e9-8cd6-294d938306d4.png)

![image](https://user-images.githubusercontent.com/16281965/51229230-90677980-1996-11e9-96e9-9f545424359f.png)

![image](https://user-images.githubusercontent.com/16281965/51229257-a70dd080-1996-11e9-8e64-fab1b97db664.png)

How should I write to achieve the same content merge?

**Comment by tehgringe** [comment]
I'm looking to achieve this. My column one effectively has a common set of values (3x High Medium and Low) but I dynamic set of rows within each group.

**Comment by llyzhizhe** [comment]
my template:
![image](https://user-images.githubusercontent.com/27886426/56465932-762cb400-643b-11e9-9e46-1c610ebc57a1.png)

the output:
![image](https://user-images.githubusercontent.com/27886426/56465939-847ad000-643b-11e9-837e-a6f1482fcb68.png)

**Comment by elapouya** [comment]
Dynamic vertical merging (based on cell content) is not supported in docxtpl

**Comment by tsy19900929** [comment]
https://github.com/tsy19900929/docxtpl_dynamic_vertical_merging
![test1](https://user-images.githubusercontent.com/24546045/199893232-ed0e41f6-5aaf-4a1e-93c0-406e1457d1b3.jpg)
