### ISSUE TITLE
Failed to replace pictures in body

### ISSUE THREAD

**Issue by L1ttleTomato** [elapouya/python-docx-template#173]
My English is not good，please forgive me.
I saw the Related Issues，but they are not helpful to my problem.
In the documentation,i saw that "The replacement occurs in headers, footers and the whole document’s body".However,when i put a image named 'test.png' into the tpl-docx(in body) and run the script,it raised the ValueError:Picture "test.png" not found in the docx template.Can you tell me is it possible to replace a picture in body?If so,could you tell me how to make a template correctly?Thank u very much.Look forward to your reply！
[test.docx](https://github.com/elapouya/python-docx-template/files/2765101/test.docx)

**Comment by elapouya** [comment]
Please give your python script.
To replace a picture, read the doc : 

```
Syntax to replace dummy_header_pic.jpg:

tpl.replace_pic('dummy_header_pic.jpg','header_pic_i_want.jpg')
```

Note that dummy_header_pic.jpg is the picture you inserted in the docx template : you must give it again in your python script so docxtpl will be able to find it in the docx template (MSWord rename it at save time)
Both 'dummy_header_pic.jpg' and 'header_pic_i_want.jpg' must exist on disk when calling replace_pic() method.
