### ISSUE TITLE
Doesn't docxtpl.render() method support keyword argument?

### ISSUE THREAD

**Issue by sulisu** [elapouya/python-docx-template#180]
Hi guys,

I have to use special character in jinja fields, such as '@' in filename like 'show_logging@10.0.0.253.txt'

I managed to make a script to loop the docx to find all fields, combine them with path and load this file into Listing object.

But when I tried to use the method provided by Martijn Pieters in this post [https://stackoverflow.com/questions/29344964/how-to-use-special-characters-in-template-variables-in-jinja2](url) , I got this error
```
  Original exception was:  
  Traceback (most recent call last):  
    File "./aj_docxsearch_test.py", line 53, in <module>  
      docxtpl_1.render(context1=context)  
  TypeError: render() got an unexpected keyword argument 'context1'  
```

Here is my code, and there is only one line in test_special_char_in_field_tpl.docx
“{{ context1['show_logging@10.0.0.253.txt'] }}”  (without quotes)

```
#!/usr/bin/env python3.6

## https://stackoverflow.com/questions/29344964/how-to-use-special-characters-in-template-variables-in-jinja2 @Martijn Pieters

import re
from docx import Document
from docxtpl import DocxTemplate, RichText, Listing

template_1 = "test_special_char_in_field_tpl.docx"
filepath='logfiles/'


regex1 = re.compile(r"{{.? (?:\w*\[')?([\w@.]+)(?:'])? }}")

textJinjaFields = []
docxtpl_1 = Document(template_1)
for p in docxtpl_1.paragraphs:
    if regex1.findall(p.text):
        textJinjaFields += (regex1.findall(p.text))

context = {}


for index, item in enumerate(textJinjaFields, start=0):   # Python indexes start at zero
    with open(filepath+item, 'r') as tempfile:
        text=tempfile.read()
    context[item] = Listing(text)

docxtpl_1 = DocxTemplate(template_1)
docxtpl_1.render(context1=context)
docxtpl_1.save("test_special_char_in_field_tpl_new.docx")

```

**Comment by sulisu** [comment]
I have tested the original example provided by Martijn Pieters in his answer. It works well.
Here is the code:

```
#!/usr/bin/env python3.6

import jinja2

values = {'pre_package_information[1]/comment': 'Device: 14.2',  'post_package_information[1]/comment': 'Device: 14.2-2'}
mssg= ("Test Succeeded!! Checking Device version for 14.2 release "+"{{values1['pre_package_information[1]/comment']}}")
x = jinja2.Template(mssg).render(values1=values)
print(x)

```

**Comment by elapouya** [comment]
Could you display the context you give to render() ?

**Comment by sulisu** [comment]
output of print(context)
`
{'show_logging@10.0.0.253.txt': <docxtpl.Listing object at 0xb632e6ec>}
`

**Comment by sulisu** [comment]
`docxtpl_1.render({'context1':context}) ` works.

I have tried this method in example code from [https://stackoverflow.com/questions/29344964/how-to-use-special-characters-in-template-variables-in-jinja2](url), it works in jinja too. Keyword argument is not necessary.

Thank you very much.

Maybe I should give this issue a more meaningful title, such as "how-to-use-special-characters-in-template-variables-in-docxtpl", but I can not edit the title.

**Comment by sulisu** [comment]
If someone else just want to do template text replace and don't need other function such as style manipulating. There is another python module [https://pypi.org/project/docx-mailmerge/](url) which using MSWord build-in mailmerge fields.

Since MSWord itself takes care of most details such as paragraphs  and tables, the python code for the same function is quit simple.

```
#!/usr/bin/env python3.6

from mailmerge import MailMerge

# Define the templates and output fileanme - assumes they are in the same directory as the code
template_in='test_special_char_in_field_tpl.docx'
template_out='test_special_char_in_field_tpl_new.docx'
filepath='testcase/'

# get mailmerge fields name form docx
testDoc=document_1.get_merge_fields()
textMergeFields=list(testDoc)

context = {}

for index, item in enumerate(textMergeFields, start=0):   # Python indexes start at zero
    with open(filepath+item, 'r') as tempfile:
        text=tempfile.read()
    context[item] = text

document_1.merge(**context)

document_1.write(template_out)
```
