### ISSUE TITLE
Can I create a variable number of tables?

### ISSUE THREAD

**Issue by nilanjenator** [elapouya/python-docx-template#184]
I need to create multiple documents.  Each document may have a different number of tables (of the same format).  Can I do that using python-docx-template?

**Comment by elapouya** [comment]
by using {% for ... %} {% endfor %} around the table in your template.

**Comment by nilanjenator** [comment]
I also need to create different anchors for each table?

Here is what I need:
Let's say I have customers who have different products.  I create tables for each product.

For Customer1, I need 4 products/tables.  For Customer2, I need 7 products/tables

I need a structure like this in the docx:

For number of products:
Anchor: t1.SKU

t1.SKU  t1.Cost   t1.Inventory

Anchor: t2.SKU

t2.SKU t2.Cost  t2.Inventory

Anchor: t3.SKU
.
.
and so on

**Comment by elapouya** [comment]
Anchors are not supported by docxtpl

**Comment by KRitter90** [comment]
Hi Eric & contributors, 
thanks for your amazing work, it helps me on a daily base to generate reports in a very efficient way!
Regarding the generation of a variable number of tables in a template using the for loop method, I tried to follow your suggestion, however I am not that used to the jinja2 world.

I created a small python script where I define a dictonary consisting of multiple table inputs in the form of:

dictMultiTab={'col_labels1': ['0'],
 'tbl_contents1': [{'label': '0', 'cols': ['0']},
  {'label': '1', 'cols': ['1']},
  {'label': '2', 'cols': ['2']},
  {'label': '3', 'cols': ['3']},
  {'label': '4', 'cols': ['4']}],
 'col_labels2': ['0'],
 'tbl_contents2': [{'label': '0', 'cols': ['0']},
  {'label': '1', 'cols': ['1']},
  {'label': '2', 'cols': ['2']},
  {'label': '3', 'cols': ['3']}],
 'col_labels3': ['0'],
 'tbl_contents3': [{'label': '0', 'cols': ['0']},
  {'label': '1', 'cols': ['1']},
  {'label': '2', 'cols': ['2']},
  {'label': '3', 'cols': ['3']},
  {'label': '4', 'cols': ['4']},
  {'label': '5', 'cols': ['5']},
  {'label': '6', 'cols': ['6']}]}

In the word template I would like to generate the variable number of tables N (in this case N=3) according to the number of tbl_contentsN, which is basically the number of dictonary keys divided by 2: N=dictMultiTab.keys()/2.

However, I did not succeed in setting up the correct word template so far using the for loop method - is there any chance you can upload an example for this puspose?

Best greetings and thanks for consideration.

**Comment by elapouya** [comment]
Your data is incorrect, use a list : it should be something like : 

```
dictMultiTab={'tables': [
{
'col_labels': ['somelabel'],
'tbl_contents': [{'label': '0', 'cols': ['0']},
{'label': '1', 'cols': ['1']},
{'label': '2', 'cols': ['2']},
{'label': '3', 'cols': ['3']},
{'label': '4', 'cols': ['4']}],
},{
'col_labels': ['someotherlable'],
'tbl_contents': [{'label': '0', 'cols': ['0']},
{'label': '1', 'cols': ['1']},
{'label': '2', 'cols': ['2']},
{'label': '3', 'cols': ['3']}],
},{
'col_labels': ['myfirstcolomn'],
'tbl_contents': [{'label': '0', 'cols': ['0']},
{'label': '1', 'cols': ['1']},
{'label': '2', 'cols': ['2']},
{'label': '3', 'cols': ['3']},
{'label': '4', 'cols': ['4']},
{'label': '5', 'cols': ['5']},
{'label': '6', 'cols': ['6']}]
}]}

```

Then in your docxtpl, just do : 

```
{% for table in tables %}

use table.col_labels and table.tbl_contents here to build one table : see examples in tests/

{% endfor %}
```

**Comment by abubelinha** [comment]
@elapouya 
Following your example for a simple table like this, would it be possible to call each row cell content by its column *name*? (instead using `for col in item.cols`, as you do in your dynamic_table_tpl.docx)

```Python
context = {
    'col_labels': ['fruit', 'vegetable', 'stone', 'thing'],
    'tbl_contents': [
        {'label': 'yellow', 'cols': ['banana', 'capsicum', 'pyrite', 'taxi']},
        {'label': 'red', 'cols': ['apple', 'tomato', 'cinnabar', 'doubledecker']},
        {'label': 'green', 'cols': ['guava', 'cucumber', 'aventurine', 'card']},
    ],
}
```

I an rendering paragraphs, not table rows. 
So I am trying to do something like this in my template:

```
{% for item in tbl_contents %}
An example of a {{ item.label }} coloured fruit would be a {{ item.cols.fruit }}. For vegetables, let's take {{ item.cols[1] }}. I will not talk about stones or other things.
{% endfor %}
```
Calling by index, `item.cols[1]` is working as expected (it returns a vegetable).
But calling by name (`item.cols.fruit` or `item.cols['fruit']`) does not work.
How can achive this?
Thanks
