### ISSUE TITLE
How to reduce memory usage？

### ISSUE THREAD

**Issue by Newester** [elapouya/python-docx-template#188]
I have a large list of data to render, it uses about 4GB memories while rendering. How can reduce the use of memory ?

**Comment by Newester** [comment]
maybe the tree generate from  xml is too big, is there any methods to  reduce the merory usage?

**Comment by elapouya** [comment]
A docx document is mainly a single xml file + media files, all zipped.
Big document implies big memory usage as the whole document must fit in memory as python objects.
This mainly comes from python-docx that is used by docxtpl.
There is not a lot of solutions except if you want to rewrite many years of code for both libraries
If you want to propose your code, I will be happy to study it.

**Comment by Newester** [comment]
Maybe not the samething. I use python-docx to add content into it, memory usage increases as O(log(n)), but too slow; your library is faster, but memery usage increases as O(n). But I don't know why.
