### ISSUE TITLE
bytes to DocxTemplate

### ISSUE THREAD

**Issue by Jekeam** [elapouya/python-docx-template#189]
Good afternoon, tell me how to do the same, but if I read the document from the database (bytes).
This is equivalent:

```
from docxtpl import DocxTemplate
open('my_word_template.docx', 'rb') as f:
  b = f.read()
doc = DocxTemplate(b)
context = { 'company_name' : "World company" }
doc.render(context)
doc.save("generated_doc.docx")
```

i get error: "bytes object has no attribute seek"

**Comment by elapouya** [comment]
Hi,

Specify the filename, not its content !
Please read the docs.

**Comment by Jekeam** [comment]
the fact is that I made an analogy, in fact I do not read the file from the disk, I read it from the Oracle database, blob

**Comment by Jekeam** [comment]
```
from docxtpl import DocxTemplate
import cx_Oracle

#
<...>
#
conn = cx_Oracle.connect(user=user, password=password, dsn=dsn)
#
cur = conn.cursor()
res = cur.execute("select docx_template from docx_templates where template_name = 'cib_fin_rq_test'")
tmp = res.fetchone()
tmp = tmp[0].read()
#
# print(tmp.decode('utf-8'))
doc = DocxTemplate(tmp) # .decode('utf-8')
context = { 'body' : 'World company' }
doc.render(context)
doc.save('generated_doc.docx')
```

**Comment by elapouya** [comment]
So the solution is to write a temporary file then give its name to docxtpl.
It is not possible to give a file-like object neither. May be I will work
on that later...

**Comment by Jekeam** [comment]
It worked for me, thanks!
