### ISSUE TITLE
ZeroDivisionError since v0.5.12

### ISSUE THREAD

**Issue by GliderGeek** [elapouya/python-docx-template#190]
I am encountering a problem with a template which worked fined when using v0.5.11. Below i have tried to make the simplest demonstrator possible

[template_zero_division.docx](https://github.com/elapouya/python-docx-template/files/3080231/template_zero_division.docx)

```python
doc = DocxTemplate("template_zero_division.docx")
context = {'results': [{'entry': 1}, {'entry':2}, {'entry': 3}]}
doc.render(context)
```

When i am on v0.5.12 or higher (only tried v0.5.17), this template fails with a ZeroDivisionError, from [this line](https://github.com/elapouya/python-docx-template/blob/master/docxtpl/__init__.py#L358).

This is added in v0.5.12 in [this commit](https://github.com/elapouya/python-docx-template/commit/8ffc7b80e815b5dcd0b49f595b6d04757909bfc8).

It would be great if you could look into this.

**Comment by elapouya** [comment]
What version of msword are you using for the template ?

Le lun. 15 avr. 2019 à 15:12, GliderGeek <notifications@github.com> a
écrit :

**Comment by GliderGeek** [comment]
i am using libreoffice 6.2 on (arch) linux

**Comment by elapouya** [comment]
Your docx does not seem good : on libreoffice/linux,  the table is splitted
in two pages...
Use tests/templates/order_tpl.docx to make some testing first.


Le lun. 15 avr. 2019 à 19:17, GliderGeek <notifications@github.com> a
écrit :

**Comment by GliderGeek** [comment]
The table is split on purpose. This way, each new entry in the list starts
on a new page (at least it does so in v0.5.11).

**Comment by elapouya** [comment]
Could you try without the split to it comes from the split or something
else.

Le mar. 16 avr. 2019 à 10:57, GliderGeek <notifications@github.com> a
écrit :

**Comment by elapouya** [comment]
closing as no answer
