### ISSUE TITLE
vertical merge problem

### ISSUE THREAD

**Issue by llyzhizhe** [elapouya/python-docx-template#192]
my template:
![image](https://user-images.githubusercontent.com/27886426/56465895-d53df900-643a-11e9-8942-06024cc6da4a.png)
 
my code:
`from docxtpl import DocxTemplate

tpl=DocxTemplate('dynamic_table_test_tpl.docx')

context = {
	'items':[
		{	
			'gene':'CYP2D6',
			'level':'3',
			'detail':[
				{
					'rsid':'*3/rs35742686',
					'geno':'TT',
				},
				{
					'rsid':'*4/rs3892097',
					'geno':'CC',
				}
			]
		},

		{
			'gene':'ADRB1',
			'level':'2A',
			'detail':[
			{
				'rsid':'rs1801253',
				'geno':'CC',
			}
				
			]
		}
	],
	'suggest':'warning',
	
}

tpl.render(context)
tpl.save('vertical_merge_test.docx')`

my result:
![image](https://user-images.githubusercontent.com/27886426/56465901-f3a3f480-643a-11e9-8ce2-c632a129b058.png)

my desired output:
![image](https://user-images.githubusercontent.com/27886426/56465909-1df5b200-643b-11e9-8db8-17972a97c42d.png)

what I can do to achieve this?

**Comment by labsolution** [comment]
I have a similar problem.

Template:
![image](https://user-images.githubusercontent.com/28300445/56649087-c34f9680-6684-11e9-9cf8-bf284ac41b4c.png)

Data:
```
            'pap_group_list': [
                ('III-p', [
                    {'entry_nbr': '19-021043'},
                    {'entry_nbr': '19-026285'},
                ]),
            ],
```

The variable pap_group contains the right value, but it is missing in the output:
![image](https://user-images.githubusercontent.com/28300445/56649177-f134db00-6684-11e9-89a4-acbefe7cd2ba.png)

**Comment by llyzhizhe** [comment]
you can try this:
![image](https://user-images.githubusercontent.com/27886426/56651333-63281700-66bb-11e9-8593-5437a366cc34.png)

my result:
![image](https://user-images.githubusercontent.com/27886426/56651351-6d4a1580-66bb-11e9-9400-0b28cedf3ccc.png)

**Comment by labsolution** [comment]
@llyzhizhe: Works like a charm. Thanks. Sorry for using your Issue for my problem.
But I understand your issue. Thats quite tricky. You want to have a vertical merge on level x and not only the current level. I don't know how you could fix that...

I would say we all should donate @elapouya for his awesome library!

**Comment by elapouya** [comment]
Cell merging is limited in docxtpl, unfortunately, I won't fix this issue as it is too much time consuming.

**Comment by chaconcha** [comment]
Has anyone figured out a way of to do this?

**Comment by tsy19900929** [comment]
https://github.com/tsy19900929/docxtpl_dynamic_vertical_merging
![test1](https://user-images.githubusercontent.com/24546045/199892843-07414076-eaaf-49b0-8c9a-e075d58ad51b.jpg)
