### ISSUE TITLE
Unable to use hyperlinks properly.

### ISSUE THREAD

**Issue by pauldamian** [elapouya/python-docx-template#193]
Hello,

I saw the documentation on how to create hyperlinks in RichText and I tried following it, but the generated documents are corrupted and the hyperlink does not show up.

My use case:
I have a DocumentTemplate.docx file which, at some point, lists the terms of using a particular service:

```
{%p for term in standard_terms %}
{{r term }}
{%p endfor %}
```

I also have a python script that manipulates the data that does in the document.
Most terms are simple text, but there are some that refer online documents:

`The customer acknowledges the associated terms and conditions from: **external_doc**. The customer is advised to print and keep these documents....`

I use the following code to manipulate the input data:
```python
rt = RichText(term)
# I use documents to check where I have to add the external doc ref
if "{documents}" in term:
    # remove the documents text
    rt.xml = rt.xml.replace("{documents}", "")
    dt = DocxTemplate(TEMPLATE_FILE_PATH)
   # documents is a list of external docs
    for doc in documents:
        rt.add(doc , url_id=dt.build_url_id(DOCUMENTS_URL+doc ))

standard_terms.append(rt)
```

At a later stage, I generate the report like this:
```python
    doc = DocxTemplate(TEMPLATE_FILE_PATH)
    print("Generating the report {}".format(report_name))
    doc.render(input_data, j2_env)
    doc.save(report_name)
```

Am I doing it wrong?
I'm using the latest version of docxtpl(0.5.17), python 3.6 and Word 2016.

Thanks.

**Comment by elapouya** [comment]
Hello,

I am sorry, but I do not have Word2016 to test with.

In order to debug, could you display `rt.xml` after all links has been added, and display the content of `documents` list ?

**Comment by pauldamian** [comment]
Thanks for the quick reply. Below you can see my data

```python
DOCUMENTS_URL = "http://www.mydomain.com/legal-information/contracts/"
documents = ["equipment"]
```

Value of `rt.xml` is 

```xml
<w:r><w:t xml:space="preserve">Le signataire de la présente offre commerciale reconnait avoir pris connaissance et avoir approuvé sans réserve l’ensemble des documents contractuels associés: </w:t><w:br/><w:t xml:space="preserve"></w:t></w:r><w:hyperlink r:id="rId13" w:tgtFrame="_blank"><w:r><w:t xml:space="preserve">equipment</w:t></w:r></w:hyperlink>
```

**Comment by elapouya** [comment]
It should work, may be Word2016 is awaiting a special xml link format.

1. could you send me a minimal generated word document where the link should appear but does not appear.
2. Could you send me the same document but created MANUALLY and where the link works.

I will debug and check the differences

**Comment by pauldamian** [comment]
Here are the attached documents.
[Auto-generated example.docx](https://github.com/elapouya/python-docx-template/files/3112015/Auto-generated.example.docx)
[manual example.docx](https://github.com/elapouya/python-docx-template/files/3112016/manual.example.docx)

**Comment by elapouya** [comment]
That's very strange : in generated docx, the link is coded in xml like this : 

`<w:hyperlink w:tgtFrame="_blank">`

despite you told me that `rt.xml = ... <w:hyperlink r:id="rId13" w:tgtFrame="_blank"> ...`

The link id has disappeared ! it is not defined in relation file too !

Could you give me the complete python code and the docx template you used ?

**Comment by elapouya** [comment]
closing as no answer. Nevertheless, the latest docxtpl version should fix links issues
