### ISSUE TITLE
Add file like object support for replace_media

### ISSUE THREAD

**Issue by edufresne** [elapouya/python-docx-template#197]
I am trying to replace a header and footer image but because of file-system constraints all of my objects are file like objects (io.BytesIO objects) and not actually on disk. 

```python
import io
from docxtpl import DocxTemplate

file_obj = io.BytesIO(input_stream)
t = DocxTemplate(file_obj)
other_file_obj = io.BytesIO(other_input_stream)
t.replace_media('image.png', other_file_obj)
```

This obviously throws:
```
TypeError: coercing to Unicode: need string or buffer, _io.BytesIO found
```

Simply the ability to pass a byte or string io object just like how it's done in the Template __init__ method would be great.

**Comment by elapouya** [comment]
Thanks for the update : will be available in v0.5.19
