### ISSUE TITLE
Jinja2 custom filters

### ISSUE THREAD

**Issue by vasa-chi** [elapouya/python-docx-template#20]
Is there any way to use custom filters whithin templates?
Passing functions within context works, but maybe I'm missing something?

**Comment by elapouya** [comment]
I just added a new argument in render() : you can add a jinja environment : custom filters can be defined this way : have a look at the documentation I modified.

Could you confirm me it works as expected ?

**Comment by vasa-chi** [comment]
Yep, seems to be working. Thanks!
