### ISSUE TITLE
how can i add page number in the footer ?

### ISSUE THREAD

**Issue by wellmonwu** [elapouya/python-docx-template#202]
how can i add page number in the footer?

**Comment by elapouya** [comment]
not with docxtpl : the page number has to be create in the template.

**Comment by wellmonwu** [comment]
which one docxtpl i can refer to ?

**Comment by wellmonwu** [comment]
which template i can refer to ?

**Comment by elapouya** [comment]
The template you create yourself with ms word : create a footer with a page number (not a real number, but a ms word page number object)

**Comment by wellmonwu** [comment]
that is it! thks!
 
------------------
 Best Regards,   Weiming Wu (伍伟明) 
      School of Software, 
Sun Yat-sen University (Zhongshan University)
 

 

 




------------------ 原始邮件 ------------------
发件人: "Eric Lapouyade"<notifications@github.com>; 
发送时间: 2019年6月5日(星期三) 下午3:09
收件人: "elapouya/python-docx-template"<python-docx-template@noreply.github.com>; 
抄送: "伍伟明"<wellmon_wu@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [elapouya/python-docx-template] how can i add page number in thefooter ? (#202)




The template you create yourself with ms word : create a footer with a page number (not a real number, but a ms word page number object)
