### ISSUE TITLE
Multi Context

### ISSUE THREAD

**Issue by overflowsecurity** [elapouya/python-docx-template#21]
Howdy,

I have been playing with this for a couple days, and I am liking it so far. Here is my issue.

Simply put I have a word doc and at the top of my python code I have something like this:

`Context = {
          report_name : "Name XYZ",
          report_date : "1/2/2222" }`

then later in my code using some data from some sql queries I need to have some more data put into the template so I try:

'context = { 'data' : row[1] }'
then if I do:
'doc.render(context)' and save it only one of my contexts works because I am over writing the first context variable.  I have also tried to do context1 and context2 but when I render context1 and then context2 I still do not get my data in my output file.  Any ideas on how I could accomplish this?

*Note that any of these above context statements do work on their own so I know my template variables are working as expected.*

**Comment by elapouya** [comment]
just update your context instead of overwriting it :
```

context={ some data }
...
context.update({ some other data })
...
doc.render(context)
```
