### ISSUE TITLE
Feature request: python-xlsx-template

### ISSUE THREAD

**Issue by retsyo** [elapouya/python-docx-template#211]
ok, maybe it is not a feature request. 

I have searched, but only find a `.Net` implementation [ExcelReport](https://github.com/hanzhaoxin/ExcelReport) who acts like python-docx-template, but works on `XLS` and `XLSX` file. The page is in Chinese, but the pictures say what it is clearly

Then I found [use jinjia2 with excel](https://qiita.com/kokumura/items/18e55ac364193ab42c74) which is in Japanese. However, it does not fill items rows by rows, instead, it fill all items with ENTER separator.

So can python-docx-template be used for xls/xlsx files? Or is there any opensource, python modules who has a nice peer usable level as python-docx-template supplies?

Thanks

**Comment by elapouya** [comment]
python-docx-template uses python-docx which works only with docx.

**Comment by karolzlot** [comment]
https://github.com/zhangyu836/xltpl/blob/master/README_EN.md
