### ISSUE TITLE
Question: Is it possible to embed raw RichText directly into the template?

### ISSUE THREAD

**Issue by abdelrahman-t** [elapouya/python-docx-template#212]
Is it possible to inject RichText directly into the template? In my use case user is allowed to insert  RichText produced by some browser-based text editor that we are integrating with, I see that the "RichText" class can be used to insert RichText into the template, but in our use case we don't have access to the original text but we just have the resulting raw RichText.

Thanks, 

p.s This package is awesome :smile:

**Comment by elapouya** [comment]
This is not possible directly : These is no docxtpl.RichText(html=someting) : you have to decode the html the user generated and create the richtext object your self.
