### ISSUE TITLE
is there a way to add  not constant number subdocs?

### ISSUE THREAD

**Issue by wentgithub** [elapouya/python-docx-template#216]
in my word, it needs to judge whether to add subdoc, and the number of subdocs is not constant, 

I found one subdoc in your test 
{{p mysubdoc}}
but I need to decide to add how many subdocs? and this does not satisfy me.

thanks a lot

**Comment by wentgithub** [comment]
to be more clear, let me add some other things.
there are a lot of content in my subdoc, so it is not easy to generate that through code, but there is one variable in all of the subdoc that I need to replace, how  should I do, 
thanks a lot.

**Comment by wentgithub** [comment]
I saw one people ever ask something about keep origin subdoc styple. I also meet this question

# -*- coding: utf-8 -*-
'''
Created : 2015-03-12

@author: Eric Lapouyade
'''

from docxtpl import DocxTemplate, RichText
from docx.shared import Inches
import os

os.chdir('/Volumes/UDISK/docx_python/python-docx-template-master/tests/')
tpl=DocxTemplate('templates/subdoc_tpl.docx')

sd = tpl.new_subdoc()
p = sd.add_paragraph('This is a sub-document inserted into a bigger one')
p = sd.add_paragraph('It has been ')
p.add_run('dynamically').style = 'dynamic'
p.add_run(' generated with python by using ')
p.add_run('python-docx').italic = True
p.add_run(' library')
tpl_1=DocxTemplate('/Volumes/UDISK/thyroid/THYRO/abc_tpl.docx')
context1 = {'mutant_exon': RichText('MSH6基因exon4第2300位碱基C置换为G使得第767位氨基酸由苏氨酸转变成了丝氨酸')}
tpl_1.render(context1)
tpl_1.save('/Volumes/UDISK/thyroid/THYRO/THYRO_CDC73_tpl_1.docx')
sd1 = tpl.new_subdoc('/Volumes/UDISK/thyroid/THYRO/THYRO_CDC73_tpl_1.docx')
context = {
    'tpl1' : sd,
    'tpl2' : sd1,
}
tpl.render(context)
tpl.save('./subdoc.docx')

the new subdoc is ok.

![image](https://user-images.githubusercontent.com/48668142/61603420-0b745a00-ac70-11e9-9274-26c559b154d5.png)
<br>
but when it insert the new doc, the styple changed, can you help me,thanks a lot
<br>
![image](https://user-images.githubusercontent.com/48668142/61603470-41b1d980-ac70-11e9-8e86-e5774d2eb328.png)

thanks a lot

**Comment by wentgithub** [comment]
the font in the table changed, but the paragraph stayed the same

**Comment by elapouya** [comment]
Subdocs inherit styles from the main document and lose its own styles. So if you want to keep styles in subdocs, define them in the main document.

**Comment by wentgithub** [comment]
but the formation of subdoc is complex, so I want to use newsubdoc..

so how can I define them in main document, can you give me some examples.

mutant_exon is the string that need to be replaced in subdoc, after replacing, I add the new subdoc, can I just modify the following code in somewhere to keeo the style? thanks a lot

from docxtpl import DocxTemplate, RichText
from docx.shared import Inches
import os

os.chdir('/Volumes/UDISK/docx_python/python-docx-template-master/tests/')
tpl=DocxTemplate('templates/subdoc_tpl.docx')

sd = tpl.new_subdoc()
p = sd.add_paragraph('This is a sub-document inserted into a bigger one')
p = sd.add_paragraph('It has been ')
p.add_run('dynamically').style = 'dynamic'
p.add_run(' generated with python by using ')
p.add_run('python-docx').italic = True
p.add_run(' library')
tpl_1=DocxTemplate('/Volumes/UDISK/thyroid/THYRO/abc_tpl.docx')
context1 = {'mutant_exon': RichText('MSH6基因exon4第2300位碱基C置换为G使得第767位氨基酸由苏氨酸转变成了丝氨酸')}
tpl_1.render(context1)
tpl_1.save('/Volumes/UDISK/thyroid/THYRO/THYRO_CDC73_tpl_1.docx')
sd1 = tpl.new_subdoc('/Volumes/UDISK/thyroid/THYRO/THYRO_CDC73_tpl_1.docx')
context = {
'tpl1' : sd,
'tpl2' : sd1,
}
tpl.render(context)
tpl.save('./subdoc.docx')

the new subdoc is ok.
