### ISSUE TITLE
add caption to an image 

### ISSUE THREAD

**Issue by sadalsuud** [elapouya/python-docx-template#217]
How I do add a caption or legend to an image, I have this 
`image': InlineImage(tpl, str(imagen), height=Mm(80)),`
and in my template I have 

```
{% for graphic in a_station %}
{{ graphic.image }}
{% endfor%} 
```

But I have a doubt, How do I this ... Any idea or comment ? .. Thanks

**Comment by elapouya** [comment]
There is no caption/legend support for InlineImage. But you could include your image in a table with invisible borders, first row would be your image and the 2nd row your legend. Then you loop on the table.
