### ISSUE TITLE
Document corrupt when using images inside textboxes. 

### ISSUE THREAD

**Issue by JesusCN** [elapouya/python-docx-template#219]
Hello, 

I am trying to generate a document using a template that has several images inside textboxes (because I need images in different locations). I am able to generate de document but when I try to open , an error message that says something like "word encountered content that can be reade. ¿ do you want to fix it ? if you trust the document source,  click yes " (is in spanish). 

After clicking yes, the document the document appears to be correct, but error messages is very annoying to users. 

Only happens with images in textboxes. I'm using Word for Mac 16.

Any ideas what could i be doing wrong ? 

Code:
<img width="730" alt="Captura de Pantalla 2019-08-03 a la(s) 11 24 30" src="https://user-images.githubusercontent.com/6798109/62414468-63508080-b5e1-11e9-8070-69d9feb1d302.png">

Template:
<img width="947" alt="Captura de Pantalla 2019-08-03 a la(s) 11 25 59" src="https://user-images.githubusercontent.com/6798109/62414470-7f542200-b5e1-11e9-979a-e1c706346d3e.png">

Thanks in advance !!

**Comment by elapouya** [comment]
Could you try the latest docxtpl version and the workaround proposed in #243 ?
