### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError: unexpected char u'&'

### ISSUE THREAD

**Issue by siyuancn** [elapouya/python-docx-template#22]
I have jinjia2 syntax like: {% if len > 0  %} in the template.

I got the error message: jinja2.exceptions.TemplateSyntaxError: unexpected char u'&' when I tried to convert the docx from template.

I try to change the '>' to 'gt', but it doesn't work. Does any one know the solution?

**Comment by elapouya** [comment]
Sounds like a bug : I will try to reproduce...

**Comment by elapouya** [comment]
meanwhile, you can use {% if len %} it should work.

**Comment by elapouya** [comment]
I fixed the code, could you test it and give me a feedback ?

**Comment by siyuancn** [comment]
@elapouya thanks for your work.

I tested the code and no problem with ">"

**Comment by yehiaelza** [comment]
I have this code. 


# Create flask app
app = Flask(__name__)

# Load the Pickle model

model = pickle.load(open("model.pkl", "rb"))


@app.route("/")
def Home():
    return render_template("index.html")


@app.route("/predict", methods=["POST"])
def predict():
    float_features = [float(x) for x in request.form.values()]
    features = [np.array(float_features)]
    prediction = model.predict(features)

    return render_template("index.html", prediction_text = "The species of flower is {}".format(prediction))


if __name__== "__main__":
    app.run(debug=True)



but I found an error 

jinja2.exceptions.TemplateSyntaxError: unexpected char '&' at 137893
