### ISSUE TITLE
replace_embedded does not work with Excel files

### ISSUE THREAD

**Issue by Soldann** [elapouya/python-docx-template#221]
I'm trying to use docxtpl to replace embedded dummy Excel files using the replace_embedded method. Naturally since I'm writing this, it doesn't work the same way as it does with .docx files.

After some digging, it appears that Word changes the CRC of Excel files when they are embedded, which means the method does not find the files within the document. I verified this by manually creating a file with the right CRC - the replacement then works as expected.

Do you know some way around this? Maybe there is some way to calculate what the new CRC will be? If that's not possible, some way to manually type the CRC into the method would be helpful.

Thanks for making this wonderful module by the way.

**Comment by zillionlee** [comment]
I meet the same question.

**Comment by juanmacarrillo** [comment]
It also happens with other files, such as .pdf and .py.

I can't confirm the source of the issue it's the CRC though.

**Comment by elapouya** [comment]
I just added the method replace_zipname() in v0.7.0 : you can now replace Excel and PowerPoint files.
... But not PDF or .py file as they are encoded as OLE Object.bin files.

**Comment by lxj361** [comment]
> I just added the method replace_zipname() in v0.7.0 : you can now replace Excel and PowerPoint files.
> ... But not PDF or .py file as they are encoded as OLE Object.bin files.

so ,there'r noway to replace the PDF or .py or .txt file?
