### ISSUE TITLE
Unable to Include both Ampersand (&) and Newline Characters (\n) in Templates (can only do one or the other)

### ISSUE THREAD

**Issue by fstephane** [elapouya/python-docx-template#222]
Hello,

I've been struggling with this issue for a few months now with no luck. Every time I think I've found a solution, there's an edge case that throws a wrench in it. I'd greatly appreciate any help!

The problem is that I can't find a way to accommodate both "&" and newline characters at the same time in my templates.

If I set `autoescape=True`, "&" characters merge fine in inserted variables as well as in the content of the document. But any newline characters in variables are replaced with empty spaces. I've tried replacing newlines with the XML equivalent (<w: br / >) in my `finalize` function. I've also tried to insert paragraph tags, etc. However, those are all XML solutions, which are escaped by the `autoescape` option. I tried replacing "\n" with literal newlines, but I think that essentially replaces "\n" with "\n"

If I set `autoescape=False`, I can replace "&" and newlines with their XML equivalents using my `finalize` function, and that works great! However, "&" characters in the static content of the templates are then replaced with "& amp;" (instead of being properly escaped). I can prevent ampersands in the content from being replaced in this way, but then they're stripped out completely instead of appearing normally. This is definitely the closest solution to what I'm after, the only problem is that "&" are not being properly inserted in the static content of the templates.

I've scoured the issues on this repo but none of the relevant issues seem to address my specific problem.

I'm using the library in a large-scale application with many templates and a big range of possible inputs. As such, I don't think any use of the RichText solution would be scalable (as far as I understand - I don't have much experience using RichText tools).

Please if anyone can point me in the right direction I would be incredibly grateful!

**Comment by elapouya** [comment]
Why do you need newlines ? for listings ?

**Comment by fstephane** [comment]
Many of the variables I'm inserting contain newlines - eg. address blocks

**Comment by elapouya** [comment]
Please,

Use Listing('your string with \n and &')

See documentation.

**Comment by fstephane** [comment]
Thanks so much for the quick responses!

Unfortunately the Listing solution won't scale for me. I'm often passing complex objects into the context. This solution would require me to identify fields in those objects that may contains newlines and pass them all in separately with the Listing() method.

Normally I do something like this:
```
context = {
    'corporation': corporation
}
```
The corporation object could have any number of attributes, all of which could potentially include newline characters. Using the Listing method would require me to break these all out:
```
context = {
    'corp_address': Listing(corporation.mailing_address),
    'corp_description': Listing(corporation.description),
    'corp_name': Listing(corporation.name),
    and so on...
}
```
The overhead of making such a change would be massive.

At this point, the only solution I can think of is to do the autoescaping myself using my `finalize` method - and then run through the content of all assembled documents using the python-docx library to replace any "& amp;" in the static template content that were not properly escaped with "&". However, this could introduce new bugs and will slow down the document assembly quite a bit - which is not ideal when the application users are trying to assemble 20+ complex documents at a time.

The only other solution I can think of is to dig into the source code but I would be way out of my depth there.

Again, thanks so much for the quick response and please let me know if you can think of anything that will point me in the right direction

**Comment by elapouya** [comment]
The autoescaping used in docxtpl comes from jinja2, so if you want to patch something it is there.

why not doing (python 3) :

escaped_context =  { k:(Listing(v) if isintance(v,str) else v) for k,v in context.items }

**Comment by fstephane** [comment]
Unfortunately I think I would run into scalability issues here as well. 

Your solution would handle one level of attributes on the object, but my application would need to be able to handle an arbitrary number of levels in an object hierarchy. I'm sure this would be possible to accomplish by having a method dedicated to parsing the objects in the list and building the context structure using a more complex version of your solution. But this processing would slow down the document assembly speed.

Another issue is that many of the objects passed in are SQLAlchemy database objects with dynamic properties. These properties make additional database calls when they are accessed. If I were to run through all these properties in each object, it would force those database calls and cause more speed issues.

I wonder if it would be easier to tackle this from the custom auto-escaping angle. If I set `autoescape=False` and do the escaping myself using my `finalize` Jinja function, the only issue is that ampersands in the static content of the document are not properly escaped. Please excuse my ignorance, but do you know why the "&" characters within my context variables are properly escaped using this method, but "&" characters in the static template content still appear as "& amp;"? If I alter my finalize function to skip "&" characters in the static content, they are simply stripped out of the document.

Sorry for the difficult requests - despite this issue, this is an incredible library and I very much appreciate your responses and input!

**Comment by elapouya** [comment]
I do not know how the jinja2 'finalize' function is called. According to the documentation, it should be at variable expansion. My guess, there is some other processing after.

The best way in your case would be to redefine the jinja2 escape().
I saw jinja2 source code, it imports escape function from the library 'makeupsafe'.
May be, the solution is to do something like this just before docxtpl rendering :

import jinja2.utils
jinja2.utils.escape = something like your finalize function

I do not have tested at all, be I think this is the track to follow...

**Comment by fstephane** [comment]
Thank you for the suggestion and for giving me a new direction to explore! I will look into the jinja2 escape function
