### ISSUE TITLE
Using Inline images inside tables

### ISSUE THREAD

**Issue by chenmic** [elapouya/python-docx-template#225]
Hi,

I'm working on a project that creates tables in a word document to show data.
In order to make the pages more alive, I need to replace some of the text in the tables with images.

When I do that (using InlineImage), I get an error stating "word found unreadable content" in my word file.
The weird thing is that when I choose to let word "recover" the file for me, is it perfect, all data is there including the images!

I must stress that I managed to create a file with those images in the tables **without** getting the error but in almost all cases, I do get it.

I tried to compare the document.xml file between the "un-recovered" file and the recovered one but had no luck.

Does anyone know why it does that and preferably how to fix it?
I'll be happy to send any more information if required!

Thank you very much,
Chen.

**Comment by elapouya** [comment]
what msword version are you using ?

**Comment by chenmic** [comment]
Microsoft Word for Office 365 MSO (16.0.11328.20362) 64-bit

**Comment by elapouya** [comment]
docxtpl has been developped for MSWord 1997, I know newer version are more
sensible to generated XML.
Unfortunately, I do not own Office 365, so I cannot investiguate.

**Comment by chenmic** [comment]
I have tested it today on MSWord 2016 and it acted exactly the same.

I should also point out that the problem happens all the time with a lot of images but only sometimes with a small amount of images.
I thought it was caused by memory and/or size issues but I couldn't verify that.

**Comment by chenmic** [comment]
Hi,
3 weeks have passed and I'm still struggling with this issue.
Has anyone suffered the same thing? Or can possibly suggest a fix or a test to get past that issue?

Thanks.

**Comment by alipar3** [comment]
I've just encountered the same issue. Also happens for a fixed image in a table within the template that is iterated (to get the same table configuration for multiple components).
