### ISSUE TITLE
Combine multiple docx files created from same template

### ISSUE THREAD

**Issue by groverab** [elapouya/python-docx-template#229]
Hello,

I am wondering if anyone has any guidance on how to combine/merge multiple docx files (all created from the same template). I was trying to model the below code that I came across while searching this topic:
doc = DocxTemplate("template.docx")

pages = []
for idx, data in enumerate(dataset):
	page_doc = DocxTemplate("page_template.docx")

    page_doc.render(context=data)

    sd = doc.new_subdoc()
    sd.subdocx = page_doc.docx

    pages.append(sd)

context = {"pages": pages}
doc.render(context)

doc.save("final.docx")

However, the generated docx is overlaying the contents, instead of creating separate pages, with page breaks. Any guidance would be greatly appreciated!

Thanks so much!

**Comment by elapouya** [comment]
docx merging with docxtpl is not supported. Note that use of subdocs is very limited and can leads to attachement/images and style issues.
