### ISSUE TITLE
Insert SubDoc Without Line Break

### ISSUE THREAD

**Issue by fstephane** [elapouya/python-docx-template#231]
Hello,

I'm running into an issue where I'm unable to insert a sub-document without having an extra carriage return after the insert. If I want to place text directly below the insert, there is always an extra line break between the two.

eg.

{{ inserted subdoc }}< lb >
< lb >
< content that comes after the subdoc >

I'm wondering if there is a clever way to strip the extra line that comes after the insert, similar to the `{%p if %}` and `{%p for %}` solutions

Also, if I have subdoc at the end of a document, it adds the extra carriage return and can sometimes cause an extra blank page at the end of the assembled document because the extra line causes the content to spill into another page. Or if the subdoc is in the header/footer of the document, it creates an unnecessary space at the bottom of the header/footer

**Comment by elapouya** [comment]
Did you try {{p ... }} ?

**Comment by fstephane** [comment]
I didn't know you could do that! Can't believe I didn't think to try it

Thanks so much!
