### ISSUE TITLE
For loop to generate table issue

### ISSUE THREAD

**Issue by zwkin** [elapouya/python-docx-template#234]
Hi,
I have a problem to generate a table, as follows:
Here is the template in my use case.
![image](https://user-images.githubusercontent.com/8761561/68000624-d5496c00-fc9b-11e9-84de-1675df8fc520.png)

And this is the generated result
![image](https://user-images.githubusercontent.com/8761561/68000714-1d688e80-fc9c-11e9-9454-555ca22f8943.png)

The {%tr%} works fine but {%tc %} produced a result not expected .
What I want is as below:
![image](https://user-images.githubusercontent.com/8761561/68000850-a7185c00-fc9c-11e9-84c4-ed95e1b63dba.png)

Any suggestion?

Thanks.

**Comment by elapouya** [comment]
closing as no suggestions
