### ISSUE TITLE
Using the "p" Tag in a "set" Command

### ISSUE THREAD

**Issue by fstephane** [elapouya/python-docx-template#238]
Hello,

Love this library!

I have a question/minor request:

Sometimes I use the {% set %} command in a template to dynamically set a variable in-line. However, this always results in an extra carriage return. I've tried using the "p" prefix to strip out the return, but this is not recognized. (eg. `{%p set [var] = [value] %}` )

I've always found some other way to handle these particular scenarios in the backend without relying on {% set %} in the document, but I was thinking it would be a great addition to be able to use the "p" prefix in set commands!

**Comment by elapouya** [comment]
{%p ... %} should remove the entire paragraph where it is located, may be there is a problem because your paragraph is empty : could you try to add some dummy caracters after like this : 
{%p set [var] = [value] %}xxx

**Comment by elapouya** [comment]
closing as no feedback
