### ISSUE TITLE
Question: Can not replace image with replace_pic function

### ISSUE THREAD

**Issue by bluewingtan** [elapouya/python-docx-template#242]
Firstly, thanks for your excellent work of this project.

## Environment
- OS: Windows 10 1909 (18363.535)
- Python: 3.7.5
    - docxtpl: 0.6.3
    - python-docx: 0.8.7
    - jinja2: 2.10.3
    - six: 1.13.0
    - lxml: 4.4.2
- Office: Office 365 1911 (12228.20364)

## What
Can not replace image with replace_pic function

## How
I insert a image into document's `body` and I know the image will be renamed by `word processor`. So I reformed the `template` suffix name from `.docx` to `.zip` and observed the image in path `\word\media` with name `image1.png`.  When I run
```python
from docxtpl import DocxTemplate
doc = DocxTemplate('template.docx')
doc.replace_pic('image1.png', 'some_img.png')
doc.save('generated.docx')
```
a `ValueError` occurred: `Picture "image1.png" not found in the docx template`

## Why (Analysis)
When I read the source code, I find
https://github.com/elapouya/python-docx-template/blob/4fe1cc507d23cca68a8d78208dcb803a312578ec/docxtpl/__init__.py#L530
and the `docx.oxml.ns.nsmap['pic']` goes [that](https://github.com/python-openxml/python-docx/blob/da75fcf01f7f322e846e2ac3e1936aedd766acc8/docx/oxml/ns.py#L19)
```python
'pic': ('http://schemas.openxmlformats.org/drawingml/2006/picture')
```
When analyzing `document.xml.rels` in `\word\_rels` path, I find the `namespace` of `png` format is `http://schemas.openxmlformats.org/officeDocument/2006/relationships/image`, which is not represented in `docx.oxml.ns.nsmap`.

Maybe this is the problem?

**Comment by elapouya** [comment]
Hello, could you provide images files and docx template ?

Could you try replace_media() : it works another way : it will manipulate
zip file directly by finding dummy image checksum. You must give the path
to the dummy file which must exist during the process (to calculate its
checksum).

**Comment by bluewingtan** [comment]
Thanks for your reply. I have tested template file and image file in other platform, this problem still here, so I think it is unlikely that this is a problem for the document itself.

In `post_processing()` do the actual replacement
https://github.com/elapouya/python-docx-template/blob/4fe1cc507d23cca68a8d78208dcb803a312578ec/docxtpl/__init__.py#L473-L484
and the `replace_media()` work properly.

BTW, could you please refactor the `replace_pic()` to support `png` format? Or extend  the `replace_media()` to support replace media by file name?

Maybe I could submit a P/R if needed🤣
