### ISSUE TITLE
Image will always be lost when insert multiple subdoc in which more than one subdoc contain picture

### ISSUE THREAD

**Issue by kikakkz** [elapouya/python-docx-template#245]
Step:
1  Prepare a template which has more than 2 subdoc template
2  Prepare 2 subdoc, each contain a image. When unzip de subdoc docx, image is named image1.png in both docx.
3  Render the template with subdoc.
Expect:
All subdocs are inserted with right image.
Result:
Only 1 image1.png is kept in final output docx, both inserted docx use this image1.png as its image to display.

I do more for that:
I do not insert the docs with subdoc, but just extract all sub elements except image, then fill the  extracted elements to output docx. After that, I add_picture to output docx, then the picture will be numbered rightly. So I think it may be not perfect when process image with same name in different subdoc.

**Comment by kikakkz** [comment]
And, this issue is actually found when I want to insert a rtf file in to template. The rtf file contain a image, then I convert the rt file to docx with win32com's SaveAs API. But the converted docx cannot be used to be a subdoc, otherwise it will corrupt the output docx. So I extract all element from the converted docx except image to add to output docx, and add the image from unzip file additionally. This may be a clue for guys who need to do same job as me to process a complex template.

**Comment by elapouya** [comment]
subdoc support is limited in docxtpl, this is mainly the case about attachements (including images) and styles.
subdocs should be avoided is possible.
I will not fix subdoc issues as it is very difficult to merge documents with different contexts.
