### ISSUE TITLE
Use python-docx-template with python-docx 0.8.8 or newer 

### ISSUE THREAD

**Issue by dragosey** [elapouya/python-docx-template#246]
Hello,

I'm currently using python-docx-template alongside pythong-docx v0.8.7 and it's working well, but, I am now trying to dynamically add images inside header area of my document file using jinja2 tags.

I saw that python-docx v0.8.8 has support for headers and footers so, my question is, are you planning on updating python-docx-template in order to support the new version of python-docx?

Thanks!

**Comment by elapouya** [comment]
Good question, actually there is a bug in docx 0.8.7 that leads to
unreadable docx by recent MSWord version.
I planned to include 0.8.7 into docxtpl directly and fix it.
I tried to use docx 0.8.10, but it implies too many investigations to make
it work with docxtpl...
So I am a little bit puzzled
I have not chosen yet...

Le lun. 6 janv. 2020 à 15:13, Dragos Sandu <notifications@github.com> a
écrit :

**Comment by dragosey** [comment]
Hello there,

Do you have any updates on this? We postponed our plan hoping for a fix with this problem. If an update which will provide this feature is not available, is there any walkaround we can use in order to make it work temporarily until this feature will be fully supported?

Is there a difined time horizon for this one?

Thanks!
