### ISSUE TITLE
Alignment - left, right, both

### ISSUE THREAD

**Issue by Felicce1990** [elapouya/python-docx-template#247]
I am trying to implement an alignment, which is not working. Adding one of the following Tags to the Listing or RichText class doesn't seem to work.

<w:pPr>
    <w:jc w:val="left"/>
</w:pPr>

<w:pPr>
    <w:jc w:val="right"/>
</w:pPr>

<w:pPr>
    <w:jc w:val="both"/>
</w:pPr>

Has anyone tried that before and found an answer?

**Comment by elapouya** [comment]
closing as there is no answer
