### ISSUE TITLE
Nested {% vm %}

### ISSUE THREAD

**Issue by System25** [elapouya/python-docx-template#249]
Hi, I'm trying to produce the following table: (https://i.stack.imgur.com/Z4k5w.png)

| Layer 1 | Layer 2 | Layer 3
|--|--|--
| {%tr for layer1 in layers %} 
| {%tr for layer2 in layer1.layers %}
| {%tr for layer3 in layer2.layers %}
| {% vm %} {% vm %} {{ layer1.name }} |  {% vm %} {{ layer2.name }} | {{ layer3.name }}
| {%tr endfor %}
| {%tr endfor %}
| {%tr endfor %}

But using two {% vm %} produces an "Encountered unknown tag 'vm' " error.
How can I do that?

Thanks!

**Comment by System25** [comment]
Hello again,
 I've managed to to it by using a workaround.

The workaround consist in using {% cellbg layer1.vmerge() %} and that method is implemented as:

```
class Layer1:
    vmergeval = 'restart'

    def vmerge(self):
        ret = self.vmergeval
        if self.vmergeval == 'restart':
            self.vmergeval = 'continue'
            
        print('ret=%s'%(ret))
        return 'FFFFFF"/><w:vMerge w:val="%s"'%(ret)
```

So, the background of the cell is set to 'FFFFFF' and the <w:vMerge> is inserted in the template after that.

But this is just a dirty workaround. There should be a better way of doing this.

Best regards!

**Comment by JonesKenzie** [comment]
How do you use this class @System25 ?

**Comment by System25** [comment]
Hi @JonesKenzie, It's just using cellbg as indicated in https://docxtpl.readthedocs.io/en/latest/

So, you have a table like this:

| Layer 1 | Layer 2 | Layer 3
|--|--|--
| {%tr for layer1 in layers %} 
| {%tr for layer2 in layer1.layers %}
| {%tr for layer3 in layer2.layers %}
| {% cellbg layer1.vmerge() %} {{ layer1.name }} |  {% vm %} {{ layer2.name }} | {{ layer3.name }}
| {%tr endfor %}
| {%tr endfor %}
| {%tr endfor %}

And that produces the desired result.

**Comment by chaconcha** [comment]
Hi! 
In my case, I needed to have one big cell in one of the columns, and I achieved that by putting the vMerge directly in the template cell and using "continue" as the val attribute, like this:
`'FFFFFF"/><w:vMerge w:val="continue"'`
