### ISSUE TITLE
Word unreadable content when adding new column with InLineImage in table.

### ISSUE THREAD

**Issue by pablosolar** [elapouya/python-docx-template#251]
Hello all, 

I've got defined this table in my template that inserts two signatures:

![image](https://user-images.githubusercontent.com/28707927/73171551-4b296c00-4101-11ea-8a34-dd47ee776f67.png)

(First row if inserting signature images with InlineImage).

When rendering this template, final word opens correctly.

Now, depending on a code condition, I need to insert an extra column to have three signatures. So I try:

![image](https://user-images.githubusercontent.com/28707927/73172013-5a5ce980-4102-11ea-9e82-45dbef6f6630.png)

If I render the template with the three columns (this one with empty values), I can also open the final word correctly. 

But when I render the template with the three columns properly filled, I get:

![image](https://user-images.githubusercontent.com/28707927/73172110-8e380f00-4102-11ea-9419-39dca1c70503.png)

I tried to delete de table and just define the variables normally. I tried to insert three independent tables. I tried to define each signature in different lines. But nothing. 

I also tried to use always the same image (just to check that the new one was corrupted or not). But the same image works fine for two columns and bad when generating three). But nothing.

Images are same-sized and same-formatted (png).

Could you help me?? I am going crazy.

Thank you all in advance!

**Comment by silver-ag** [comment]
I have a similar issue. I have a large template which produces apparently damaged documents when more than one InLineImage is provided. If I say yes to recovering the document it recovers fine. I've had a look at what the recovery changes, and it seems that the problem may be two images having the same id, but I'm not sure what triggers the issue since a simple test template works fine with multiple images.

**Comment by elapouya** [comment]
Could you try with the very latest version of docxtpl and keep me informed ?

**Comment by SmartDataCode** [comment]
Hi,

I'm having also a similar issue, using version 0.10.0. I have a table to represent 5-scale scores with the following format:
<img width="476" alt="afbeelding" src="https://user-images.githubusercontent.com/20578268/82831078-b587c880-9eb7-11ea-8891-edb18369ba32.png">
(there is some `jinja2` logic to place `{{marker}}` in the right column, but for simplicity not shown here). The `{{marker}}` is a small `InlineImage` (60x60 px).
It works all fine up to 9 rows, from 10 rows and up I get the same message as above.

I also tried to use unique markers and images: `{{marker01}}` for row 1, `{{marker02}}` for row 2, etc. Each having a unique `InlineImage`. The curious thing is that this works up to 19 rows and then fails after 20 rows and up.

Hope this helps in locating the issue.

**Comment by tsotnesharvadze** [comment]
> Hi,
> 
> I'm having also a similar issue, using version 0.10.0. I have a table to represent 5-scale scores with the following format:
> <img alt="afbeelding" width="476" src="https://user-images.githubusercontent.com/20578268/82831078-b587c880-9eb7-11ea-8891-edb18369ba32.png">
> (there is some `jinja2` logic to place `{{marker}}` in the right column, but for simplicity not shown here). The `{{marker}}` is a small `InlineImage` (60x60 px).
> It works all fine up to 9 rows, from 10 rows and up I get the same message as above.
> 
> I also tried to use unique markers and images: `{{marker01}}` for row 1, `{{marker02}}` for row 2, etc. Each having a unique `InlineImage`. The curious thing is that this works up to 19 rows and then fails after 20 rows and up.
> 
> Hope this helps in locating the issue.

I Have Same Issue, My Break Point Is Eighth Column

**Comment by elapouya** [comment]
Please could you provide me a minimal test case with a docx template file and the corresponding python file to generate the wanted docx

**Comment by maarten-betman** [comment]
I had the same issue when adding an `InlineImage`. The work-a-round discussed in #243 fixed the issue for me

**Comment by elapouya** [comment]
Could you tell me what version of docxtpl AND python-docx you are using (`pip list`)  ?

**Comment by maarten-betman** [comment]
python-docx==0.8.7
docxtpl==0.10.0

**Comment by elapouya** [comment]
Please upgrade python-docx to 0.8.10, there were many changes since the 0.8.7

**Comment by ibooj** [comment]
I use docxtpl==0.11.2 and python-docx==0.8.10 and put InLineImage in the document, but MSOffice can't open it although libre office opens it well. What's wrong?

**Comment by elapouya** [comment]
did you use MSWord or LibreOffice to create your template ?

**Comment by ibooj** [comment]
I'm not sure how it was created but last time I edited it via LibreOffice

**Comment by ibooj** [comment]
The problem is solved. I loaded the template Docx to google drive and save it back to my pc, and now MSOffice can open it after processing. Although the file's size got larger
