### ISSUE TITLE
Conditional cell background formatting problem

### ISSUE THREAD

**Issue by richard-moss** [elapouya/python-docx-template#252]
Hi there,

Quick thanks first for an awesome package!

I'm trying to selectively set the background color of cells in a tab based on the cell value, but can't seem to get it working.

In my table I have a cell defined as
`{{ m.thick_error | round(1) }}`
This works fine - I get the value of my 'thick_error' variable printed with a single decimal place.

Now what I'd like to do is specify the background color only if the value of 'thick_error' is ' too big'. ...this is an error value variable, so a value too high is a problem and I'd like to highlight those cells.

If I use a jinja {% if... %} with a plain text  between the endif, it works, in the sense I only get the string included based on the result of the if:
`{% if m.thick_error|abs() >  10 %} BIG {% endif %} {{ m.thick_error | round(1) }}`
In the above, I only get the string 'BIG' in front of the variable value if it's absolute value is greater than 10.

However, if I try the above, but instead use cell background color setting in place of the plain text 'BIG' above, it doesn't work: _all the cells_ have the background color set, regardless of the 'if':
`{% if m.thick_error|abs() >  10 %} {% cellbg ‘555555’ %} {% endif %} {{ m.thick_error | round(1) }}`

I don't know jinja well, but is there a way to have the {% cellbg %} only get used based on the surrounding if?

thanks!

**Comment by robertpdx** [comment]
I did something similar to your idea by creating/setting an attribute of the data object and assigning it a default value of white, and in the code before rendering did the checking and set the value to some other color. Each cell in the table has a cellbg tag.  

e.g.  {%cellbg a.somBkgdVar%}{{a.SomeValueVar|e}}

For my application I have a variable number of records but for each record the table is fixed, so I was able to easily define vars for each cell.  You'd have to get creative for a variable table size using this method.

**Comment by richard-moss** [comment]
Thanks for the reply Robert!

I saw that in the examples, and might use that approach.

**I actually just found out how to do it in jinja** - hopefully this might help anyone else as well.   This use case is different to your approach (and the examples), because it allows you (if you want) to set the limits for formatting solely in the template file, without having to calculate it in the code doing the templating.
So you can update any cell highlighting type formatting without having to change the code, only the template.

You can do this:

`{% cellbg ‘555555’ if m.thick_error|abs() >  10 %} `

Note that you include the `if` as part of the single jinja statement.  So in my example above, to make it work you can do in a table row:

```
{%tr for m in m4 %}
    {% cellbg ‘555555’ if m.thick_error|abs() >  10 %}
    {{ m.thick_error }}
{%tr endfor %}
```
