### ISSUE TITLE
How to generate index (bibliography)?

### ISSUE THREAD

**Issue by ben-ce** [elapouya/python-docx-template#254]
Hi, I'm trying to create a index in my docs. The library correctly creates the entries but it does not assign the correct page numbers and hyperlinks in the index.
The following piece creates the entries in the index:
```console
for item in items %}
{{ item.id}} – {{ item.name }}
{% endfor %}
```
The index creates entries up to level 4.
After manually updating the index with one click, it's good, but I'd like it to be automatically good.
Is there a right way to do this? Any suggestions?
Thanks

**Comment by elapouya** [comment]
Indexing is not supported with docxtpl has it does not know how the document will be rendered by MS Word. May be, there is a way to trigger index recalculation, but I do not know if it is possible. If someone knows how, I will be very happy to include this feature in a next version of docxtpl.
