### ISSUE TITLE
Diagnosing failer render()?   ...how to get more info

### ISSUE THREAD

**Issue by richard-moss** [elapouya/python-docx-template#256]
Hi there,

I'm docx template v0.6.3 with python-docx 0.8.7 and had some great success with it.  I'm using it to generate moderately complex reports, with images, and most of the time working well.

However I do have one big problem - when something fails during render() how do you figure out what/where the problem is?

For instance, I'm currently having render() fail and the exception I'm getting back is simply:
`'Imgtype'`

Is there a way to get more informative information when render fails as to where and why?

This is a huge problem for me, as trying to diagnose what a problem is on a moderately complex template with only that info is pretty hard!

thanks,
Richard

**Comment by elapouya** [comment]
Please upgrade to latest version of docxtpl, then provide me a stacktrace on a new issue.
Otherwise, there is no special way to investigate but using a debugger... sorry.
