### ISSUE TITLE
How do a dynamic table generate?

### ISSUE THREAD

**Issue by Barolina** [elapouya/python-docx-template#257]
I don't know , how many will columns of table be?
How do a dynamic table generate?

Thank you

**Comment by shexuelang** [comment]
I have success yet，just like this：
![image](https://user-images.githubusercontent.com/22361141/76682774-cefbd100-6639-11ea-8606-eb26e41b7b81.png)
maybe this is helpful for you

**Comment by Barolina** [comment]
thanks you
