### ISSUE TITLE
Support HTML tags using template variables

### ISSUE THREAD

**Issue by duanyp1991** [elapouya/python-docx-template#26]
Hi @elapouya ,
Very good library, thanks for the good work here.

Would it be possible that we can use template variables which contains the html tags (the text content comes from a HTML editor)? 

We don't need the complex styles with external css classes. we only wanna keep the following:

- \<br\> new line
- \<ul\>\<li\>

- Bold/italic text

Any advise?

Thanks in advance.:)

**Comment by elapouya** [comment]
Sorry, it is not possible...yet (but I keep the idea)

Thx
