### ISSUE TITLE
How to insert multiple paragraphs

### ISSUE THREAD

**Issue by komawar** [elapouya/python-docx-template#261]
We have a list of paragraph objects that are ready with custom styles. Is there a way we can insert them using one or many (jinja2) tags with the help of this library?

I see that there is the subdoc template variable (https://docxtpl.readthedocs.io/en/latest/#sub-documents) that helps us insert subdocuments.

```
    tpl=DocxTemplate('templates/subdoc_tpl.docx')
    sd = tpl.new_subdoc()
```

Is there a way to do this for docx Document objects? Or a way to convert them into a subdoc object?

**Comment by elapouya** [comment]
What do you mean by "paragraph objects that are ready with custom styles" ?
is that at python side or docx template side ?

In your docx template you could do something like this :
{%p if have_paragra1 %}
{{r paragraph_with_style_via_richtext}}
{%p endif %}

You can also use jinja loops etc...

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 6 avr. 2020 à 12:38, Nikhil Komawar <notifications@github.com> a
écrit :

**Comment by komawar** [comment]
@elapouya thanks for the response.

I have a script that generates paragraph objects https://python-docx.readthedocs.io/en/latest/api/text.html#paragraph-objects

These are created on python side where

```
import docx
d = docx.Document()
p1 = d.add_paragraph("Some data", style="List Number")
p2 = d.add_paragraph("Some more data", style="List Number 2")
p3 = d.add_paragraph("And some more data", style="List Number 3")
...
# DO NOT save the document
```

Say I have a nested list (could be more complex list).
This way we have a series of paragraphs already added to the docx Document already constructed. 

Now I'd like to use the template library to simply insert this into a template document of python-docx-template...

```
doc = docxtpl.DocxTemplate("tpl-doc.docx")
context = <add_my_Document()_here> (or some alternate way to insert the paragraphs
doc.render(context)
doc.save("newly-created-tpl-doc.docx")
```

What's the best way of going about this?

**Comment by elapouya** [comment]
This is not the way to use docxtpl,You should use RichText to create your text (You can use '\a' to create a new paragraph) : 

```
my_text = RichText
my_text.add("Some data", style="List Number")
my_text.add("\aSome more data", style="List Number 2")
context = {"my_text":my_text}

And then use {{r my_text}} in your template.

```
Now, if you really want to include a docx document like you want, it as easy as putting in your template : `{{p my_docx}}` with `context = {"my_docx":d}`
But this is not recommended because docx rendering in template has some limitations : you may encounter problems with styles for example. 

Please see tests/richtext.py and tests/subdoc.py examples for more informations.

**Comment by komawar** [comment]
@elapouya I see, I was indeed seeing some formatting/rendering issue when inserting stylized subdoc and was looking into why that may be...

Thanks for the pointer on RichText.
