### ISSUE TITLE
replace_zipname does not work for embedding xlsx files into docx documents

### ISSUE THREAD

**Issue by juanmacarrillo** [elapouya/python-docx-template#266]
Related with [comment](https://github.com/elapouya/python-docx-template/issues/221#issuecomment-611553187) in issue #221.

I tried to embed a xlsx file following the simple (thanks for making them simple) in the most recent (v 0.7) [documentation](https://docxtpl.readthedocs.io/en/latest/).

Attached is the most simple reproducible example I came up.

```
from docxtpl import DocxTemplate

nameDocx = "test_docxtpl.docx"
nameAnex = "new_embedded.xlsx"
nameInsertedFile = "word/embeddings/Microsoft_Excel_Worksheet1.xlsx"
###########################

doc = DocxTemplate(nameDocx)

doc.replace_zipname(nameInsertedFile, nameAnex)

doc.save(nameDocx)
```
[replace_zipname_xlsx.zip](https://github.com/elapouya/python-docx-template/files/4473620/replace_zipname_xlsx.zip)

**Comment by elapouya** [comment]
fixed in 0.8.1
