### ISSUE TITLE
Adding a list of InlineImage 

### ISSUE THREAD

**Issue by mrtouch93** [elapouya/python-docx-template#267]
Hi elapouya, I've got a list of image which I'd like to insert in my template with a for loop. 
My context is 
![image](https://user-images.githubusercontent.com/59916156/79209697-0f6e8a80-7e44-11ea-80e3-d7a3f3d33559.png)

And in my template I've got
![image](https://user-images.githubusercontent.com/59916156/79209788-27dea500-7e44-11ea-9307-1cd62384cf45.png)

But Jinja raise an error: "InlineImage" object is not iterable
![image](https://user-images.githubusercontent.com/59916156/79209878-480e6400-7e44-11ea-920f-0bb1fd8d1a5e.png)

In my situation I don't think I can insert a sub paragraph for every image, am I missing something or simply is not possible?

**Comment by elapouya** [comment]
You forgot to specify a list for `dict_image `as you are using a `for` in your template
And yes, it is possible to have a paragraph for each of your image
just put a `{{p my_paragraph_var }}` in your for loop in your termplate and add `my_paragraph_var` in your context
Please have a look in the examples in tests/
