### ISSUE TITLE
Add Jinja2 whitespace controll

### ISSUE THREAD

**Issue by vildead** [elapouya/python-docx-template#268]
When having long paragraph where some words/sentences are shown only on condition, the syntax gets very messy. 
Instead of:
```
My house is located {% if living_in_town  %} in urban area {% elseif %} in countryside {% endif %} and I love it. 
```
something like this would help a lot:
```
My house is located
{%- if living_in_town  -%}
  in urban area 
{%- elseif -%}
  in countryside
{%- endif -%}
and I love it.

**Comment by elapouya** [comment]
use {%p xxx %} syntax see documentation and examples in tests/

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by vildead** [comment]
I am well aware of doc and examples. Also kinda related issues #62 and #206.  Maybe I am missing something. I have just no luck. 
I have tried:
```
My house is located
{%p if True %}
in urban area 
{%p else %}
in countryside
{%p endif %}
and I love it.
```
and it gives me following output:
```
My house is located
in urban area
and I love it.
```
while I want all parts of the sentence on the same line.

**Comment by elapouya** [comment]
Sorry, I believed you wanted seperate paragraphs

To do what you want it requires to have the possibility to merge some
paragraphs, that is not possible yet. But it is a good idea...

**Comment by elapouya** [comment]
I pushed the new feature you requested (not yet on pypi) : could you clone this repo and test it ?

**Comment by elapouya** [comment]
new wanted syntax {%- xxx -%} is now part of the v0.9.0

**Comment by vildead** [comment]
I've just tested and it works!
 Thx for the light speed
