### ISSUE TITLE
ValueError: target_part property on _Relationship is undefined

### ISSUE THREAD

**Issue by Banaanhangwagen** [elapouya/python-docx-template#271]
I used docxtpl v0.6.3 in order to generate 3 docx based on 3 templates.
One template contains headers and footers

Since the update to v0.8.0 (where you use python-docx (0.8.10)), generating that third template gives the following error:
```
File "C:\Users\xxx\Desktop\xxx.py", line 476, in <module>
    doc.render(context)
  File "C:\Program Files\Python37\lib\site-packages\docxtpl\__init__.py", line 294, in render
    self.map_headers_footers_xml(relKey, xml)
  File "C:\Program Files\Python37\lib\site-packages\docxtpl\__init__.py", line 266, in map_headers_footers_xml
    new_part.load_rel(rel.reltype, rel.target_part, rel.rId, rel.is_external)
  File "C:\Program Files\Python37\lib\site-packages\docx\opc\rel.py", line 161, in target_part
    raise ValueError("target_part property on _Relationship is undef"
ValueError: target_part property on _Relationship is undefined when target mode is External
```

Can this be solved here, or is it a python-docx issue ?

**Comment by elapouya** [comment]
Could you try with 0.9.x
If it does not work, please provide your code and your template.

**Comment by Banaanhangwagen** [comment]
Same error with latest 0.9

I have to precise that the header contains a picture; when it's only text, there is no error.
Maybe you can reproduce it also ?

Unfortunately I can only share a part of the code:
```
from docxtpl import DocxTemplate
[snip]
template = 'xxx.docx'
    req_out = output_path + new_filename_req

    doc = DocxTemplate(template)
    context = {[snip],
               'FIRSTSEEN': datetime.strftime(liste[-1]['DATE'], "%d/%m/%Y %H:%M:%S"),
               'LASTSEEN': datetime.strftime(liste[0]['DATE'], "%d/%m/%Y %H:%M:%S"),
               'DATE_NOW': datetime.strftime(datetime.now(), "%d/%m/%Y"),
               'PROVIDER': provider
               }
    doc.render(context)
    doc.save(req_out)
[snip]
```

**Comment by elapouya** [comment]
Please, provide me a test case I can simply reproduce (simplify python code
and template to the minimum)

Le mer. 22 avr. 2020 à 13:20, Banaanhangwagen <notifications@github.com> a
écrit :

**Comment by Banaanhangwagen** [comment]
Ok, we did some old-school debugging here. 
It appears that the error is not due to a picture in the header/footer, but due to an URL.

> Used simplified script for reproducing:
```
from docxtpl import DocxTemplate
from datetime import datetime

''' DocxTPL '''

template = 'test.docx'
req_out = 'test_output.docx'

doc = DocxTemplate(template)
context = {'FIRSTSEEN': datetime.strftime(datetime.now(), "%d/%m/%Y"),
           'MIDDLESEEN': datetime.strftime(datetime.now(), "%d/%m/%Y"),
           'LASTSEEN': datetime.strftime(datetime.now(), "%d/%m/%Y"),
           }
doc.render(context)
doc.save(req_out)

print('document Word created : {} '.format(req_out))
```


> used docx for reproducing.
[test.docx](https://github.com/elapouya/python-docx-template/files/4516830/test.docx)

**Comment by ddiguru** [comment]
I've got exactly the same issue. I have a template document that has external URLs that have been attached to some social media icons, and these are failing. I'm having problems just figuring out how to find them and root them out of the template doc. But it's the exact same issue. I tested our code against 0.9.0, 0.8.1, and 0.8.0 - all fail. 0.7.0 seems to work. 

I just wish i could figure out how to locate these hrefs/links and just remove them from the template. I subscribed to this issue to keep my eye on it. I will continue to fumble about. Thanks.

**Comment by elapouya** [comment]
I found a workaround :

In your template, Edit the link and specify the target window (where the
link have to be displayed). In french it is the button "Cadre de
destination".
If you leave the default value : it will crash docxtpl. If you choose "new
windows" : the docx generation works well.

Le jeu. 23 avr. 2020 à 05:21, Patrick Piper <notifications@github.com> a
écrit :

**Comment by Banaanhangwagen** [comment]
Strangely, this workaround does not work for me.

Other workarounds: simply "remove hyperlink" of the URL, or another one: put the URL in body
Nuke-workaround: do not use header/footer

**Comment by elapouya** [comment]
What version of MS Word are you using ?

**Comment by Banaanhangwagen** [comment]
Office365 v20.03 (build 12624.20382)

**Comment by elapouya** [comment]
I made a change : could you try the latest version (git clone) and tell me it solved your issue ?

**Comment by ddiguru** [comment]
Just tested my issue. That resolved the problem. Good to go. Thank you!

**Comment by Banaanhangwagen** [comment]
Tested, and it works. Thank you!
