### ISSUE TITLE
Page not rendering correctly

### ISSUE THREAD

**Issue by adithyasujith** [elapouya/python-docx-template#273]
Hi,
I am trying to render html content using docx, but some how while generating the tempate its generating with xml contents like below
<img width="1680" alt="Screenshot 2020-05-03 at 15 40 54" src="https://user-images.githubusercontent.com/45132492/80915746-91234b00-8d54-11ea-9f56-d637e12e7f6e.png">

My doc template is like below
<img width="1680" alt="Screenshot 2020-05-03 at 15 42 42" src="https://user-images.githubusercontent.com/45132492/80915793-d6477d00-8d54-11ea-8a34-89c0b0f4e224.png">

Please let me know how to fix this?.

**Comment by elapouya** [comment]
docxtpl does not support HTML code rendering.
What would be an example of what you want to generate ? may be there another way ...

**Comment by adithyasujith** [comment]
Ok, i am using ckeditor for saving the following text,

- sampletext
- sampletext
- sampletext

 when its saved to db its saved including html tags <ul><li>sampletxt</li><li>sampletxt</li><li>sampletxt</li> </ul>

and when i generate the document using docxtpl i want the text to be converted and rendered as the normal text without html  tags .  If you know another way please let me know

**Comment by elapouya** [comment]
The only way is to translate your HTML code into text or docxtpl.RichText.
If you really want to have exactly all ckeditor is able to do (images, tables etc...), it is not possible to include that via docxtpl.
