### ISSUE TITLE
undeclared_template_variables does not include header/footer variables

### ISSUE THREAD

**Issue by LoneGunman001** [elapouya/python-docx-template#274]
Hi,

It appears that undeclared_template_variables does not include header/footer variables at the moment. I am new to this but can header/footer contain variables?

**Comment by elapouya** [comment]
undeclared_template_variables should work with header/footer as jinja2 look inside the whole xml file.
You can put variable in header/footer, see : tests/header_footer.py

**Comment by LoneGunman001** [comment]
Hi,

I just tested the code and header/footer variables do work, but undeclared_template_variables do not reflect the variables.

Using header_footer.docx, my program only showed _{'mysubdoc', 'title'}_ but it left out _date_ variable in the header.

The problem lies in __init__.py. `get_undeclared_template_variables()` only calls `get_xml()` but not `get_undeclared_template_variables()`

**Comment by elapouya** [comment]
Good point : I missed get_headers_footers_xml()
I'll fix that.

**Comment by elapouya** [comment]
its fixed (git clone)
