### ISSUE TITLE
{%- if -%} tag causes document not to open

### ISSUE THREAD

**Issue by Marijus** [elapouya/python-docx-template#275]
I have added {%- -%} tags like this:

<img width="315" alt="Screen Shot 2020-05-18 at 8 05 26 PM" src="https://user-images.githubusercontent.com/654110/82240546-448a6300-9943-11ea-8843-108074335cd2.png">

Causes this error:

<img width="429" alt="Screen Shot 2020-05-18 at 8 06 35 PM" src="https://user-images.githubusercontent.com/654110/82240585-523fe880-9943-11ea-8c79-c1e857adfd4b.png">

If I remove the "-" from "{%-" tag it works as expected. Am I missing something?

**Comment by elapouya** [comment]
Why are you using {%- -%} ?
it should be {%p ... %}

**Comment by iLeandro** [comment]
I have the same problem. I have a nested for with a if statement inside the second for. If my my for loop content has 100 rows and only 15 meet the if requirements, i will have 85 break lines

**Comment by elapouya** [comment]
Please provide the docx template

**Comment by iLeandro** [comment]
```
{%p for item in row_findings %}
{% for endpoint in row_endpoints %}
{%- if endpoint.finding_id == item.f_id -%}
{{ endpoint.host }}		
{%- endif -%}
{% endfor %}
{{ findings_data }}
{%p endfor %}
```

**Comment by elapouya** [comment]
Try:

```
{%p for item in row_findings %}
   {% for endpoint in row_endpoints -%}
      {%- if endpoint.finding_id == item.f_id -%}
         {{ endpoint.host }}		
      {%- endif -%}
   {%- endfor -%}
   {{ findings_data }}
{%p endfor %}
```
Should be equivalent to 
```
{%p for item in row_findings %}
   {% for endpoint in row_endpoints %}{% if endpoint.finding_id == item.f_id %}{{ endpoint.host }}{% endif %}{% endfor %}{{ findings_data }}
{%p endfor %}
```

**Comment by elapouya** [comment]
It is not an empty line but a new paragraph that you have. 
I do not have your full code, so I cannot help you further.
Just try to remove the 'p' from {%p and make a CTRL+RETURN at the good place in your template to make a new line and not a new paragraph.
