### ISSUE TITLE
Table Cell Question

### ISSUE THREAD

**Issue by iLeandro** [elapouya/python-docx-template#277]
Hi!
Is it possible to do this?
![1111](https://user-images.githubusercontent.com/32276456/82571794-5fdfb300-9b7b-11ea-91af-881a6f5e95ea.PNG)

Ignore the yellow things
The ideia is to populate data like the image in group of two.
1 2
3 4
5 6 ...

instead of 
1
2
3
4 ...

I saw de horizontal merge template example but I think it's not for me

Cheers

**Comment by elapouya** [comment]
You can do that at python side : instead of giving one simple list in the context, give a list of lists (columns)
See tests/dynamic_table.py to see how rows and columns are managed.

**Comment by iLeandro** [comment]
If my context variable is like this im in the right path?

```
[
    [
        {'host': 'REDACTED'}, 
        {'host': 'REDACTED'}
    ], 

    [
        {'host': 'REDACTED'}, {'host': 'REDACTED'}
    ], 

    [{'host': 'REDACTED'}, {'host': 'REDACTED'}]
]
```

**Comment by elapouya** [comment]
That's the idea...

**Comment by iLeandro** [comment]
To create an output likes this:
`[
   ['10.10.8.85', '172.13.37.43'], 
   ['192.168.1.110', 'metasploitable3-ub1404'], 
   ['preprod.boardvantage.net', 'qa3app01'], 
   ['qa3app02', 'qa3app03'], ['qa3app04', 'qa3app05']
]`

Group the array
```
def grouper(n, iterable):
   iterable = iter(iterable)
   return iter(lambda: list(IT.islice(iterable, n)), [])


list_endpoints = list(grouper(2, endpoint_array))
```


In template:
```
{%p for triple in all_endpoints %}
{%tc for val in triple %}  {{val}}  {%tc endfor %}
```

This will give the desired output.
