### ISSUE TITLE
Inappropriate requirements in setup.py

### ISSUE THREAD

**Issue by zondo** [elapouya/python-docx-template#28]
The documentation requirements in `setup.py` could do with some tweaking:
- The sphinx version restriction seems redundant.  I have Sphinx 1.3 installed, and it works fine to build the docs.  But without manual tweaking of `setup.py` the `<1.3b` restriction stops me installing from pip.
- sphinxcontrib-napoleon isn't used in `docs/conf.py`, but is mentioned as a requirement.  (In fact, with recent sphinx versions, that extension is built in.)

**Comment by mdwgrogan** [comment]
Sphinx probably shouldn't be in install_requires at all - it's only used for building the docs, which is normally something only contributors would want to do. Any chance of removing this dependency?

**Comment by maerteijn** [comment]
We have Sphinx version conflicts in our projects as well due to this dependency. See https://github.com/elapouya/python-docx-template/pull/57

**Comment by elapouya** [comment]
Latest Sphinx package is now taken.
