### ISSUE TITLE
Add Images in a Nested Loop

### ISSUE THREAD

**Issue by iLeandro** [elapouya/python-docx-template#280]
I want to add images to my docx document.

Using the normal way as in the docs, InlineImage works just fine.
`'catimage': InlineImage(doc, '/media/46c9f2d6-bcc4-4b32.PNG')`

Now, I'm trying to add multiple, so I followed the structure in
https://github.com/elapouya/python-docx-template/blob/master/tests/inline_image.py

And my structure looks like this:
```
'images': [
    {
        'id': 799, 
        'image': "InlineImage(doc, '/media/d781dffb-f0da-4025.png')"
    },
    {
       'id': 790, 
       'image': "InlineImage(doc, '/media/64cbfe54-e0c3.png')"
    }
]
```

Then in my template I have a validation. Something like:
```
{% for image in images %}  {% if image.id == XXXX.id %}
{{ image.image }} {% endif %} {% endfor %}
```

but it does not work! it renders the text. so instead of getting the image, I get the 'image' content string (InlineImage(doc, /media........).

Is is because of having double quotes instead of singles quotes in the structure? I've been trying to replaced them with single quotes to take that out of the equation.

**Comment by elapouya** [comment]
You must give an InlineImage object (not a string) this is the reason why it works for your first case and not for your 2nd case. So remove your double quotes

**Comment by iLeandro** [comment]
I have one variable (variableX) that contains the following structure:
```
[
            {
                'id': 799, 
                'image': InlineImage(doc, '/media/d781dffb.PNG')
            },
            {
                'id': 813, 
                'image': InlineImage(doc, '/media/46c9f2d6.PNG')
            },
            {
                'id': 834, 
                'image': InlineImage(doc, '/media/d19b8656.png')
            }
]
```

If I use that variable in the context ( `context = { 'images': variableX, }` ) is does not work!
But If I copy the the variableX content to the context instead of calling it, it will work. 
```
context = {
     'image': [
            {
                "id": 813,
                "image": InlineImage(doc, '/media/46c9f2d6.PNG')
            },
            {
                "finding_id": 860,
                "image": InlineImage(doc, '/media/233ab907.png')
            }
     ],
}
```

But I need to use a variable. Is it a known bug?

**Comment by elapouya** [comment]
please provide the files so I can test that.

**Comment by iLeandro** [comment]
Hi,
Can you provide me your e-mail?

**Comment by elapouya** [comment]
You can drag&drop files where you type texte

**Comment by iLeandro** [comment]
I was debugging and noticed that when I print the `context`, using the variables name above, the `image ` var, where it says `InlineImage....` it prints a memory location? something like `docx.inline image object at 0xxxxx` And the `variableX `prints the whole object `InlineImage(doc, '/media/d781dffb.PNG')`

**Comment by iLeandro** [comment]
Since .py is not supported, I changed the extension to .txt
[redacted.txt](https://github.com/elapouya/python-docx-template/files/4781852/redacted.txt)

The template...
[redacted.docx](https://github.com/elapouya/python-docx-template/files/4781877/redacted.docx)

**Comment by elapouya** [comment]
As I do not have a running code, I cannot reproduce. Nevertheless, your code is very similar to the test tests/inline_image.py which works well. I suggest to have a look.
This close definitively the discussion.
