### ISSUE TITLE
Words escaping

### ISSUE THREAD

**Issue by dzhabrailovsn** [elapouya/python-docx-template#281]
![image](https://user-images.githubusercontent.com/17762648/84658768-1175c800-af1f-11ea-806a-0e1d0c6971dc.png)
I have a table like wich i fill with json. But with every row my row 
### ВСЕГО по субъекту:
also doubling, but i want to  display this words only at one time. What should i do ?

**Comment by josezulu** [comment]
I don't know if this would work, but I think you just need to merge the cell where "ВСЕГО по субъекту:" is with the cell right above it and the one underneath.
