### ISSUE TITLE
\n is read as space instead of paragraph

### ISSUE THREAD

**Issue by iLeandro** [elapouya/python-docx-template#282]
When using `tpl.render(context, autoescape=True)` if I have 'okok': 'Paragraph\a test\n\ntest\ntest',

According to the documentation \a should make a paragraph (it doesn't) and \n which I'm used to be a new line, it is recognized as space.

**Comment by elapouya** [comment]
please provide minimal test files so I can reproduce

**Comment by iLeandro** [comment]
```
doc = DocxTemplate("template.docx")

context = {
    'okok': 'Paragraph\a test space\n\ntest space\nteste space',
}

doc.render(context, autoescape=True)
doc.save("generate.docx")
```

In template.docx i just simply call {{ okok }}

Can you anwser https://github.com/elapouya/python-docx-template/issues/280 after this?
Thank you

**Comment by elapouya** [comment]
I need your FILES not an example. same thing for #280

**Comment by iLeandro** [comment]
Since .py is not supported, I changed the extension to .txt
[redacted.txt](https://github.com/elapouya/python-docx-template/files/4781879/redacted.txt)

Template
[redacted.docx](https://github.com/elapouya/python-docx-template/files/4781881/redacted.docx)

This has the problem address in https://github.com/elapouya/python-docx-template/issues/280 too,

**Comment by elapouya** [comment]
please provide a fully runnable test case : the py file has no import, functions are missing.
In the docx template, you use ImageC that is not referenced somewhere...
The best way is to give a tar file : py file, docx tpl, the pictures you are using + Functions that are missing

**Comment by iLeandro** [comment]
Sir, I can not send you the full code, not here.
The one that I sent you it's taken from the original. 
The import I have is  `from docxtpl import DocxTemplate, Listing, InlineImage`, the `imageC `was misswritten, it was supposed to be `imageP`.

**Comment by iLeandro** [comment]
For this problem you don't need my full code...

You have all you need in what I sent you. Template should only include de {{ okok }} and the .py code the context above.

The other one, it's more diffcult. only with video call

**Comment by elapouya** [comment]
For \n and \a, please use RichText() as documented. Do not forget {{r ... }} in your template also.
