### ISSUE TITLE
Images in Nested Loop (w/ Files)

### ISSUE THREAD

**Issue by iLeandro** [elapouya/python-docx-template#284]
Hi. This a continuation from https://github.com/elapouya/python-docx-template/issues/280

[REDACTED.zip](https://github.com/elapouya/python-docx-template/files/4793293/REDACTED.zip)

Inside the zip file you have two files. The `.py` and the `.docx`

`list_images` contains the exact structure I get on my output (sql query) like the documentation.
`list_images_manual` is the same structure but written manually.

The difference between both is that `list_images_manual` doesn't have double quotes on InlineImage.

I want to do the same on `list_images` but my `list_images` cames from a SQL Select Query, so it's not always the same. I already tried to remove it but I can not do it.

cheers,

**Comment by elapouya** [comment]
In your code you have
`list_images[i]['image'] = list_images[i]['image'].replace("\"", "")`
This means that `list_images[i]['image']` is a string. As I said in a previous post : 
A string is not an InlineImage Object ! this is why it does not work.
Build an InlineImage object from the image path you get from sql but do not use the path string itself.
This is really obvious. I cannot go further to help you. Do not re-open a ticket on that topic please !
