### ISSUE TITLE
Feature-request - Read in a document and get code that would output that document

### ISSUE THREAD

**Issue by utimcraig** [elapouya/python-docx-template#286]
I have a feature request, which I suppose is sort of the opposite of the package.  I'd like to read in a docx, and get the python-docx-template code that I would need to write to generate the document.  Is there a way to do this currently?

**Comment by elapouya** [comment]
This is not very clear : could give me an example ?

**Comment by utimcraig** [comment]
Sure,  Here is a very simple example:
You have the following document:

![image](https://user-images.githubusercontent.com/32027355/87654451-36946b00-c757-11ea-89a9-23a1ef50f776.png)

Then you could read in the document, and get out the following:
```
>>> doc.add_paragraph('Hello world!')
```

**Comment by elapouya** [comment]
Unfortunately, it is impossible to do such a new feature : it will require to write a whole new project, it will require to know exactly how a docx is internally made, which only Microsoft really knows, and then to create many new features that python-docx does not have yet.

If you want to automate making long documents having a lot of formatting : you can try python-docx (not python-docx-template), 
you can load a docx, then use the librairie to add what you want, but it is really complex if you want to modify an existing document.
