### ISSUE TITLE
Access to the variable name from a filter

### ISSUE THREAD

**Issue by mohovkm** [elapouya/python-docx-template#287]
Hi!
Is it possible, to access the variable name from a filter?

structure: `{"foo":{"bar":123, :"baz":""}}`

`env['filter'] = my_filter`

```
def my_filter(number: str):
    if number == '':
        raise Exception(f'You pass an empty string to the [VARIABLE_NAME]') # <- and here I want to print the name, 
# in this case its "foo.baz"
```

**Comment by elapouya** [comment]
Have a look to the file tests/custom_jinja_filters.py

**Comment by mohovkm** [comment]
> Have a look to the file tests/custom_jinja_filters.py
Thanks for the quick response!
Yes, a saw this file, it's only described filters and how to write them, but nothing about a variable name. I need to access a variable name from the filter function. is it possible?

**Comment by elapouya** [comment]
you should see jinja2 doc for that

**Comment by mohovkm** [comment]
Ok, thanks.
