### ISSUE TITLE
replace_pic with file object

### ISSUE THREAD

**Issue by arieknarie** [elapouya/python-docx-template#289]
Let me first say how happy I am with docxtpl!
However,  I came across an issue.

In my script I generate a new image and use is to replace an image in a document. Initially I saved the replacement picture locally, and then loaded it to do the replacement. It would be more elegant to directly substitute the replacement file instead.
I used this in another application where I apply InlineImage instead.

With replace_pic  I can not make it work. Most likely I am doing something wrong. There is no error, but the replacement picture can not be displayed in the document.

I made a minimal example: a script test_file_object.py and a template my_template.docx. The variable use_file_object can be set to either True or False to either use the file object or the image stored locally.

You can easily see the image is replaced as the line in the template is blue and replaced by red upon substitution.

[test_file_object.txt](https://github.com/elapouya/python-docx-template/files/4943674/test_file_object.txt)
[my_template.docx](https://github.com/elapouya/python-docx-template/files/4943675/my_template.docx)

**Comment by elapouya** [comment]
You need to rewind your ram-file (do a seek(0)).
This worked for me : 

```
import matplotlib
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg
import io
from docxtpl import DocxTemplate

#matplotlib.use('Agg')

my_figure = Figure(figsize=(3, 3))

ax1 = my_figure.gca()
ax1.plot([0, 1], [0, 1], color='red')
canvas = FigureCanvasAgg(my_figure)
canvas.draw()
my_figure_temp = io.BytesIO()
my_figure.savefig(my_figure_temp, format="png", dpi=300)
my_template = DocxTemplate('my_template.docx')
my_figure_temp.seek(0)
my_template.replace_pic('my_figure.png', my_figure_temp)
my_template.save('my_document.docx')
```

**Comment by arieknarie** [comment]
Aha! 
Thank you so much!
