### ISSUE TITLE
Losing hyperlink in subdoc

### ISSUE THREAD

**Issue by robertpagano** [elapouya/python-docx-template#290]
#124 

Hey there - I was able to use an existing docx object as a subdocument, and almost everything worked perfectly (formatting, text styles, etc.). The one thing that didn't work was a hyperlink - the text was formatted like a link, but there was no address associated with it. Should it be possible to take in a docx object with a link as a subdoc, and have that link be populated in an output file using a docx template?

Let me know if that's confusing...

Thanks!

**Comment by elapouya** [comment]
Unfortunately, this is a limitation of including a sub document : links, attachement, images : cannot be easily merge into the main document as it will required many references renumbering in main docx and/or sub-docx. There is no plan to do such a feature in the future.
