### ISSUE TITLE
{%- and  -%} not work

### ISSUE THREAD

**Issue by GoldenBite** [elapouya/python-docx-template#291]
I run the script  "python-docx-template/tests/merge_paragraph.py".
I am interested in the function of "{%-" and  "-%}",because it said it can merge the lines like below:

My house is located
{%- if living_in_town -%}
 in urban area
{%- else -%}
 in countryside
{%- endif -%}
 and I love it.

to the whole thing.
As my understanding,It will become one line.
But it did not ,after I run the script.
![merge](https://user-images.githubusercontent.com/22338146/88989154-8e150800-d30d-11ea-9ee6-5842e05f61c6.png)
Could it become one line?

**Comment by elapouya** [comment]
Please attach your docx template file (your cut & paste is not enough)

**Comment by elapouya** [comment]
If you are using directly the test, it should work : provide  `pip list` and your python version

**Comment by GoldenBite** [comment]
yes I used the test.but it did not work
my python version is 3.6 ;and pip list attached

[pip.list.txt](https://github.com/elapouya/python-docx-template/files/5032350/pip.list.txt)

**Comment by elapouya** [comment]
I do not see python-docx-template in the pip list.
Please try pipenv like explained at the very end of the documentation.
Do a fresh git clone before
Are you running windows or linux ?
