### ISSUE TITLE
how to return the rendered result  as a stream ?

### ISSUE THREAD

**Issue by hnwilsonfr** [elapouya/python-docx-template#293]
normally , we have these codes :
 tpl = DocxTemplate(tpl_file)
tpl.render(xxxxxx)
tpl.save(file_path)

but in the case of a web service,we need to return the rendered result as a stream for the caller, for example:
 return StreamingResponse( stream )

Is there any way  that  we can use something like:
tpl.to_stream()
?

**Comment by elapouya** [comment]
A docx is basically a ZIP file. It is an atomic operation that cannot be streamed. Especially there may have some postprocessing.
The only thing you can do is generate it fully and then steam it by chunk to the client, but it is not the purpose of my library.

**Comment by elapouya** [comment]
Note : instead of using a file path, you can use Memory, it will be better for streaming output : 

```
import io
t = DocxTemplate(tpl_file)
new_obj = io.BytesIO()
t.render(context)
t.save(new_obj)
```
Then stream new_obj...
