### ISSUE TITLE
Are nested loops possible?

### ISSUE THREAD

**Issue by keithcallenberg** [elapouya/python-docx-template#30]
Is it possible to nest loops in the template? If so, is there a special syntax that is necessary?

When I try to use nested for loops, I am getting this error: 
`Encountered unknown tag 'endfor'.`

This is essentially what I am trying to do:
```
{% for author in authors %}
    {% for book in author.books %} 
        {{ author.name }} {{ book.title }}
    {% endfor %}
{% endfor %}
```
I tried doing this with variations of `{%p` but that did not seem to help.

**Comment by elapouya** [comment]
Yes it is possible, and it works for me : what version are you using (pip freeze) ?
I just added a new example : tests/nested_for.py and tests/test_files/nested_for_tpl.docx

**Comment by serkandemirhan** [comment]
Can we do it in tables also?
{%tr for departman in departmans %}
{%tr for process in departman.processes %}

{{ process.name }} {{ departman.name }}

{%tr endfor %}
{%tr endfor %}

**Comment by elapouya** [comment]
it should be possible, but may be you have to put {%tr for xxx%} on the
first loop and just {% for yyy %} for the 2nd (withou the 'tr') or the
reverse....

2017-11-18 10:39 GMT+01:00 serkandemirhan <notifications@github.com>:

**Comment by serkandemirhan** [comment]
Thanks for super fast response. 
First case worked . Let me note it down that  I have to put all loop starting ending codes into seperate rows,  otherwise it doe snot work at all. bu this time I had unnecessary blank rows inside the table ,so I  set  the height of the rows to 0 cm ,so they do not show in rendered document. 
Do you have any better solution?

**Comment by saqibmubarak** [comment]
Did u find any better solution serkandemirhan ?

**Comment by serkandemirhan** [comment]
No sorry it has been more than 4 yars and I do not remember  why I used
this tool :)

**Comment by break11** [comment]
> Did u find any better solution serkandemirhan ?

1) In cell with nested for put {% vm %} tag, for example before "for" tag, and separate "vm" tag and "for" tag by "Enter".
2) Put nested "endfor" not in special row, but in last nested column, after it value tag.
