### ISSUE TITLE
custom delimiters and get_undeclared_variables()

### ISSUE THREAD

**Issue by englishincourbevoie** [elapouya/python-docx-template#302]
I want to find the undeclared_variables but when using custom delimiters, it doesn't work. 

```
from docxtpl import DocxTemplate
import jinja2

jinja_env = jinja2.Environment(block_start_string='[[', block_end_string=']]', variable_start_string='{{', variable_end_string='}}')

doc = DocxTemplate("/path/to/my.docx")

glossary = doc.get_undeclared_template_variables(jinja_env=jinja_env)

```
This code will show the variables marked with {{ }} but fails for those mentioned in tests.

Unless I'm mistaken in how I'm trying to implement, I suspect that this fails because the delimiters are hard-coded in the patch_xml function.

IF that is the source of the problem, is it possible to use re.compile and re.sub  to accept new delimiters as arguments to the patch_xml function?

**Comment by elapouya** [comment]
Yes it is hard coded. There is no plan to make it customizable.
