### ISSUE TITLE
[question] how to merge two template

### ISSUE THREAD

**Issue by lovecuey** [elapouya/python-docx-template#305]
there a big doc template, and another partial docx. and I want firstly modify the partial docx.  and put it in the big template like {{mysubdoc}}
```python3
from docxtpl import DocxTemplate
from docx.shared import Inches

tpl = DocxTemplate('templates/subdoc_tpl.docx')

sd = tpl.new_subdoc(docpath='templates/order_tpl.docx')
context = {
    'mysubdoc': sd,
}
tpl.render(context)
tpl.save('output/subdoc.docx')
```
it works. but i wanna know how to modify the "sd" template before render "tpl"?
like below

```python3
from docxtpl import DocxTemplate
from docx.shared import Inches

tpl = DocxTemplate('templates/subdoc_tpl.docx')

sd = tpl.new_subdoc(docpath='templates/order_tpl.docx')
sdcontext = {
    'customer_name': 'Eric',
    'items': [
        {'desc': 'Python interpreters', 'qty': 2, 'price': 'FREE'},
        {'desc': 'Django projects', 'qty': 5403, 'price': 'FREE'},
        {'desc': 'Guido', 'qty': 1, 'price': '100,000,000.00'},
    ],
    'in_europe': True,
    'is_paid': False,
    'company_name': 'The World Wide company',
    'total_price': '100,000,000.00',
}
sd.render(sdcontext)
context = {
    'mysubdoc': sd,
}
tpl.render(context)
tpl.save('output/subdoc.docx')
```

but it does work cause "AttributeError: 'Document' object has no attribute 'render'"

Looking forward to your answers

Thanks advance

**Comment by elapouya** [comment]
A sub-document is not a template, it is a python-docx object : you can use only what this package provides (see this package documentation), you have an example in tests/subdoc.py. There is no render() method.
You cannot do some partial rendering with docxtpl, you can only render the final "big" document with all the aggregated context values.

**Comment by lovecuey** [comment]
Very very thanks for your reply. But i want make template in template. do I  have other methods to solve this ? Your code help me a lot, thanks again~

**Comment by elapouya** [comment]
You can only embed clickable document in document (tests/embedded.py) both can be generated with docxtpl but I do not think that is what you want. Otherwise you could play with `{_{` and ` }_}` (see documentation), it is ugly and not tested, but it could answer to a 2-passes rendering.

**Comment by lovecuey** [comment]
thanks a lot, I will test it~

**Comment by SamiraIhsan** [comment]
@lovecuey you can do it like that
tpl = DocxTemplate('templates/subdoc_tpl.docx')
tpl_body = DocxTemplate('templates/order_tpl.docx')

sdcontext = {
    'customer_name': 'Eric',
    ...
}
tpl_body.render(sdcontext)
target_stream = io.BytesIO()
tpl_body.save(target_stream)
target_stream.seek(0)
sd = tpl.new_subdoc(target_stream)

context = {
    'mysubdoc': sd,
}
tpl.render(context)
tpl.save('output/subdoc.docx')

**Comment by RDNATOS** [comment]
> A sub-document is not a template, it is a python-docx object : you can use only what this package provides (see this package documentation), you have an example in tests/subdoc.py. There is no render() method. You cannot do some partial rendering with docxtpl, you can only render the final "big" document with all the aggregated context values.

The only problem is that docxtpl even if it has Python-Docx type for its subdocuments, you can't give style to tables, for exemple. That's a shame
