### ISSUE TITLE
QUESTION - mail merge or combining multiple entry and putting all templates all in one doc

### ISSUE THREAD

**Issue by sebsenechal** [elapouya/python-docx-template#306]
Is there a way to "mail merge" the template? 

I know that there is another package specific to mail-merge (docx-mailmerge), but it as somehow lot less options when filling the template. The mail-merge has a "merge_templates" function where you can pass your dictionary with a separator (ie. page break).

**Comment by elapouya** [comment]
I am not sure what a "mail-merge" is. I guess it uses template functionality from MS Word.
In python-docx-template a simple docx IS the template : you just have to use Jinja2 tags within a normal document.
About mailing, python-docx-template does not mail anything, but you can use python `email` standard module for that.

**Comment by sebsenechal** [comment]
Bonjour Eric, 
thanks for getting back. And thanks for this wonderful package by the way.

By mail-merge, I was referring to Word Mail-Merge (or you can check https://pypi.org/project/docx-mailmerge/ or better explained here https://pbpython.com/python-word-template.html), which basically mean taking a template, but filling it in loop, all in the same doc. Quick example would be a DF with 5 row of data, and a one-pager template. You end up with a 5 pages word doc, each of the page have one record from the DF (obviously for that package, that also mean that each row of the DF are converted to a dictio).

I know it can be done a bit manually by filling the template, combining the results with the template and iterate the operation.
