### ISSUE TITLE
Inserting Data to multiple tables

### ISSUE THREAD

**Issue by umutaltun13** [elapouya/python-docx-template#308]
Hi,

Firstly, thanks for this great template.

So, I want to add values regarding jinja variables for multiple tables. I read that I need to define special syntax but I could not succeed it . Can you give me syntax example, to fill 2 tables in word ?

![image](https://user-images.githubusercontent.com/70034033/95151876-71290500-0794-11eb-9a97-26dca40562d9.png)

**Comment by elapouya** [comment]
You have in the source code in directory tests/ many examples that I suggest to see.
