### ISSUE TITLE
inline_image test no longer works

### ISSUE THREAD

**Issue by jamesstidard** [elapouya/python-docx-template#313]
Hi,

I've been having troubles getting images to template into documents. I cloned the repo and tried running the `tests/inline_image.py` test file. This produced a file that opens in libreoffice with no images templated, and produces an error when trying to open it in Microsoft Word.

My python environment is from the `Pipfiles` in the docx-template project (using `python==3.6.12`:

```console
docxtpl==0.10.4
  - jinja2 [required: Any, installed: 2.11.1]
    - MarkupSafe [required: >=0.23, installed: 1.1.1]
  - lxml [required: Any, installed: 4.5.0]
  - python-docx [required: Any, installed: 0.8.10]
    - lxml [required: >=2.3.2, installed: 4.5.0]
  - six [required: Any, installed: 1.14.0]
```

Here's the error that Word produces on opening the document: 

![telegram-cloud-photo-size-4-5782855598285632517-x](https://user-images.githubusercontent.com/1797906/96114920-2159e480-0ede-11eb-92a0-8cae7cefb7c2.jpg)

and the final output document itself:

[inline_image.docx](https://github.com/elapouya/python-docx-template/files/5384292/inline_image.docx)

**Comment by b4bay** [comment]
Same issue with 0.10.3. Build 0.10.0 works well.

**Comment by elapouya** [comment]
PR #307 and #312 corrupted XML code : I reverted changes to the equivalent of 0.10.2 (now 0.10.5)
