### ISSUE TITLE
creating dynamic Table of Contents

### ISSUE THREAD

**Issue by sachin141** [elapouya/python-docx-template#317]
I want to create dynamic table of content with page no. in docx file.
I had added TOC in template file which takes values from Heading tag on every page, for it I need to define static parameters in TOC for every page. 

Suppose I have 20 pages doc file and I had added 5 parameters in TOC , it will show only 5 pages heading in TOC, how can I automatically update it using python docx?

Thanks

**Comment by elapouya** [comment]
It is not possible, sorry.

**Comment by paulpechey-ow** [comment]
Is there any plan to support the ability to add a ToC? It would be incredibly valuable

**Comment by elapouya** [comment]
Well, if somebody does know how to trigger an automatic ToC refresh on document opening, it could be a solution. But as docxtpl is not MS World, it does not know how to render pages thus cannot know on which page are located chapters...
