### ISSUE TITLE
Subdocument adds an extra empty paragraph?

### ISSUE THREAD

**Issue by cristianocca** [elapouya/python-docx-template#318]
I have the following python code that creates a new sub document and a paragraph. It will also include pictures but I've removed all of that for simplicity:

![image](https://user-images.githubusercontent.com/8573267/96916740-5934cf00-147e-11eb-98ba-2a6c8b8d34fd.png)

Also the following template code:
![image](https://user-images.githubusercontent.com/8573267/96916805-723d8000-147e-11eb-9e00-a059d22d27f8.png)

I would expect that `{{ res }}` does not add any additional white space, however, I get this extra paragraph at the end:

![image](https://user-images.githubusercontent.com/8573267/96916881-8b463100-147e-11eb-8f13-8155f86ca719.png)

Where is this extra empty paragraph getting added from? How can I remove it?

Thanks for the amazing library!

**Comment by elapouya** [comment]
Please use {{p res }} 
(note the 'p')
see tests/templates/subdoc_tpl.docx

**Comment by cristianocca** [comment]
That works, however, if I do that, I lose the text alignment of the doc and I need to set it from code (`current_p.alignment = 0`). Also, the text in bold was in the same paragraph, with this, they will be in two separate paragraphs. Not a big deal, but it works!

Any alternative to achieve the same? Have both text and photos in a variable and being able to use it in the template afterwards? A subdoc seemed like the most intuitive way but perhaps I overlooked something.

Thanks!
