### ISSUE TITLE
Page number or context for errors

### ISSUE THREAD

**Issue by jamesstidard** [elapouya/python-docx-template#319]
Hi,

I've been using this library to template some pretty large documents. I found finding and fixing syntax errors and undefined variables quiet time consuming and a little trail and error.

I was wondering if it's possible to give more context around errors like the following.

![telegram-cloud-photo-size-4-5805554453200352933-x](https://user-images.githubusercontent.com/1797906/96990171-a9fc0480-151e-11eb-81b4-1cf4ed08b8c4.jpg)

Is it possible to include the page number and/or the entire snippet of python code where these kind of error occur (i.e. everything within the `{{ <python snippet here> }}`)?

Thanks.

**Comment by elapouya** [comment]
Actually, this is not possible, sorry.
