### ISSUE TITLE
Dynamically adding sections(headings & paragraphs) while keeping style or Copying styles

### ISSUE THREAD

**Issue by sssseossss** [elapouya/python-docx-template#32]
Hello,
Is there anyway I could dynamically add sections (headers and paragraphs) while keeping their stylings - colours, fonts, alignment etc.
Or I could copy the stylings and add new paragraphs myself - please direct me howto.
Example picture below:

![issue](https://cloud.githubusercontent.com/assets/16890918/14176737/64bdcd1e-f74a-11e5-934d-d5cb986ec08d.png)

Many thanks!

**Comment by elapouya** [comment]
Something like that in the template:

{%p for issue in issues %}

3.1 Issue No{{issue.id}}    <--- put the style you want in the template

{{issue.desccription }}     <--- put the style you want in the template

Recommendation           <--- put the style you want in the template

{{issue.recommendation }}     <--- put the style you want in the template

{%p endfor %}


2016-03-31 15:11 GMT+02:00 sssseossss <notifications@github.com>:

**Comment by sssseossss** [comment]
Thank you! Works great
