### ISSUE TITLE
XML Injection through Jinja Tag

### ISSUE THREAD

**Issue by quentingaeschlin** [elapouya/python-docx-template#321]
I would like to know if we could consider injecting xml in a jinja tag in our template. 

I have a case where a section of our document comes from another word docx document section. Including text, images, tables, lists etc... The easiest way we found to"extract" all that data from that source word docx is through xml. 

We would like to be able to use a jinja tag to inject that xml in our template directly, there and then, without having to bother about headers etc. 

Is this a scenario you considered / tested?

**Comment by elapouya** [comment]
Actually, it is already the case for basic XML : ensure autoescape is set to False, then you can put your XML code in a variable.
you have to know how a docx is coded as XML. Use {{ myvar }} to insert into a text, {{r myvar}} to replace current run and {{p myvar}} to replace current paragraph with your XML code.
The big problem comes with ressources like images : there is no way to directly modify the generated docx for that. In addition you have to deal with styles that comes from the docx you want to extract and the styles from the template that are different.
I think there are even more to extract from one docx to put it in the generated docx. All these are in different places making this very hard to work properly. This is why subdoc feature in docxtpl is quite limited : there are so much to consider to merge 2 docx.
So to summary : include basic XML is already possible, to "extract" all that data from another word docx with styles, images and so on is not possible and won't be the case in the future with docxtpl.
