### ISSUE TITLE
Adding a list of images in InlineImage

### ISSUE THREAD

**Issue by pipemsn1** [elapouya/python-docx-template#322]
Hello , I've got a list of images in Folder , I'd like to insert in my template with a for loop
here are my code but it shown ERROR "TypeError: 'InlineImage' object is not iterable"
![2020-11-01_041753](https://user-images.githubusercontent.com/15522512/97790280-e05e1180-1bf9-11eb-8ff2-04d105e8d806.png)

This is my template 
![2020-11-01_041856](https://user-images.githubusercontent.com/15522512/97790341-69754880-1bfa-11eb-9a97-7e708c9e2f0f.png)

Is it possible to use list of images with InlineImage

**Comment by elapouya** [comment]
it is NOT possible to use list of file paths with InlineImage() but you can use a list of InlineImage with 1 file path each

try : `chart = [ InlineImage(report, f, width=Pt(500)) for f in glob.glob("*.png") ]`
