### ISSUE TITLE
some html code missing < >

### ISSUE THREAD

**Issue by the-404** [elapouya/python-docx-template#323]
when I use 0.11.1,I try insert  htmlcode to docx.I found some html tag like '<div>' '<body>' missing <> 
But,when I use 0.10.5 '< >' can show me.

<img width="669" alt="截屏2020-11-02 下午4 23 04" src="https://user-images.githubusercontent.com/5340063/97845585-b440ae80-1d27-11eb-9046-533cd1d27f97.png">

**Comment by elapouya** [comment]
rendered HTML is not supported in docx. If you just want to display HTML as simple text, do not forget to escape it (see doc)

**Comment by the-404** [comment]
> rendered HTML is not supported in docx. If you just want to display HTML as simple text, do not forget to escape it (see doc)

I want display html code in docx. And I escape it but in the docx some html tag missing '<' '>' . I try use version  0.10.5 .The html as simple text can be displayed . But on version 0.11.1 The html tag's <> missing
`  tpl = DocxTemplate(template)
    tpl.render(content,autoescape=True)
    tpl.save('xxxx.docx')   `
content is some http respond

**Comment by elapouya** [comment]
In version 0.11.1, the test `escape_auto.py` works properly : the text `<unicode>` is correctly displayed in the generated docx `escape_auto.docx`.
Could you provide a complete test case (.py and template.docx) so I can reproduce your problem ?

**Comment by the-404** [comment]
> In version 0.11.1, the test `escape_auto.py` works properly : the text `<unicode>` is correctly displayed in the generated docx `escape_auto.docx`.
> Could you provide a complete test case (.py and template.docx) so I can reproduce your problem ?
`#coding:utf-8

xxx = {}
from docxtpl import DocxTemplate
with open ('./123.txt') as f:
    xxx['html'] = f.read()
tpl = DocxTemplate('template/test.docx')
tpl.render(xxx,autoescape=True)
tpl.save('xxxx.docx')   
`
[123.txt](https://github.com/elapouya/python-docx-template/files/5507929/123.txt)

[test.docx](https://github.com/elapouya/python-docx-template/files/5507934/test.docx)

**Comment by elapouya** [comment]
Fixed in 0.11.2
