### ISSUE TITLE
Header disappear if "for" variable is not used

### ISSUE THREAD

**Issue by Jala015** [elapouya/python-docx-template#327]
I have a _for_ loop inside an _if_ on the docx template:
```
A
{%p if lalala is defined %}
{% for item in lalala %}
{{item.name}}
{% endfor %}
{% endif %}
D
```

and the following context:
```
context = {
    'lalala':[
        {'name':'B'},
        {'name':'C'}
    ]
}
```

When _lalala_ is defined, everything renders correctly, but when is missing, a lot of errors occur: "D" is not rendered and the page header disappear. The code works if I define 'lalala' as a simple variable, but when is a list the errors occur.

**Comment by elapouya** [comment]
Try `{%p endif %}`

**Comment by Jala015** [comment]
It worked! Thank you and sorry for the inconvenience. I thought it was a bug...
