### ISSUE TITLE
Broken output when using a PNG InlineImage and a certain header content

### ISSUE THREAD

**Issue by DennyWeinberg** [elapouya/python-docx-template#328]
I have a docx with a certain header, which adds a line OUTSIDE of the header.
The template itself works find, but when I try to render a PNG image (InlineImage) in the body, it gets broken.

![image](https://user-images.githubusercontent.com/7354954/99976502-ce5c3280-2da3-11eb-93ee-45fe6809e1e5.png)

Test Script:

```
from ls_docxtpl import DocxTemplate

def test_image_from_pil_barcode(docx, barcode):
    from docxtpl import InlineImage
    from docx.shared import Cm
    import code128
    import io

    pil_image = code128.image(barcode, height=100, thickness=3)

    byte_arr = io.BytesIO()
    pil_image.save(byte_arr, format='PNG')
    # byte_arr = byte_arr.getvalue()

    return InlineImage(docx, byte_arr, width=Cm(4.5) , height=Cm(1.5))

docx = DocxTemplate(r"C:\Users\dwe\Downloads\isolated.docx")
docx.render({'docx': docx, 'barcode': 'ABC', 'test_image_from_pil_barcode': test_image_from_pil_barcode})
docx.save(r"C:\Users\dwe\Downloads\isolated_out.docx")

```

Template (can be opened)
[isolated.docx](https://github.com/elapouya/python-docx-template/files/5583762/isolated.docx)

Output (can be opened with a message from MS Word and can be recovered)
[isolated_out.docx](https://github.com/elapouya/python-docx-template/files/5583761/isolated_out.docx)

It would be nice to analyze why it gets broken.
Thanks

**Comment by elapouya** [comment]
Generated document is readable on Libreoffice and MSWord (Office365 Web version) wihtout any error :

![Sélection_113](https://user-images.githubusercontent.com/888300/100580654-a2323b80-32e6-11eb-868a-763d9bba6eba.png)

I do not own other MSWord version to make some tests...

**Comment by DennyWeinberg** [comment]
Here is the error/warning:
![image](https://user-images.githubusercontent.com/7354954/100581721-71eb9c80-32e8-11eb-8061-46886a480b09.png)
