### ISSUE TITLE
its possible to turn bold a specific part of my variable?

### ISSUE THREAD

**Issue by luizaugpires** [elapouya/python-docx-template#332]
So my {{ variable }} in the word doc is made up of person's name and persons data like adress, id, etc.  I put everything in the same variable because the user has the possibility to add more persons (name  + data), idk if there's a clever way of doing this. But i need that all names added are in bold and the data is not. Its possible to turn bold a specific part of my {{ variable }}? Or any solution for this problem?

```
from docxtpl import DocxTemplate

grantor = ('')

while True:
 add_grantor = str(input('Add a person [Y/N]:'))
    if add_grantor == 'Y':
        # user_input
        name = str(input('name: '))
        id = str(input('id: '))
        adress = str(input('adress: '))
        grantor = f'{grantor}{name.upper()}, ID {id}, {adress}.'
    else:
        break

doc = DocxTemplate('files/index.docx')
context = {'grantordoc': grantor}
doc.render(context)
doc.save('files/test.docx')
```

**Comment by elapouya** [comment]
It is possible : see RichText in documentation
