### ISSUE TITLE
Replacing multiple pictures/medias within one document doesn't do anything

### ISSUE THREAD

**Issue by JonasMArnold** [elapouya/python-docx-template#333]
Consider the following part of a python script:

```
from docxtpl import DocxTemplate

tpl = DocxTemplate('template.docx')
tpl.replace_media('dummies/dummy1.png', 'pics/pic1.png')
tpl.save('out.docx')
```

Replacing the picture that way works perfectly fine! Now suppose someone wants to replace multiple pictures with different one's - you obviously could try to use `tpl.replace_media() `multiple times, though this doesn't work.
A bypass to this is using a temporary file, i.e. (yes, you could write that within a function, considering it's pretty repetitive and you might have to replace more than two pictures!)

```
tpl = DocxTemplate('template.docx')
tpl.replace_media('dummies/dummy1.png', 'pics/pic1.png')
tpl.save('temp.docx')
tpl = DocxTemplate('temp.docx')
tpl.replace_media('dummies/dummy2.png', 'pics/pic2.png')
tpl.save('out.docx')
```

It works smoothly in most of the files! Though - and I can't tell why - there are a few exceptions, for example this one _(attached as template_example.docx)_. In my opinion, the usage of `replace_media()` is very inconsistent - sometimes a replacement, which has worked hundreds of times before, stops functioning properly! And in the case of the file attached it doesn't work at all.

What can cause these discrepancies? Moreover, what could I do to fix the issue with the example .docx I attached? _(**NOTE**: The sudoku are just placeholders, I'm not the owner of the pictures - the original pictures are still named dummies)_

**Attachements:**
[template_example.docx](https://github.com/elapouya/python-docx-template/files/5798005/template_example.docx)

**Comment by JonasMArnold** [comment]
By the way, after converting the` .docx `to `.zip`, I took a look at `\word\media` and found the four images as expected. Odd thing is, even though I specifically know where the pictures are saved and I used them in the document they aren't called "dummy[x].png", no the files are called "image[x].png".

I guess that due to formatting (?) the image files might have been renamed to the standard - being "image". I further tried to rename the original picture to, e.g. "image1.png" and replace it from there, but it didn't work! 

Keep in mind that's just an observation I made, not the solution as the problem still occurs and I'm not able to replace the files. Another odd thing is that if in fact the images would have been renamed, why doesn't it throw an error...? Therefore the theory might be wrong alltogether.

**Comment by Oremiro** [comment]
Hi, i have the same issue, but probably i've found the way, where you can dig.

In the same unzip directory you have document.xml - it seems, that modern versions of word are renaming all pictures in some sequence, which looks like "Picture 1", "Picture 2".

It's worked for me:

`doc.replace_pic('Picture 1', f'{my_path}/generated/some_picture_stuff.png')`

I still don't understand the correct mechanism of the renaming, but there is at least where to start an investigation of issue

**Comment by JonasMArnold** [comment]
@Oremiro Thanks a lot for your help! Odd thing is that it actually works in another document with the same pictures (same Word version, etc.), therefore I don't think that this is the actual reason - in fact, I tried with "image1.png" and wasn't able to replace them either. But may you elaborate what you meant with `document.xml`?

**Comment by Oremiro** [comment]
In my case, when i unzip my template.docx, it creates these directories and files.

![image](https://user-images.githubusercontent.com/55203583/104244321-3c9fa600-5473-11eb-8569-0d8bd96aaf6b.png)

Here, you can see this path "/word/document.xml".

In this file, i've searched some "Picture" mentions:

![image](https://user-images.githubusercontent.com/55203583/104244503-956f3e80-5473-11eb-9476-a3be176b82cb.png)

I didn't find any mentions of "*.png" in this file, but replacement with "Picture" worked for me.

**Comment by JonasMArnold** [comment]
@Oremiro Correct! I unzipped it as well and found the images like "image[x].png" in the media folder. The `document.xml` has some mentions (I used a beautiful formatter for easier reading purposes) about "Picture 1", "Picture 2", etc., though you can't replace a picture by `tpl.replace_media('Picture 1', 'test.png')` as Picture 1 is not a valid file? You'd need to use `picture1.png`, which doesn't work?
Or am I missing something with the naming?

**Comment by Oremiro** [comment]
@JonasMArnold, sorry, i have no idea, why replace_media() is not working, it's also doesn't work for me as well)

**Comment by Oremiro** [comment]
@JonasMArnold, probably i've found another solution for replace_media();

After unzipping docx, i've used path to files in these way and this worked.

`my_path = os.path.dirname(__file__)
 doc.replace_media(f'{my_path}/word/media/image1.png', f'{my_path}/generated/some_generated_image.png')`

my script and unzipped files are in the same directory. Maybe your code working in directory "A" and not working in directory "B", because you don't have files, which related to document, inside directory "B"?

**Comment by JonasMArnold** [comment]
Just to close this issue - @Oremiro provided helpful insights and his method, described above my closing comment, is a good approach to tackle the problem!

In my case, I found out that in some formatted documents you experience a bug (?) which blocks the `replace_media()` or `replace_pic()` methods. What solved the issue were reading the **names** of each picture in the `document.xml` and using them with `replace_pic()`. For `replace_media()` you shall use the filename - which can get problematic, according to my experiences!
