### ISSUE TITLE
Error in replacing mathematical expression

### ISSUE THREAD

**Issue by 1019157263** [elapouya/python-docx-template#334]
# Template fragment:
```
已知输入功率{{\ \mathrm{who\ }}}3=3.16kw，小齿轮转速310r/min，

```
## Word automatically recognizes braces as its built-in properties, and cannot place braces correctly
# code snippet
```python
from docxtpl import DocxTemplate
import os

class Documentcreater:
    def __init__(self,tem_name="test.docx"):
        self.father_path = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
        self.file_name = tem_name
        self.temp = DocxTemplate(self.father_path + f"\\temp\\{self.file_name}")
    def reader(self,context={'who': '默认'}):
        self.temp.render(context)
    def output(self,file_name=""):
        if file_name=="":
            file_name=f"output_{self.file_name}"
        self.temp.save(self.father_path + f"\\output\\doc\\{file_name}")


if (__name__ == "__main__"):
    Doc=Documentcreater("圆柱斜齿轮设计.docx")
    context = {
        'who': 'test'
    }
    Doc.reader(context)
    Doc.output()
```
# An error occurred
```
Traceback (most recent call last):
  File "F:/CurriculumDesign/doc/Document.py", line 22, in <module>
    Doc.reader(context)
  File "F:/CurriculumDesign/doc/Document.py", line 10, in reader
    self.temp.render(context)
  File "F:\CurriculumDesign\venv\lib\site-packages\docxtpl\__init__.py", line 310, in render
    xml_src = self.build_xml(context, jinja_env)
  File "F:\CurriculumDesign\venv\lib\site-packages\docxtpl\__init__.py", line 269, in build_xml
    xml = self.render_xml(xml, context, jinja_env)
  File "F:\CurriculumDesign\venv\lib\site-packages\docxtpl\__init__.py", line 224, in render_xml
    raise exc
  File "F:\CurriculumDesign\venv\lib\site-packages\docxtpl\__init__.py", line 217, in render_xml
    template = Template(src_xml)
  File "F:\CurriculumDesign\venv\lib\site-packages\jinja2\environment.py", line 1031, in __new__
    return env.from_string(source, template_class=cls)
  File "F:\CurriculumDesign\venv\lib\site-packages\jinja2\environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "F:\CurriculumDesign\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "F:\CurriculumDesign\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "F:\CurriculumDesign\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '<'
```

**Comment by elapouya** [comment]
I do not know this syntax : `{{\ \mathrm{who\ }}}` why backslashing space ? could you provide a minimal *.docx template and the docx expected for result

**Comment by elapouya** [comment]
... and what is `mathrm` ? it does not seems to be Jinja2 standard function. May be it is better to process the value at python side...
or declare this function in context...

**Comment by 1019157263** [comment]
> ... and what is `mathrm` ? it does not seems to be Jinja2 standard function. May be it is better to process the value at python side...
> or declare this function in context...

Hello, this is the mathematical formula in word. I copy it to get the mark above. The mathematical formula in word also uses braces. It seems that this has caused a mistake
Backslash space is the space in the mathematical formula of word. The formula source code of word will be changed into backslash space

There are many bugs in the application of mathematical formula template in word

OK, I'll provide a file later

**Comment by 1019157263** [comment]
> ... and what is `mathrm` ? it does not seems to be Jinja2 standard function. May be it is better to process the value at python side...
> or declare this function in context...
### Template:


[main.docx](https://github.com/elapouya/python-docx-template/files/5839692/main.docx)
### Expected :
[out_e.docx](https://github.com/elapouya/python-docx-template/files/5839704/out_e.docx)


### python code
```python
from docxtpl import DocxTemplate

doc = DocxTemplate("main.docx")
context = {
    'num1' : "1236" ,
    'num2' :  "456",
    'num3' :  "456",
    'num5' :  "456",
    'N1X' : 256,
    'N2X' : 258,
            }
doc.render(context)
doc.save("out.docx")
```
### error:
```
  File "F:/CurriculumDesign/doc/doctemp/main.py", line 12, in <module>
    doc.render(context)
  File "F:\CurriculumDesign\venv\lib\site-packages\docxtpl\__init__.py", line 310, in render
    xml_src = self.build_xml(context, jinja_env)
  File "F:\CurriculumDesign\venv\lib\site-packages\docxtpl\__init__.py", line 269, in build_xml
    xml = self.render_xml(xml, context, jinja_env)
  File "F:\CurriculumDesign\venv\lib\site-packages\docxtpl\__init__.py", line 224, in render_xml
    raise exc
  File "F:\CurriculumDesign\venv\lib\site-packages\docxtpl\__init__.py", line 217, in render_xml
    template = Template(src_xml)
  File "F:\CurriculumDesign\venv\lib\site-packages\jinja2\environment.py", line 1031, in __new__
    return env.from_string(source, template_class=cls)
  File "F:\CurriculumDesign\venv\lib\site-packages\jinja2\environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "F:\CurriculumDesign\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "F:\CurriculumDesign\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "F:\CurriculumDesign\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '<'
```

**Comment by 1019157263** [comment]
> ... and what is `mathrm` ? it does not seems to be Jinja2 standard function. May be it is better to process the value at python side...
> or declare this function in context...

Its bugs won't even be reported in detail. If you have already written a large template, it's hard for you to locate where the template is wrong, which makes me confused

**Comment by 1019157263** [comment]
## This is the *. Docx file I provided. 
![image](https://user-images.githubusercontent.com/31230637/105117878-44f98000-5b08-11eb-841f-bf9cfa6bdf33.png)

## I copied it to get some
```
P2={{\ num1\ }}kw

d1t\geq2.923(ZEσH)^{{num3}}KT1*{{ num5 }}φR(1-{{ num2 }}φR)^2•u

N2=\frac{{{N1X}}\times10^8}{4}={{N2X}}\times10^8

```
## It seems that the error occurred in Num3

**Comment by 1019157263** [comment]
> ... and what is `mathrm` ? it does not seems to be Jinja2 standard function. May be it is better to process the value at python side...
> or declare this function in context...
Hello, did you receive it? If you have any ideas, please let me know. I would be very grateful.

**Comment by elapouya** [comment]
On my side, when looking with LibreOffice your template, it seems that first openning brace for num3 is not next to the second one : Could you try without {{ num3 }} : sometime, MSWorld adds some hidden character that makes Jinja2 unhappy.

**Comment by 1019157263** [comment]
> On my side, when looking with LibreOffice your template, it seems that first openning brace for num3 is not next to the second one : Could you try without {{ num3 }} : sometime, MSWorld adds some hidden character that makes Jinja2 unhappy.
Thank you for your answer. I'll try again

**Comment by Mill7** [comment]
> > On my side, when looking with LibreOffice your template, it seems that first openning brace for num3 is not next to the second one : Could you try without {{ num3 }} : sometime, MSWorld adds some hidden character that makes Jinja2 unhappy.
> > Thank you for your answer. I'll try again

Hi, I have  the same issue, "unexpected '<'".
Did you, by any chance, find what makes it work or not ? #

**Comment by elapouya** [comment]
I looked carefully the out_e.docx provided by "1019157263" : I cannot see "2.92" number or "KT1" string which are in the mathematical expression in any of xml files of the docx file. This means the mathematical expression is encoded in a way that docxtpl cannot modify (I only change strings in xml files).
So for me, modifying mathematical expression is not and will not be supported. Sorry.

**Comment by elapouya** [comment]
May be I was a little too quick, I found this post : see #406

**Comment by LuberLinder** [comment]
I use LibreOffice instead of Word and solved it by wrapping variables such as num1 into double quotes with brackets without spaces, like that: "{{num1}}".

So, try to change your code from:
P2={{\ num1\ }}kw

d1t\geq2.923(ZEσH)^{{num3}}KT1*{{ num5 }}φR(1-{{ num2 }}φR)^2•u

N2=\frac{{{N1X}}\times10^8}{4}={{N2X}}\times10^8

**Comment by Mill7** [comment]
> I use LibreOffice instead of Word and solved it by wrapping variables such as `num1` into double quotes with brackets without spaces, like that: `"{{num1}}"`.
> 
> So, try to change your code from:
> 
> ```
> P2={{\ num1\ }}kw
> d1t\geq2.923(ZEσH)^{{num3}}KT1*{{ num5 }}φR(1-{{ num2 }}φR)^2•u
> N2=\frac{{{N1X}}\times10^8}{4}={{N2X}}\times10^8
> ```
> 
> to:
> 
> ```
> P2="{{num1}}" kw
> d1t\geq2.923(ZEσH)^"{{num3}}"KT1*"{{num5}}"φR(1-"{{num2}}"φR)^2•u
> N2=\frac{"{{N1X}}"\times10^8}{4}="{{N2X}}"\times10^8
> ```
> 
> in LibreOffice it will looks like:
> 
> ```
> P2= "{{num1}}" kw
> d1t ≥ 2.92 nroot {3} {( {ZE} over {left [σH right ] } )^ "{{num3}}" {KT1 *"{{num5}}"} over {φR(1 - "{{num2}}" φR)^2 • u} }
> N2= {"{{N1X}}" × 10^8} over {4} = "{{N2X}}" × 10^8
> ```
> 
> Python code remains the same:
> 
> ```python
> from docxtpl import DocxTemplate
> 
> doc = DocxTemplate("main.docx")
> context = {
>     'num1': "1236",
>     'num2': "456",
>     'num3': "456",
>     'num5': "456",
>     'N1X': 256,
>     'N2X': 258,
> }
> doc.render(context)
> doc.save("out.docx")
> ```

Hi,
That looks like a nice way of dealing with this issue.
However, it would be easier if it was possible to wrap a Python variable directly in the Word Equation zone, as it would enable more flexibility and also consistence with the elements to be mandatorily put in the Equation.
But I did pretty similarly to you to move forward.
