### ISSUE TITLE
Question : replace_embedded() not working ?  

### ISSUE THREAD

**Issue by Puji01** [elapouya/python-docx-template#336]
My document contains screenshot section , in this section I need to embed the document which contains the Screenshots

So in the template i put a document dummy one (the one shown in SS) , which is to be replaced by the document which actually contains screenshots 

But when i use the function tpl.replace_embedded('doc_in_template.docx', 'doc_i_want.docx') in the code it is not getting replaced.

<img width="370" alt="SS" src="https://user-images.githubusercontent.com/62922868/106865138-c8ae9180-66f0-11eb-948c-803397fcc145.PNG">

![image](https://user-images.githubusercontent.com/62922868/106865796-ab2df780-66f1-11eb-8cd1-5d9ba6cf724c.png)

this is the one in the template file (which i am using to generate the other word docs)

both the files are present in the working directory

When the doc is generated the one in the template remains not getting replace

Please do help !! Thanks @elapouya

**Comment by elapouya** [comment]
Test is working, so please provide a test case.

**Comment by Puji01** [comment]
Please find the updated description

**Comment by elapouya** [comment]
Please provide full running test case with .docx  and .py

**Comment by lxj361** [comment]
[embedded_embedded_docx_tpl.docx](https://github.com/elapouya/python-docx-template/files/5995398/embedded_embedded_docx_tpl.docx)
when‘run’ the embeded.py file,error wairing as :
docx.opc.exceptions.PackageNotFoundError: Package not found at 'templates\embedded_embedded_docx_tpl.docx'

**Comment by lxj361** [comment]
from docxtpl import DocxTemplate
tpl=DocxTemplate(r'C:\Users\Inya\Documents\demo.docx')
tpl.replace_embedded(r'test.docx',r'C:\Users\Inya\Documents\1212.docx')
tpl.save(r'C:\Users\Inya\Documents\demo1.docx')
[Uploading 1212.docx…]()

**Comment by lxj361** [comment]
replace_embedded still wasn't working, someone konw the solution?
