### ISSUE TITLE
Saving, on Azure Databricks

### ISSUE THREAD

**Issue by luis-at-gea** [elapouya/python-docx-template#337]
When saving the file, using an azure databricks path, it's failing not recognizing the file/path structure, though, when reading the template from the same path, a different name, seems to work.

Any ideas?

```
tpl = DocxTemplate('/dbfs/templates/report.docx')
tpl.render(context)
tpl.save('/dbfs/reports/final.docx')
```

**Comment by elapouya** [comment]
Path must point to a Unix-like filesystem : is that the case ? If not, you should consider work one a local filesystem then copy generated file to azure
