### ISSUE TITLE
Nest {%tr} inside {%tc}

### ISSUE THREAD

**Issue by JonesKenzie** [elapouya/python-docx-template#339]
Can we nest {%tr ...} insde {%tc ...} ?  Apparently it doesn't work... any suggestions on how to tackle this ?

```   
{"products": [
  {
  "name" : "A",
  "loads": {
                "installation_cases": [
                    {
                        "loads": {
                            "bending_moment": 495000000,
                            "tension": 5224500,
                            "hydrostatic_pressure": 21.1
                        }
                    },
                    {
                        "loads": {
                            "bending_moment": 100,
                            "tension": 2200,
                            "shear": 0,
                            "hydrostatic_pressure": 21.1
                        }
                    }
                ]
                }
                }]
                }
```
<table class="waffle" cellspacin g="0" cellpadding="0"><thead><tr><th class="row-header freezebar-origin-ltr"></th><th id="0C0" style="width:100px;" class="column-headers-background">A</th><th id="0C1" style="width:100px;" class="column-headers-background">B</th><th id="0C2" style="width:100px;" class="column-headers-background">C</th><th id="0C3" style="width:100px;" class="column-headers-background">D</th><th id="0C4" style="width:348px;" class="column-headers-background">E</th></tr></thead><tbody><tr style="height: 20px"><th id="0R0" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">1</div></th><td class="s0" dir="ltr" colspan="2">Installation Cases</td><td class="s0 softmerge" dir="ltr"><div class="softmerge-inner" style="width:97px;left:-1px">{%tc for case in product.loads.installation_cases %}</div></td><td class="s0 softmerge" dir="ltr"><div class="softmerge-inner" style="width:97px;left:-1px">{{loop.index}}</div></td><td class="s0" dir="ltr">{%tc endfor%}</td></tr><tr style="height: 20px"><th id="0R1" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">2</div></th><td class="s1" dir="ltr" rowspan="3">Design Load</td><td class="s1"></td><td class="s1" dir="ltr" rowspan="3">{%tc for case in product.loads.installation_cases %}</td><td class="s1 softmerge" dir="ltr"><div class="softmerge-inner" style="width:97px;left:-1px">{%tr for _,load in case.loads.items() %}</div></td><td class="s1" dir="ltr" rowspan="3">{%tc endfor%}</td></tr><tr style="height: 20px"><th id="0R2" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">3</div></th><td class="s1"></td><td class="s1" dir="ltr">{{load}}</td></tr><tr style="height: 20px"><th id="0R3" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">4</div></th><td class="s1"></td><td class="s1" dir="ltr">{%tr endfor %}</td></tr></tbody></table>

**Comment by elapouya** [comment]
{%tr ...} inside {%tc ...} means you have a secondary table inside a primary table which is not your case in your template.
