### ISSUE TITLE
updating TOC

### ISSUE THREAD

**Issue by sssseossss** [elapouya/python-docx-template#34]
Hi!
is there any way to update Table of Contents when  the file is generated from template?

Thank you!

**Comment by elapouya** [comment]
No, but if you find a way tell me so...

**Comment by yywing** [comment]
There maybe something useful about TOC.
https://www.youtube.com/embed/BG8p3Pb7lh4?feature=oembed

**Comment by yywing** [comment]
I used the method in video, but you have to open it . And the TOC will be update. But i found libreoffice. 
https://ask.libreoffice.org/en/question/46586/how-to-automatically-update-indices-in-headless-mode/
