### ISSUE TITLE
Header and footer not displayed if loop in document

### ISSUE THREAD

**Issue by fdegrave** [elapouya/python-docx-template#341]
When a document contains a loop, the header and footer disappear. I tested it with `python-docx-template/tests/templates/header_footer_entities_tpl.docx` that I modified to include a loop. The result is the well-generated document, but without header nor footer.
[test_header_footer_loop.docx](https://github.com/elapouya/python-docx-template/files/6136765/test_header_footer_loop.docx)
[result.docx](https://github.com/elapouya/python-docx-template/files/6136767/result.docx)

**Comment by elapouya** [comment]
Could you try without the '-' in `{% ... %}`

**Comment by Tockos** [comment]
Same problem here. I didn't use the embedded loop, instead, I merged a subdocument, but the header wasn't present in the result.

**Comment by elapouya** [comment]
Please, open another issue and join a fully runable test
