### ISSUE TITLE
Cannot change cell background

### ISSUE THREAD

**Issue by cayox** [elapouya/python-docx-template#342]
Cannot change the cell background in a dynamic table

tried with a simple block like: `{% cellbg 008000 %}{{ row[“name”] }}`

The output is just a not colored cell.

I am using Word Version 2008 (Build 13127.21216) and docxtpl 0.11.3

Any ideas ?

**Comment by elapouya** [comment]
Try color with double quote : `{% cellbg "008000" %}` or use a variable containing the color

**Comment by cayox** [comment]
Ok that worked! Looking back it makes total sense to put it into a string. Thanks!
