### ISSUE TITLE
Got 'Unspecified error' when I use shapes inside the loop

### ISSUE THREAD

**Issue by wafi543** [elapouya/python-docx-template#345]
This issue always happens, I tried every scenario and got this error. But the results sounds good after recovering.
Do any one know why this issue occurs?

![docxtpl-issue](https://user-images.githubusercontent.com/41089137/114305726-217c1b00-9ae2-11eb-94e0-c4abc3559e22.png)

**Steps:**
- create new docx file.
- write a loop using jinja tag, and put any shape.
```
{%p for number in [1,2,3,4] %}
insert any shape here
{%p endfor %}
```
![code](https://user-images.githubusercontent.com/41089137/114306280-1cb86680-9ae4-11eb-9785-1c84a53abc01.png)

**Results:**
![result](https://user-images.githubusercontent.com/41089137/114306233-fd213e00-9ae3-11eb-8474-d76675c2d60a.png)

I tried using this template file:
[template.docx](https://github.com/elapouya/python-docx-template/files/6291887/template.docx)

**Comment by wafi543** [comment]
After I troubleshooted it I found that child element `<wp:docPr id="3" name="Rectangle 3" />` inside shape element must be unique 'id', the issue occurs because of duplicate ids of that element inside document.
`15: <wp:docPr id="3" name="Rectangle 3" />`
`79: <wp:docPr id="3" name="Rectangle 3" />`
`143: <wp:docPr id="3" name="Rectangle 3" />`
`207: <wp:docPr id="3" name="Rectangle 3" />`

so I opened docx files and go to `word/document.xml` and search for that element and found duplicated ids created by loop.
so I changed the ids to unique id for every element, then it works fine without error.
`15: <wp:docPr id="3" name="Rectangle 3" />`
`79: <wp:docPr id="4" name="Rectangle 3" />`
`143: <wp:docPr id="5" name="Rectangle 3" />`
`207: <wp:docPr id="6" name="Rectangle 3" />`

[result-after.docx](https://github.com/elapouya/python-docx-template/files/6317314/result-after.docx)
[result-before.docx](https://github.com/elapouya/python-docx-template/files/6317315/result-before.docx)

So how can I do it in python? should be updated from this repository? or should I do it in my code after rendering template?

**Comment by kdebrab** [comment]
This looks related with #243 and #225. I'd propose to give [this workaround](https://github.com/elapouya/python-docx-template/issues/243#issuecomment-578517618) a try.
