### ISSUE TITLE
From version 0.11.0 (2020-10-19), page break function will add some lines in new page.

### ISSUE THREAD

**Issue by Sinnetech-sg** [elapouya/python-docx-template#346]
My old pc using version 0.10.5, the 'page break' function always normal, new page will begain from the first line.
but those days, I'm using new mac mini(m1 cpu), so I install all the pip package  with newerst version, inclusing python-docx-templae, when I run my program, I found there are always add some blank lines infront of new page.
So I tested escape.py, same problem happened in my new pc.  I try to run same escape.py in my old pc, 'page break' function back to normal, the new page new paragrah will begain from first line(on my old pc). Then I change my new pc docxtpl version to 0.10.5 same as my old pc. I found the problem gone. After that, I tested all the new versions 0.11.x they all got same problem. Please help !
Thanks

**Comment by Sinnetech-sg** [comment]
![image](https://user-images.githubusercontent.com/52275145/114986087-22d48b80-9ec6-11eb-9758-265608858942.png)
This is generated by 0.11.4 version, you can see some blank lines before the paragraph.
![image](https://user-images.githubusercontent.com/52275145/114986306-6fb86200-9ec6-11eb-8236-f4ee604e37e1.png)
This is generated by 0.10.5, you can see there is no blank lines before the paragraph.

**Comment by elapouya** [comment]
Tested with v0.16.0 : docxtpl works as expected. Closing.

Note : escape.py / escape_tpl.docx test is coded in a way there are some lines after page-break. I will add a text to show the beginning of page in next version.
