### ISSUE TITLE
htmltodocx

### ISSUE THREAD

**Issue by Mustard404** [elapouya/python-docx-template#348]
i want add html code to word，or copy a.docx to demo.docx
<p>test1</p><p>test2</p><p><img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANcAAAEcCAYAAABUJSF2AAAgAElEQVR4Ae2c/VfUSL7GOffe3VFsQEBFZUBUZMV3BlHwZUCncViEi8IKo73CKLOOI+jd8QyuesdlZhSJnvzP3z3fSiqppPPS6U510vr8kJMmqVRVnno+9VTSrU1NhS7CBg3gAQ0egKgaRMWEhQmbPQC4ABc8oMkDEFaTsEgvpBfgAlzwgCYPQFhNwiK5kFyAC3DBA5o8AGE1CYvkQnIBLsAFD2jyAITVJCySC8mVNVxtlxdp750N2re4QW1XFjEggPLT8UCWcO25uU57n5q075np7Dtn1z8dcQHK5z2WWcHVOb1Oe9ZM2iu3dZP28vbUpI7Ztc97UADlpzH+WcDV+dd12vPYdLefTNrD2xOT9v/wUQDXcfOnT0NggPL5jmO94eqcWqfOR6a7/WhS548m7fvhI/Xc3abDf3tHfXe2qLe0TbunH3++AwMoG3/s6wlXx4116lg1qXPVtPY/mNT5g0l7lrfowPU1OrzAYL2jvqUtOvTdFh26+55av77b+CIDlM9zDOsFV8fkOrU/MKlDbg9N6nhoUufSb47w+658T32LWxZcd9/ToXvv6dDft2nXiQmnTL36i3bwFUXNHqi5ggpm5fbiOu1eNp2t/XuTdn9vUuedzTJo9l79nvq+ey9Si8Hqvb9NvSsGNQ9+XVa2Hn1HG4Csag9UfWEFUHHd7d+sU9vfTdott/sm7b5vUsf8v0Nh2Tv+gA6VtqmX4Vo2qPd7g3oefKA/954NvUb3faB+QJbYA4kvqBAqrnf3tXVqu2u6W8mktpJJHbfexEKy59oD6r1viNTqffCBeh4a1FH8PvY6nfeDugFYIg8kKpwErIl1al00qXXJ3r4zqfU7/g4rHizZpz3XH1qp9fAD9ax+oObT1wBXgjGQOmKf0aSgQ/i28XVq+ZtJLXesjSFrWTSp4+avieFoGb5Je2fXqeX8zcTX6rg31JmRURtxUknbLG1fr1Nh3qQWuS2Y1LJgUvvU/6cGx2hPP80PnKD9e3pSqzNtHdKtb4xuP98i0zTp7fMSDTai0T7HPqdpgrYr61SYM6lwy95um1S4bVL7t69Tg+BSdz99GL5AxvkL9OHCRTrXfSS1uoO06L6+TI9f/E5vDVOYmw0uNmOLNv+5TEN1Mc0ybch2zVe0WJc2kVBBfkh0LFHhiEFtvbJOu2ZN2vW/3m33ZHpgcV+NM+fJODtCxtAIGcMX6MPIRRrpOaoBsAEa/+l3L1COwW3A3j2j8QhN0tK2qTBGiy8M0RfjxTKSqy6apzC5pGGA1svr1DxjCric/axJu4vxYA19eZRuHz9FC4On6VLfAO1oOxAJysTBfjJOnbcgOzdCxlcj9OH8BRrr6Y+8Lul99t99RYaE6eMWbaw9ottTEzR0aYKGpkpU+nGDNn99Uie4UhjoRjHkp9TPpKbzlxdg3TSpmbcZd9tdjH7G2tPeTesnh8g4P0bGyBgZFy+RMXqJ/n1hlAYOHA4F5b8KXbTcd4KMk+fJOO1Nsau9x0Kv8/c77u/Fl3IZaNDT2YHU6o1rF+c/oYmklsFsvbROzdM2WHJ/06S2b+LfCq4PnLGWd2cvkDF00dqGR8k4P0pbI6PU0d4daugdLfvph76TZJwYtlNshAyRYhfo2qF0AHPh+p1WL1U44ANTtLj2ijbfWUs4+Xz29t8bVLp+2r6fESq9luCG1L2w4SxHN38sUlNhhh6/i1iK9k7Q1OqGt92PBnG7K7MT1OFLg/E16+WIaW7R48kxml17Q8ZHrn+LHl+v8F59ddbio0/22mpvrHDuLjX/1bTgYrDsre16PFjn9vaRMThsbZxAvMw7PULGGYaEYbtA033HQ+HiPre2HqC1wyftOmzIzp4Xz2IXumt/Bis+cwExXj6kod5407lASnjU/RY9vmElYEfplQvPP8p/Nzn7i7zuDa2c4XYj4Bou0c8SPLmM9e03f5rxAKbC9fMv6nMlwxZ/n9V65rO7rtobbp14Rc1TJu2cMsWeP7dOvo0EQrY1d7Cfto+dJWPgnLUdHyLj+FdWEtlpxMkmy4ft97QdpJ+PnLKuZVjtZ7Gngyn8TGp4mTbUN4TG7/Tz/Rnqj4Bs8aVBm88fUnFYptQADS08p7fS7K8fUj/P+L3K279fH1nHnCRYoKfvbbhk+VC4irT6mwTRpM3ny1S8MEIdA2N0ee4JvXb6b9DPC+7S1oXLunZzbSHyvsL0x/GYiahagVqvbtDOb01q/ta09gxXsTK4bu8/QsaRk2QcPUVG/2ky+s+QIWH7yzkyjg/R/x2VBo2+gUeHBl1AGbATw/So/1QsmJXcd8fEI8Wgton55cb9Kep2YHD71z0Q1OcBdxn4/jlNiesG6LaSTiWRTnY9s8+dFykbJQlEcHJ13HGXj2/XvOkk7u/KE9r0g13oIg9cvz7C28eAsazEH7FlYguENLzr1CLtvGGKTQB2wwKt9Vr8z5sudvbQdu9xMg4N0nbfIBmHT9A2L/GOnqLtoxZs893xz053OAEZ0GNnrCT8CyfgEH3VFf5CJPH9iueZV/RWPJO4KWH+9pxmh12wZL0dp2bo9v0n9PTFK3r9h0GGkx58rfsdlQqGC1EXOcvRjxt020nJYLim/imXriHPboURWvlV9tltW4VLbVveA/bl41qVJlVdZAPXOrruACZB430cYH8udNGrA0dpu/sYbfcM0HYvb8dp+9BxMvoGafvwCerZHf5Cg/s813WYtvmtoQ2lTL/igdqftwI16R2h8fsbtKnC8sczGncAGKPZZ+rzi21qw7BfFnjhaios0c8S2F9K9jORAtEvS0r6KseV79acZ7yPGzQbMgm6IAXBhWeswLEO0TJx2cQX+BpuubhOOydN71YBYEfbDtBv+w/T9oEjtH2QQeun7S8ZtmPEyRbVr6m9hwSUxiEG0k6+IyepuD/FxPLdp9Of3hl6/IdMA5Ner4yIvvYrLynevnhEU9fHnKWjA4GSXFyfkzwSjsln9vOZQU9vqrNnDFzOclO9xvoMuMo1ccYybIzTOp5GQwKwokk7eVNAi0uwtpYuutHeTY/39ND63l661dlDX7ZGf4k81tFtwShA5MT7i0i84r6+SCDTuE+nDhWktRlqKgQ9V8lBDV6aibqc5yv+Lk15FlLSyWozGK7yt4qyTblX2pYAe565kFzOmKYFlFpPWpV7AJOgFU1qqeAZLEkf/rXvUFnaFfccShmsGVp5/oSKA9Kk3v3gqrv84xcJ0a/KH9Fr+VLBl1xNhTnnzaDxz2XnzZ/13ZbaZjBc6iv92BcaztJTgVh8z6W2g89JvBhbNraASmLMZwHYdZN28vaNvQnAwv/VcdL273BydfXRtr2kLMYsIZPWb5WXZjZo88UzKs1NOT97Wnn2xnmbZ30Jy4YcIHfpZ9DG/aJYEnaMLdFTZQmpvtCQ/XJeYPyxZS8Jg15OyP6YZHpSTV2iGrS5VqLL/DVA7whd8LyK9yaUu1T0Hpd9wj6lSSZtIVv4Jcd1k3bYkMl9y7V0AGtv6aKp9oNU6vyShncfTDmxpKiKmZ3UcZ+zrF9eGLT5D/f1d8fChgKdUvaPZ/TY+UWG+1LB0d15zrKvcb7bkn3hvdIfD1xd1OT/Pq6svwZtlMY8OgEuVVuNn51BjkmlJOUKo09pxzXTu103qXA9OWDNl1apMPWOeJ+kD7WW7b6yQCvPrJ8yWT8NssxvvN8Sabbo/JxJDg5/YfyMXiu/lnj78ol4Xe+mWgBcBe8XwfIFibf/EXDxuNk/u/L8sxj+JzEvntDsmPyuTPYTy0Kvtq4uqR9PvUIbUgHYhEk7eFNASwJY4camtbyUz3AXl+sKmC5tUK9GQ6cYEjWPU80VRNxMYeypBZeEzN5XAhiDJZeU8hmuUHwFuCL01jmWqLuKCUG3aAKwcZN2qNtE9BKxMLnpSTv5DPen/iuAC3A1jgd0w8X17+IE+9q0NgWyXQHPYLuKm960s5eUO8/faxxRAQDGij1QD7gcwK6a9MVVCzK533Xd/V93BVgKfOJ5bcKknRfwrFWvcUI7VSz/wibTeorZfOmZgIvBktuOqyY1f7NFzcUtBzyRcjZkOy8+wCwYNng4nm9v1BMubksAdsWkL5SNAeO/xZ6TzYZv59gP+RYP5sb4RHmg3nA5gF026Qt1U2Bj0HaO/YiBixo4nMu/P7KAywPYJR9kl01qvvQk/8LB3BijOA9kBRe3u/PyM/qC4VK2nZefYtDiBg3nG8MjWcLFbe/4qkTN47+KbcdwqTFEg7kxTpV4IGu40H6Kr34rGXCUqd/EAHPD3PCAJg9AWE3CIiHqlxB51RpwAS54QJMHIKwmYfM6m6Jf9UtUwAW44AFNHoCwmoRFQtQvIfKqNeACXPCAJg9AWE3C5nU2Rb/ql6iAC3DBA5o8AGE1CYuEqF9C5FVrwAW44AFNHoCwmoTN62yKftUvUQEX4IIHNHkAwmoSFglRv4TIq9aAC3DBA5o8AGE1CZvX2RT9ql+iAi7ABQ9o8gCE1SQsEqJ+CZFXrQEX4IIHNHkAwmoSNq+zKfpVv0QFXIALHtDkAQirSVgkRP0SIq9aAy7ABQ9o8gCE1SRsXmdT9Kt+idoyZxI2aAAPpO+BJoiavqjQFJqyBwAXkhsrF00eAFyahEV6Ib0AF+BCcmnyAODSJCySC8kFuAAXkkuTBwCXJmGRXEguwAW4kFyaPAC4NAmL5EJyAS7AheTS5AHApUlYJBeSC3ABLiSXJg8ALk3CIrmQXIALcCG5NHkAcGkSFsmF5AJcgAvJpckDnwRca4ZJpmlSKUYkLvfuTYIZ9YlJ70yT1p7EXFNpuZj+cdqV3ppkGibdUMqKY29j+qCUR2rmQ6ua4PrXH5ap2dhJN742DRPceONtOwqEesL1shJNAoDh6/wTAOBKxytp+C1JHTXBxUDNPDXp9HKyja/ha5N0NLDshlXPyw2rLmFCJWkEeEoKqHAFmZ/rkSkYNVnI9pw+BSQX119WTkkXtS+yHjlR+CcIwJWCVxTtpd6696nAlbSTqcBlG9r0zf7SoGzsKLjUPgugFAidc5VCU2k5ZYCDEioI+CjIxbmgfivtOPeCY7VP5gk11AaXTLOgwa0ZrhCwnLbsRFvjJaNivqC0kGnHz2vyc6yh7SXfa34+Clj+Mdie5JL9Vcsq/eJ+y7aDnhuRXEguz8yw/sYk3hzDK9TXBJcNjj+xgtqJSy6Zcv5lmFNXpYlUaTlFA6cNPmZfH7aMBFzBPvJoGKZthse1JZcuuG5smPTOMOml/YYwKDkkeJFw+Z7X5EDV65lLtlfJHnABLk9K6YJLmjFoicfn1ONRcMllmApnWXJUmkgyeexlIidhRc9P9tKworLqkjLgc9ByUmqFfTZwpppcDJRqVvWzukSsaVlox7wKkWoe9XgUXOo1cllWtjwMgMtzHfdFLlN9r9DlM1dY6vBx/yv3srozXNKgL7UDmSpc6oDkPbmk+UWfbUB49q8oRew3lA44ARA69St1O/oElHfOASjPCqiRdfm04JLLM/t7r6jkEudsSPzlnAGtFIKAcg5cvqUq1+1A6QNJHA9Y8qkrAM9n3xtHp9++enG89hSqRsPGh0tZlgnjKd97+aFRl4zqUlAeT2Juz5IuBi65dHS+ewv5qVYYdEED67+3oDI4lg1UUndtcGn9nisgDeQNqXu/ASVEsowKU+ALgQBo5LWefUA5Nbm4rOiLnUplz3Z20gCubGHwjGkK6a8NrqiO6nyhwe2GmdQPF5cVz1hhy6sAaALvK6CcHy4VZPlVgb+usH77y/Hf/okjqAyOZQtrKnDJlKp0rxuuIIjYaP7jwsy+78wCEyxuFouCSy5bleWqAFr5DaSEAHBlC4Mch7T2NcGV5a/iQ41oG73sOysfXHKZpi7RGD7PC4OYlwtrm0p5BR4eHAkQ1xcIbAB04p5i2vT0Lyxx4yYDnK/LG8ma4EqL8KrqsSHymE0aUxpdGlgeV4zO5lfBqqoPKZs0dMIIaAfLwvynXOPCFWC4PACCPuTf9PUaI8AFSOuyRKqXofPUDuACXIBLkwcAlyZh8zSDoi/ZLFUBF+BCcmnyAODSJCzSIpu0yJPugAtwIbk0eQBwaRI2TzMo+pJNigIuwIXk0uQBwKVJWKRFNmmRJ90BF+BCcmnyAODSJGyeZlD0JZsUBVyAC8mlyQOAS5OwSIts0iJPugMuwIXk0uQBwKVJ2DzNoOhLNina1FToImzQAB7Q4AGIqkFUTFiYsNkDgAtwwQOaPABhNQmL9EJ6AS7ABQ9o8gCE1SQskgvJBbgAFzygyQMQVpOwSC4kF+ACXPCAJg9AWE3CIrmQXIALcMEDmjwAYTUJi+RCcgEuwAUPaPIAhNUkLJILyQW4ABc8oMkDEFaTsEguJBfgAlzwgCYPQFhNwiK5kFyAC3DBA5o8AGE1CYvkQnIBLsAFD2jyAITVJCySC8kFuAAXPKDJAxBWk7BILiQX4AJc8IAmD0BYTcIiuZBcgAtwwQOaPFCLsL3Hz1Fx+lbija+rvt0xKt5bpZnxGgUZX6LSyjIVh2qsp6qEsu5hcXosXoehOVrMrJ9ZaPMJtVm9ybvozMhVKq2sij1/rmRjGLlc1e0OTVJxflm0W5qfpKbCJM2srFp/V7IX11gDODpvXSdMLmCrvJ5E1yhtWvcNuKoe/6oms4yAreUmJVxJ6qgZLimugGGJRm24KkkyAZPf6LIeuZf1h+7DwQis367He85bx+C0PVlUMjkElKkoAUPvJyPjfQ79SQKGv6wKV1ffCYrb+PrU4HIGp/rk8txPzXBZ/QiDPAouTz+c+7JNj2Vh9ascv5b1/jtyYGM6o8LFn6Oev/i8TrjCTK3en9fgvhlbwiXMHL48XJyeFM98/rSw0oeT1Fev/be3bW9yqX0s+wy4AFeZKUJMVmtyCRPfm6NBp/7oxAjul2VuD5ASLqfeYEiaCkFgWMf4+dO/SQij4Qq/3l9f2d8eLcL6jOPBPtCsSy2N+pOL/1a3oLprhmtozn6BId/0JVwWMgD3HtCNcX4Lx59tUGuBK/BaL/TRcEUMMpILyaVCJT/rgEvWKcwqwGATS9BUkwYljHqeP9uJwS85VEDE5/IUst5O+uu1IJIJJftn1ef2C3D5tf8M/nbMELscKheDIeJlSlQd/9N2kDp7Bqhl/2FRTr70iLom0Tk5s8skCliaeZdSruE97ZTB5X1+cuHwwlW+TLV0cssH/a3WUUXylt2jt6+e+6piXHF9uder0qSqi+wBi4Nr4OxFur14z3kOuVqcjgSxqr544FLBUQ1siyXLBn1xXA1cSn0CJmH6JRq1k099pvPCFtC3AAjkS5KZ+VUqS8aA8lXph3rS96TUtJYBiYLryMlhAdW1b2dFavGvMr6dmae/zi2kcDPK84ww+BKNSqOLBOOZ3DUwG1uYU5Zx4FLqqQIurlcFyFlmMmS+79OSwmWBZU8W8h7loIm9dX/+dmoZT1ybUmLJcapF0Ci4Ll6dpIWlv3tA6j52RgBX6LKWiFW3rULCUPCzV9mxJZq55874AoRp30+JBFC2gauAK6j/AqKV8mVaErgssLzgimM2sFYbNsBDY8qb05TNIU2CvcfHQeMeeCzwYIViRsE1PnmTxiZueDpV2Ncn4OLnrlralcsl/k7JMa0Kl+i/m1xOW74yop6gt4UCtEpfaLiGlqb3ppl13ulnWN/EcfX5S13ich12UnEqyj5XOE7O/aN8Tb5LrGPiC5QBioJLnuOXGdzGf7ceoMGhMSu59vXVdJOuURWAJDjTdpI5y0LrS19heFlGLAt9y6qY5HJ1Utp0tHCNHwSWe60EsbwOCaZY5nn6Ka9RAANcNfmnfDxUjVP8XEtDEqCwOkbHbwiYbt66Qwvf3Ref795/QPwGMeya+OPW7C6eodRlnWJIawk1p/ySgq9ZpqJ4HlOfY5SllwqXA02Q0D4wRLuccv6kCbpWHlPrsNNKBUa5F6GHnaTypYaV3OXPdfHayfaxr4tWtTQi4fK+6l4VP4OS9R44eopOfHWJDvafEkBdHJ+k24sl6vjyWHWAOUDZaSFfHPgN6SSX8s86FIAsgypAKOdk34P3Khi+PkRBaQPialX+XOa05wBrL03lPfrrd+pU7sNfBn9X57M0dHMGtMrK5PdW/n1UvWdGrlC1/6bLWj7x28FJmrmnmCoCLmfJtSJfcNhQqGkRAZeTFM73SxFgVKmjqpfVnt421PbwWVOSQ1hNwqYAGcamwccGA9jgAwiIs1v2xWkPuAAXPKDJAxBWk7BxsxrO5zdx0hobwAW44AFNHoCwmoRNa/ZDPY2bcIALcMEDmjwAYTUJi8Rp3MRJa+wAF+CCBzR5AMJqEjat2Q/1NG4CAi7ABQ9o8gCE1SQsEqdxEyetsQNcgAse0OQBCKtJ2LRmP9TTuAkIuAAXPKDJAxBWk7BInMZNnLTGDnABLnhAkwcgrCZh05r9UE/jJiDgAlzwgCYPQFhNwiJxGjdx0ho7wAW44AFNHoCwmoRNa/ZDPY2bgIALcMEDmjwAYTUJi8Rp3MRJa+wAF+CCBzR5AMJqEjat2Q/1NG4CAi7ABQ9o8gCE1SQsEqdxEyetsQNcgAse0OQBCKtJ2LRmP9TTuAkIuAAXPKDJAxBWk7BInMZNnLTGDnABLnhAkwcgrCZh05r9UE/jJiDgAlzwgCYPQFhNwiJxGjdx0ho7wAW44AFNHoCwmoRNa/ZDPY2bgIALcMEDmjwAYTUJi8Rp3MRJa+wAF+CCBzR5AMJqEjat2Q/1NG4CfvZwjS9RaWWZikNBkE3SzMoSjcLgjWvwLMcubbgK+/ro1p27VFpZFRt/5mNptxNb39AcLdp9kH3h/cy4F6LR+VUq3ZujwaBBkHXMT9a//0H9wbHGGodYkyYc0J6BswKqIyeHiTc2NB9LtR2RNha8KjjezxUkjg2PHzi1r4PTyxHJxqCOUfFeObRNBU69sD6W901AHlo+rJ6IiSHhuKn3jM/eCbhqPaq+0B689u5j9Kf2bgFPV98Jmr51hxbvLTsw8Wc+xue4LS7L19Tabvn1lsnDl3jlgnlTS14fYWTV/DLthiapOM8ArtLi9JhyXwxXwHJTTAwhcKkJWVbO6p/ahgBf9gMwKdqXj3W5X+pQppZGGRiZFgwQf568ecuTVJxafIzPyTL8WcJWS/vOtXHLNzaq34RxqWWfV83stBdkZD8M4vqEcKnwVvrZf19BfcOxbMCLNEzMoPDzFINz/Nyo2PMyMKw+PqeW5WvDyiY67je1p8/u0mxxfo5GlZcWQanlgmRfpyaJgKU8ccL66q1fmSUj+6uUk/cRBqk8j306PtKhY5g54o7L5yn/Eo9fXoxN3BBLQ14S8mf/Cw2+htMrCsa49uWzDtcTvQUAIQzuPidZz1WynL08LEsE+7gKXOCAuMvL4Gc5F3jR7/l74pkt+h6quMfAvgXAi3L64Iw3cfCAMCAMD28SMH6ekmnGyz7eOK14OSify+R1XE5el7wProHZlB4T28s5Pu4mke8elDLS1LIO68WCBM13nQ2lrNeCUhrfuib+BYivzjhzI7n0mT9O+1rPJze2aw4Ghs15ZuSqEICTiGGTIHHd/JmPyZTisnyNWqaWPqjXOmZXUodhkeCoZa3P3jRyro9NQ9+zVNKlXsigVd6+DbRyn+X35o4TzmWkRa3Cq3AxOJxU/jr5mARQwuUvU9vfMsn8iTNGo4Fv8myxGYpAg1r1yYRq8sEj0k1dHgadjwM0oF0BV8DxIG2SlA26HsfqAFwtIvuTi5d5DJu63PMfk3ClllwVLJuspd4qlVQgxPdQvgRyEsWCy0k8HzxlmpWd98Hp1MsDGvCyxD6P5KqD4T1jobm9MqNU2DhD43/m4rr4BQYDNj55U2z8mY/JdsKuk+cr38u0ks88Fe7tZHCAUxLGgckGwPm7DB7foASdF8fK4bUA8iesVV+SNEpStnJNffdVoRdQf4hu1QoT9raQ6+PvtjiheAv6dYZMM/kclrwPPPuXG1fUE5VkbPh7SzQ6JN/YVVhHEDyq8QLP2/CryzxRLvwZEMkVYlJV60b6nNzYrgD8xq84bX3PxfsoWPicWjat77k4gZxnIxbeA5cFked80ODYppfLRpFqZVAoaSPaUP5W4GJAnMSTS0Cuy24jqi9J0ihJ2VrGGNe6fk+sReILFHPKX2jw8lD++oIBUtOKP/MxXh5yGS7rfy6rrg9yWbhExSHlZ0cqXENjNCj+DvoNnkwv37OYgMCXaAo8oq+Bf7vLUg9Asn3/VwaKjvL+kVw1GDlAT6lrZvtaG+YlnqyDYZMAyWMSPD7Hx/hFhnqNLJdob6eATBrPtSpciuDyGUukih8Ou5w0t5s89mD7yvtTQ9Zd8v3zFFkfH5/hX9/z852aiEr/+B789Xruq4ayUfXgnEag0xaXk4pNxD+J4o0/q0lWc3vC6N5kcU1sG9jzVlARL+Baqz8Bz0ceM8uUDEon63W/m1ZKIpY9F6rn7GWlkmwCPuUFS5K/yyYET/8VDXDcCYOavRinZdoN5Obfc8XduIbzDuRhcCttOmlXQdm0xwj11WmygdB1EloBC5p/JppjoD+TgQbc9VsOSq0BF+CCBzR5AMJqElbOXtjXPzHyojngAlzwgCYPQFhNwuZl9kQ/sktOwAW44AFNHoCwmoRFYmSXGHnRHnABLnhAkwcgrCZh8zJ7oh/ZJSjgAlzwgCYPQFhNwiIxskuMvGgPuAAXPKDJAxBWk7B5mT3Rj+wSFHABLnhAkwcgrCZhkRjZJUZetAdcgAse0OQBCKtJ2LzMnuhHdgkKuAAXPKDJAxBWk7BIjOwSIy/aAy7ABQ9o8gCE1SRsXmZP9CO7BAVcgAse0OQBCKtJWCRGdomRF+0BF+CCBzR5AMJqEjYvsyf6kV2CAi7ABQ9o8gCE1SQsEiO7xMiL9oALcMEDmjwAYTUJm5fZE/3ILkEBF+CCBzR5AJ60m2MAAADpSURBVMJqEhaJkV1i5EV7wAW44AFNHoCwmoTNy+yJfmSXoIALcMEDmjwAYTUJi8TILjHyoj3gAlzwgCYPQFhNwuZl9kQ/sktQwAW44AFNHoCwmoRFYmSXGHnRHnABLnhAkwcgrCZh8zJ7oh/ZJSjgAlzwgCYPQFhNwiIxskuMvGgPuAAXPKDJAxBWk7B5mT3Rj+wSFHABLnhAkwcgrCZhkRjZJUZetAdcgAse0OQBCKtJ2LzMnuhHdgkKuAAXPKDJAxBWk7BIjOwSIy/aAy7ABQ9o8gCE1SRsXmZP9CO7BAVcgAse0OOB/wBqDHxzjfBKOAAAAABJRU5ErkJggg==\"></p>

**Comment by the-404** [comment]
应该实现不了,我遇到过如果带有注释符的代码(例如： <!-- ) 会导致 生成word时候 后面的内容都被注释掉，怀疑是jinja2的问题。

**Comment by Mustard404** [comment]
> 应该实现不了,我遇到过如果带有注释符的代码(例如： <!-- ) 会导致 生成word时候 后面的内容都被注释掉，怀疑是jinja2的问题。

我项目中应该没有这种情况，目前考虑两种方案，但是都有问题。
1.将html通过docx转成word文档，但是不知道怎么把html转的文档复制到现有文档中。
2.就是写过滤器，把html代码直接解析成正常文档，不知道这么过滤器怎么写。

**Comment by elapouya** [comment]
If you want to add html code as a listing of code : juste use escaping (see doc)
If you want to add a **rendered** html code, it is not possible
