### ISSUE TITLE
problem with template path - Compiling exe with pyinstall 

### ISSUE THREAD

**Issue by sssseossss** [elapouya/python-docx-template#35]
Hi!
I'm trying to compile the program into exe with pyinstall.
When I run the program, I get the error that default.docx is not found. I understand that program cannot find my template file and tries to load default template, which is not included into exe. How can i resolve the path to my template problem? At the moment i use such path in the program: tpl=DocxTemplate('c:/QAT/bin/template.docx')

Many thanks!!!

Error is below:

Traceback (most recent call last):
  File "<string>", line 1344, in <module>
  File "<string>", line 952, in menu
  File "<string>", line 1291, in generate_report
  File "site-packages\docxtpl\__init__.py", line 116, in new_subdoc
  File "site-packages\docxtpl\__init__.py", line 123, in __init__
  File "site-packages\docx\api.py", line 25, in Document
  File "site-packages\docx\opc\package.py", line 116, in open
  File "site-packages\docx\opc\pkgreader.py", line 32, in from_file
  File "site-packages\docx\opc\phys_pkg.py", line 31, in __new__
docx.opc.exceptions.PackageNotFoundError: Package not found at 'C:\Users\sp\AppData\Local\Temp\_MEI48882\docx\templates\default.docx'

**Comment by elapouya** [comment]
I think it is a problem with pyinstall and docx packages : please contact
them.

2016-04-06 13:36 GMT+02:00 sssseossss <notifications@github.com>:

**Comment by sssseossss** [comment]
Thank you elapouya for such a great support.
You are right and wrong saying that it's the issue with docx.
In my template I'm using the subdoc. whith command: picture=tpl.new_subdoc()

If I comment this out - I get no errors after compiling. The issue is that new subdoc uses default.docx template within docx.
Workaround would be if you can tell me how to open subdoc file instead of using that template.
Many thanks!

**Comment by elapouya** [comment]
What works without pyinstall and does not with means there are some missconfigurations between docx and pyinstall (that I do not know at all). I am sorry, but I cannot help.

**Comment by sssseossss** [comment]
Do you know how to open subdoc instead of new_subdoc?

**Comment by elapouya** [comment]
I do not understand

**Comment by sssseossss** [comment]
Sorry for my bad question.
Just wanted to ask, how can i use the subdocument (add already existing document as a subdocument) instead of creating new subdocument with command: tpl.new_subdoc()
thanks!

**Comment by elapouya** [comment]
This not possible actually.
