### ISSUE TITLE
trying to follow dynamic_table example for non tabular content

### ISSUE THREAD

**Issue by abubelinha** [elapouya/python-docx-template#356]
@elapouya 
I try to find an example of a pretty common task: producing many similar paragraphs with a common structure/style, filling their text contents from a datasource, and putting them alltogether in the same document. But not in a table format.
Example text, a list of address labels, so we can print many labels per page.
Or a letter which we are sending to many different people (so we produce a document with many pages, one for each person).

Is there any example that I could adapt for doing this? 
I couldn't identify any one by their names, but I guess there should be something similar.

I tried to follow the dyanmic_table example, but how to adapt `{%tc for col in item.cols %} ... {{ col }} ... {% endfor %}` so I can access each column by its **name** when I need it in my letter or label?
I mean, something more like `{{% item.cols.vegetable %}}`

Guess I need a different datasource format, but I wonder if you already have examples of this.

Thanks a lot in advance

**Comment by elapouya** [comment]
It sounds quite easy : just use a list of data in your context like this : 

```
context = {'datasource':[{'my_custom_paragraph':'blabla'}, {'my_custom_paragraph':'hello'},...]. 
```

Then in docx template, use 

```
{%p for data in datasource %} 
{{data.my_custom_paragraph}} 
{%p endfor %} 
```

No need to create a table if not needed. you can also use for-loops inside for-loops : Have a look to `nested_for` example
