### ISSUE TITLE
Strings with Newlines

### ISSUE THREAD

**Issue by MrLeeh** [elapouya/python-docx-template#36]
Great project,

I couldn' t find a way to pass Strings including newline characters (\n or \r) to the template. The newline characters just got replaced by spaces in the output document.

```python
doc = DocxTemplate('mytemplate')
context = {
    'body': 'some text with\nnewline characters\nThx
}
doc.render(context)
doc.save("generated_doc.docx")
```
In my word template I' m using simple JINJA2 tags like {{ body }}.
Am I doing something wrong?
Greetings

**Comment by elapouya** [comment]
see tests/richtext.py AND do not forget to use {{r body}} (with a 'r')

**Comment by DennyWeinberg** [comment]
I have a better solution: use <w:br/> instead of /r or /n or both.
r not needed! No richtext needed.

**Comment by DennyWeinberg** [comment]
<w:br/>

**Comment by DennyWeinberg** [comment]
< w:br/ >

**Comment by DennyWeinberg** [comment]
Without blank. Github is removing this Charakter... Sorry

**Comment by abubelinha** [comment]
Can @elapouya or anyone else confirm that `<w:br/>` trick works?
Or can @DennyWeinberg share some working example code?
It is not working: I just see that `<w:br/>` string (and not a line break) introduced within the merged field value.
Of course using ReachText works perfectly, but if there is an easier trick it would simplify some common use cases.

Thanks a lot for this great project
