### ISSUE TITLE
How to use a variable number of variables

### ISSUE THREAD

**Issue by SunHaozhe** [elapouya/python-docx-template#364]
Instead of declaring a fixed number of variables `{{blabla}}` in the docx template, how can we use a variable number of variables?

**Comment by elapouya** [comment]
You can declare inside  the context dict a dict or an object, so you have free to use any keys or attributes without to declare more variables : thus `{{obj.blabla1}}` or ... `{{obj.blablaN}}` requires only `obj` to be in the context
