### ISSUE TITLE
Image disappears after the document is created, updated, and saved.

### ISSUE THREAD

**Issue by srutherfordbta** [elapouya/python-docx-template#371]
## Describe the bug
Use docxtpl to create a document with multiple images. Make some changes in the document. Save document. Close document. Open document again to see that an inserted image has disappeared.

## To Reproduce
https://github.com/srutherfordbta/docxtpl_multi_image_test/tree/master
docxtpl_multi_image_test.py included which creates a document with two images based on images_template.docx and saves the document as images_before.docx. The images_before.docx is then opened with the docx library and has a footer inserted into it. It is then saved as images_after.docx. Open the document and notice one of the images is missing. This was tested in a Windows 10 environment with python 3.7 and 2.7.

## Expected behavior
I expect the images to stay in the document regardless of changes made to the document that do not include deleting the images.

## Screenshots
See .docx files

## Additional context
Looks like a few other issues have been created around image problems recently, but no code has been provided on them. I hope this helps.  I have not noticed the issue until recently so maybe a recent update to Word is causing some grief.

Thanks for all your work on docxtpl Eric, it is a fantastic library.

**Comment by elapouya** [comment]
When unzipping the 'before' docx, I can see that word relations file seem to have unique IDs what was a problem in the past :

```
cat word/_rels/document.xml.rels


<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXml" Target="../customXml/item1.xml"/><Relationship Id="rId6" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="theme/theme1.xml"/><Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings" Target="webSettings.xml"/><Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image1.png"/><Relationship Id="rId8" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image2.png"/></Relationships>
```
The docx seems to be correct and I can view it properly with context images put in-place.

For the second part or the script, python-docx is used, not python-docx-template.
The 'after' docx is displayed correctly for me on MacOs with 'Pages' that can read .docx files
Even with multiple re-opening, images are still there
`word/_rels/document.xml.rels` looks the same except there is a new ID for the added footer.
Images IDs are the same. 

I am sorry, but I cannot see why the modified docx is not properly displayed on MS Word. You should contact python-docx project to have more help about this issue.

**Comment by srutherfordbta** [comment]
Thanks for looking at this Eric. I will keep an eye on issue #372 which seems to have the same issue, but they are using pure docx-template to reproduce the issue.

**Comment by srutherfordbta** [comment]
Adding a note about my Word and Windows version since you don't have the issue in the "after" docx in your version.
Word - Version 2106 (Build 14131.20332 Click-to-Run)
Windows Windows 10 Pro (Version 10.0.19041 Build 10941)

**Comment by srutherfordbta** [comment]
Closing this issue as we will continue work out of #372. It has a pure docxtpl example as opposed to mine with a docxtpl/docx hybrid example.
