### ISSUE TITLE
How to use template in footnotes

### ISSUE THREAD

**Issue by huahmj** [elapouya/python-docx-template#379]
## Describe your problem
I want to use template in footnotes, but it not work

## More details about your problem
There are footnotes in my DOCX document, and I need to replace the text in the footnotes with templates.  I added a footnote like {{var}}, but the final render docX does not replace var correctly, just shows {{var}} in the footnote

**Comment by elapouya** [comment]
Please provide a fully runnable example

**Comment by staffanm** [comment]
I have the same problem. This is my code:

```python
from docxtpl import DocxTemplate
doc = DocxTemplate("footnote.docx")
context = { 'what' : "Apples" }
doc.render(context)
doc.save("out.docx")
``` 

The result is a word document where `{{what}}` has been substituted in the main body text. but not in the footnote.

The footnote.docx template I'm using is available at https://github.com/staffanm/staffanm.github.io/raw/master/footnote.docx

**Comment by elapouya** [comment]
I confirm, footnotes is not supported :  adding request for enhancement label...

**Comment by jayvynl** [comment]
I've encountered a similar issue, but my requirements are more challenging. I need to dynamically generate footnote entries and dynamically generate footnote references.
