### ISSUE TITLE
[User Help] replace a picture?

### ISSUE THREAD

**Issue by metadirective** [elapouya/python-docx-template#39]
I have a docx, I can modify all texts elements with python-docx-template but there's a also a picture in the docx header.
I also have a logo.png next to my Python script. 
Is it possible to replace the docx picture ? 
If so how ? (Do I delete it in my initial docx and replace it ? with what {{ }} ?)

Thanks for any help, and thanks for the tool :)

Edit : I've tried this
sd = doc.new_subdoc()
sd.add_picture('logo.png', width=Inches(1.25))
context = {'mysubdoc' : sd}
and added {{mysubdoc}} in the docx file
but when I open the generated docx I have an error message from Word and the picture is missing

**Comment by elapouya** [comment]
remove picture from docx template, replace it with {{p mysubdoc}}
where mysubdoc is a sub-document containing the picture you want : see
tests/subdoc.py example.

2016-05-30 14:48 GMT+00:00 frschnell <notifications@github.com>:

**Comment by DennyWeinberg** [comment]
You can also wrap app into an if else block and all is fine ;)

**Comment by metadirective** [comment]
Thanks for both help :)
