### ISSUE TITLE
3.10无法安装

### ISSUE THREAD

**Issue by xuehang00126** [elapouya/python-docx-template#390]
fatal error C1083: 无法打开包括文件: “XXX.h”: No such file or directory问题解决办法

**Comment by caoergou** [comment]
@xuehang00126 
As a chinese developer，I'm ashamed of you for your lazy not to use any translate application before open the issue in Github.   
老哥，你上Github 提 issue 能不能先翻一下？再说不提供任何的环境信息直接甩一个报错就来问这合适吗？

**Comment by elapouya** [comment]
Anyway, the issue seems to be related to a compilation problem, so not related to docxtpl itself. 
Closing here as no more information are given.
