### ISSUE TITLE
Render function doesn't work

### ISSUE THREAD

**Issue by Dzirt07** [elapouya/python-docx-template#392]
Hello, I'm trying to automate the creation of Word documents.  
I have 2 templates and one CSV file which consists of all information. The goal is to create word documents based on csv file. 

The render() function doesn't work and all output files have the same information despite that variables are updated. 
It just keep adding same info from the first row located in CSV file 

Steps to reproduce the behavior, expected behavior etc...

```
import os, sys
from docxtpl import DocxTemplate
import csv

os.chdir(sys.path[0])
file = 'offers.csv'
offer_cover = DocxTemplate('Offer_Package_Home.docx')
sales_agreement = DocxTemplate('sale_agreement_template.docx')

with open(file) as f:
    csv = csv.reader(f)
    next(csv)
    for row in csv:
 
        mls_number = row[0].strip()
        offer_number = row[1]
        offer_words = row[2]
        broker_license = row[3]
        broker_name = row[4]
        # listing office
        listing_office_phones = row[5]
        broker_phone = row[6]
        broker_address = row[7]
        property_address = row[8]
        realtor_name = row[9]
        realtor_email = row[10]


        cover_context = {'property_address': property_address, 'MLS_number': mls_number, 'listing_office': broker_name,
                         'listing_agent': realtor_name, 'listing_agent_email': realtor_email}

        sales_agreement_context = {'property_address': property_address,
                                    'broker_name': broker_name,
                                   'broker_license': broker_license, 'broker_address': broker_address,
                                   'broker_phone': broker_phone, 'realtor_name': realtor_name,
                                   'realtor_email': realtor_email, 'offer_number': offer_number,
                                   'offer_words': offer_words}
        offer_cover.render(cover_context)
        sales_agreement.render(sales_agreement_context)
        os.mkdir(mls_number)
        offer_cover.save('.\\' + mls_number + '\\offer_cover_' + mls_number + '.docx')
        sales_agreement.save('.\\' + mls_number + '\\sales_agreement_' + mls_number + '.docx')
        cover_context = {''}
        sales_agreement_context = {''}
```

If applicable, add screenshots to help explain your problem
[offers.csv](https://github.com/elapouya/python-docx-template/files/7500069/offers.csv)
[sale_agreement_template_git.docx](https://github.com/elapouya/python-docx-template/files/7500070/sale_agreement_template_git.docx)
[Offer_Package_Home_git.docx](https://github.com/elapouya/python-docx-template/files/7500071/Offer_Package_Home_git.docx)
.

2 examples of output documents
[offer_cover_PAPH2010544.docx](https://github.com/elapouya/python-docx-template/files/7500166/offer_cover_PAPH2010544.docx)
[offer_cover_PAPH2040284.docx](https://github.com/elapouya/python-docx-template/files/7500167/offer_cover_PAPH2040284.docx)

**Comment by Dzirt07** [comment]
2 examples of output documents

[offer_cover_PAPH2040284.docx](https://github.com/elapouya/python-docx-template/files/7500155/offer_cover
[offer_cover_PAPH2010544.docx](https://github.com/elapouya/python-docx-template/files/7500159/offer_cover_PAPH2010544.docx)
_PAPH2040284.docx)

**Comment by elapouya** [comment]
This is a limitation right now : you have to re-instanciate the template object before each render() call.

So, please put the 2 lines : 

```
offer_cover = DocxTemplate('Offer_Package_Home.docx')
sales_agreement = DocxTemplate('sale_agreement_template.docx')
```

inside your csv row loop.
