### ISSUE TITLE
Creating multiple docx-documents from a csv file

### ISSUE THREAD

**Issue by Weird-room** [elapouya/python-docx-template#394]
I am trying to create multiple docx-documents from a csv file. I have a for loop reading the csv file and assigning the different rows to different dictionary keys and then using template.render(dictionary) followed by template.save(location).

The problem i run inte is that the first output document is flawless and the concurring ones is exactly the same as the first one. 

Using print(dictionary) I get unique output for every row in the csv file. 

## My code
```

from docxtpl import DocxTemplate, RichText
import csv

tpl = DocxTemplate('template.docx')

with open('input.csv') as inputCSV:
	csvReader = csv.reader(inputCSV, delimiter = ';')
	for row in csvReader:
	
		dict = {
		'Number' : row[0][-4:],
		'date' : row[1],
		'name' : row[2],
		'email' : row[3],
		'length' : int(row[4]),
		}
		
		tpl.render(dict)
		tpl.save('c:/test/Number. ' + row[0][-4:] + '-2021 decision regarding predation fence.docx')

```

Thank you for your time.

**Comment by elapouya** [comment]
This is a limitation right now : you have to re-instanciate the template object before each render() call.

**Comment by Weird-room** [comment]
> This is a limitation right now : you have to re-instanciate the template object before each render() call.

Thank you so much for the answer. 
So if i were to move
`tpl = DocxTemplate('template.docx')`
down to be included in the for-loop it would solve the problem?

Thanks again for your help.
