### ISSUE TITLE
Wrong mime type

### ISSUE THREAD

**Issue by simbirsky** [elapouya/python-docx-template#395]
I wrote this code for generate docx based on docx template:

```
#!/usr/bin/env python3

from docxtpl import DocxTemplate

doc = DocxTemplate("block.docx")
context = { 'kids' : [ {'name': 'Mihail', 'toys': [ {'name': 'php'} ]} ] }
doc.render(context)
doc.save("generated_doc.docx")
```

Why mimetype of `generated_doc.docx` file is `application/octet-stream` ? Mimetype of block.docx file is `application/vnd.openxmlformats-officedocument.wordprocessingml.document`

How can i fix it? I need to give `generated_doc.docx` file to user for download and the user receives a file with the wrong mimetype

**Comment by elapouya** [comment]
Please contact python-docx project owner as python-docx-template is using its .save() method.
Alternatively, force mime on your web server or your python web application.
