### ISSUE TITLE
Page break in for loop

### ISSUE THREAD

**Issue by simbirsky** [elapouya/python-docx-template#396]
How can i break page in loop?

My case:

```
{% for page in pages %}
some text
{% endfor %}
```

But i don't know how break page after each iteration.

**Comment by elapouya** [comment]
Just add a page break with MS Word just before the `{% enfor %}`

**Comment by simbirsky** [comment]
In one case i have problem with that approach
If the page is completely filled then the page transfer character will be written to the next page. As result i have one empty page in word document :(
How can i get rid of it?

**Comment by elapouya** [comment]
The only way I see is to create a page_break variable containing a richtext with a page break : 
```
context = { 'page_break': RichText('\f') }
```

And in your docx template use : `{{r page_break}}`

I never tested, but should work.
