### ISSUE TITLE
header and footer problem 

### ISSUE THREAD

**Issue by zwkin** [elapouya/python-docx-template#40]
The header and footer will disappear when also using the subdoc at the same time. Any idea to avoid this problem?

Thanks for help in advance and thanks for the great tool.

**Comment by elapouya** [comment]
I have to investigate...

2016-06-10 5:26 GMT+02:00 zwkin <notifications@github.com>:

**Comment by DennyWeinberg** [comment]
Hi,

I had the same problem. Here is the solution:
`    def __ext_snipplet(self, name):
        """
        Render another docx body into my document
        """
        document = DocxTemplate(self.getSnippletPath(name))
        document.render(self.jinjaContext)

        # Remove the sectPr element ("SecrionProperties")
        # "This element defines the section properties for the final section of the document." (Source: https://msdn.microsoft.com/en-us/library/documentformat.openxml.wordprocessing.sectionproperties(v=office.14).aspx)
        # This is not needed in case of a snipplet
        if document._element.body.sectPr is not None:
            document._element.body.remove(document._element.body.sectPr)

        # Remove the body xml tag
        xml = re.sub(r'</?w:body[^>]*>', '', document.get_xml())

        return xml`

It is really important to remove the "sectPr" Element and the body open and close tags before inserting another document into yours.
More information are provided in the comments of the code.

It would be nice if we could integrate this function into the branch?

I have also another function to insert a picture:
`    def __ext_image(self, image_path_or_stream, unit='cm', width=None, height=None):
        """
        Insert an image into docx
        """
        sd = self.new_subdoc()
        if unit == 'cm':
            sd.add_picture(image_path_or_stream, width=Cm(width) if width else None, height=Cm(height) if height else None)
        else:
            raise NotImplementedError('Unit %r currently not implemented!' % (unit))

        return sd`

With this you can directly use {{p image('test_files/python_logo.png', width=2)}} in your docx if you are adding the fonction to the jinja context like this:
self.jinjaContext.update({'image': self.__ext_image})

# snipplet
self.jinjaContext.update({'snipplet': self.__ext_snipplet})

**Comment by elapouya** [comment]
I fixed the problem by removing the "sectPr" Element.
Thanks Denny ;) 

Pushed version 0.2.1 on pypi
