### ISSUE TITLE
pandoc generate docx can't use new_subdoc

### ISSUE THREAD

**Issue by Mustard404** [elapouya/python-docx-template#405]
## demo
[test.zip](https://github.com/elapouya/python-docx-template/files/7791076/test.zip)
## Expected behavior
I think zhe base64 image bug

**Comment by elapouya** [comment]
docxtpl uses another project to merge subdocs : docxcompose, I think it comes from that.
I do not have pandoc : please generate the vuls_1.docx, load it in MSWord and save it again with another name : pandoc may generate a corrupted docx.

**Comment by Mustard404** [comment]
update demo,  generate the vuls_1.docx
[test.zip](https://github.com/elapouya/python-docx-template/files/7795233/test.zip)

**Comment by elapouya** [comment]
If I open the vuls_1.docx and simply save it again as another file, the merging work well.
This means that pandoc generated a file that is not properly managed by docxcompose
My guess is that you are using base64 image and pandoc has generated inline image docx which is not supported by docxtpl.
As a workaround, you could load+save the pandoc generated docx with libreoffice before using it in docxtpl.

**Comment by billsteve** [comment]
> zhe

Have you fixed the BUG?
