### ISSUE TITLE
Banded rows when looping through a table

### ISSUE THREAD

**Issue by nixshal** [elapouya/python-docx-template#407]
Hello

I wanted to confirm if there was a way to make sure the banded rows (rows in alternate colors) show up.

In my [example.pdf](https://github.com/elapouya/python-docx-template/files/7846819/example.pdf), the table at the top has the banded rows option selected (under the Table Design tab).

However, when looping through the table, only the orange color row (or any other color that the variable is in) is preserved and you don't get the appearance of the banded row.

Would like some help on how I could achieve this. Thanks.

**Comment by sebastian-jansson** [comment]
Setting the table design to this and checking "banded rows": ![image](https://user-images.githubusercontent.com/54795430/151777245-b1fe66b1-d411-4bd4-a64e-b62d000ca715.png)

Results in a table in the template that looks like this:
![image](https://user-images.githubusercontent.com/54795430/151777357-babdc7d3-56b2-4d35-bcae-8b4da33835c9.png)


Which successfully gave me banded rows. However, it was a while ago I did this and I recall having to fiddle with the different options at first.

**Comment by SergeyZaykov** [comment]
Look this example: [Dynamically set cellbg](https://github.com/elapouya/python-docx-template/issues/420)
