### ISSUE TITLE
get_undeclared_template_variables thorws AttributeError in Version 15.1

### ISSUE THREAD

**Issue by jurkov** [elapouya/python-docx-template#408]
## Describe the bug
`get_undeclared_template_variables` throws `AttributeError: 'NoneType' object has no attribute '_element'`

## To Reproduce
install 15.1
```
    docx_tpl = DocxTemplate(tpl.docx_tpl.file)
    content_tpl = docx_tpl.get_undeclared_template_variables()
```

## Expected behavior
return undeclared template variables

## Additional context
`AttributeError: 'NoneType' object has no attribute '_element' ` comes from[ `return self.xml_to_string(self.docx._element.body) `](https://github.com/elapouya/python-docx-template/blob/19733a6b5b6898c24fc1a431765c97c0efda9d74/docxtpl/template.py#L69)

## Workaround ##
Install 14.1

**Comment by elapouya** [comment]
fixed in 0.15.2
