### ISSUE TITLE
Impossible to open the word document after adding a picture

### ISSUE THREAD

**Issue by BenoitMarchand** [elapouya/python-docx-template#409]
## Describe the bug
I try this librairies with simple template to edit a single variable, create a table and add a picture with InlineImage

As long a I do not add an image everything work well

But if I try to add the image , no python error occurs, but when I use word to open it I have a message 

the word template contains 
{{ my_picture }} where I want to add the picture

Code : 

import numpy as np
from docxtpl import DocxTemplate,InlineImage
from docx.shared import Mm
from matplotlib import pyplot as plt 

###### open template
doc = DocxTemplate("test.docx")
######  template and the appropriate value
context = { 'myvariable' : 152 }
######  header first (nb of column can be defines in the python script)
context["header"] = ["col1", "col2", "col3"]
######  value to be added in the table
marge = []
for i in np.arange(0,100):
    marge.append([1, "some text", 3])
context["marge"] = marge
######  insert picture 1) create the picture, save it an insert it with InlineImage
fig, ax = plt.subplots(1)
ax.scatter([1,2,3], [1,2,3])
file_name = "new_picture.png"
fig.savefig(file_name)
myChart = InlineImage(doc, image_descriptor=file_name)
context = { 'my_picture' : myChart}
###### put all value in the document and save it. 
doc.render(context)
doc.save("generated_doc.docx")

NB : I tried with context = { 'my_picture2' : myChart}, wherease I have no tag my_picture2 and the issues is still there. 
If I comment this line, I can perfectly open the document and the table and variable are updated

**Comment by elapouya** [comment]
Please provide the "test.docx" to reproduce the problem

**Comment by BenoitMarchand** [comment]
dear elapoya, 

Thank you for your quick response. please find below the template file : 

[test.docx](https://github.com/elapouya/python-docx-template/files/7914695/test.docx)

**Comment by elapouya** [comment]
It work perfectly with me : please check docxtpl version and python environement : 
```
$ pip list
Package         Version
--------------- -------
cycler          0.11.0
docxcompose     1.3.4
docxtpl         0.15.2
Jinja2          3.0.3
kiwisolver      1.3.1
lxml            4.7.1
MarkupSafe      2.0.1
matplotlib      3.3.4
numpy           1.19.5
Pillow          8.4.0
pip             21.3.1
pyparsing       3.0.7
python-dateutil 2.8.2
python-docx     0.8.11
setuptools      59.6.0
six             1.16.0
wheel           0.37.1
```

**Comment by elapouya** [comment]
Sorry, I tested with libreoffice which works : I can see generated image in generated docx without any error message
But not with MSWord !!
So investigating...

**Comment by elapouya** [comment]
I found the problem, it does not come from image but the above table : MSWord does not like empty tables.
You have an error in your python code : you erase context data to put inlineimage object so there is no more table data.

Just replace 

`context = { 'my_picture' : myChart}`

by

`context.update({ 'my_picture' : myChart})`

**Comment by BenoitMarchand** [comment]
Great, thank you very much for your very quick response and for taking the time to investigate the "issue" I was facing. It work like a charm an it was definitelly 

With my best regards.
