### ISSUE TITLE
Pagebreak

### ISSUE THREAD

**Issue by Kulikovpavel** [elapouya/python-docx-template#41]
Hello

I need to make doc with one template, several pages, in for loop.

When i add pagebreak in template directly, at end of page, but before {% endfor %} tag, with N items i got N pages with template and N blank pages at end.

How can i do this?

Or maybe i can add subdocs in  loop in python to add pages?

**Comment by DennyWeinberg** [comment]
Please attach the docx file to be able to reproduce it. Normally this should work...

**Comment by Kulikovpavel** [comment]
Well, somehow new variant of template work good now. Strange. Dont sure, what to go wrong first time
