### ISSUE TITLE
Copy an Exels datasheet directly in word document (like Richtext)

### ISSUE THREAD

**Issue by SaugetMarc** [elapouya/python-docx-template#415]
## Context 

I have generated an Excel document with many sheet (with panda) and the formating is build with Excel. 
Now, I just want to take this sheet and copy it in a word document at an specified emplacement.
Reading your documentation, I have not find how to do this step.

**Comment by elapouya** [comment]
This is already possible : the idea is to put a dummy/empty excel file in your docx template and replace it by the one you generated by using replace_embedded() 

See the documentation and tests/embedded.py

**Comment by SaugetMarc** [comment]
Yes but no.
In this case, you are embedding the file, not the content.

I only need a final file, not a grouping that is not directly readable.
I see if I can suggest a solution.

Best regards

**Comment by elapouya** [comment]
Please show an exemple of the expected document.

**Comment by elapouya** [comment]
If your goal is to generate a docx with a table containing the data extracted from an excel file, you can do that too.
See tests/dynamic_table.py
