### ISSUE TITLE
Indicating a RESTfulAPI & JSON transformation file for fetching data & transforming it

### ISSUE THREAD

**Issue by NarayananSG** [elapouya/python-docx-template#419]
## Describe your problem
I need to fetch data from API endpoint & transform the received JSON data (using a JSON transformation file) to correspond to the data field names for specific table that will be populated.
For this, is it possible to indicate a RESTful API endpoint and JSON transformation file as part of table jinja syntax? Also, would it possible to configure so that the data is fetched at run time during rendering instead of  preparing the entire context before rendering.

**Comment by elapouya** [comment]
I do not know what is a JSON transformation file. Are you sure you are in the good project ?

**Comment by NarayananSG** [comment]
Sorry for the confusion. I am trying to use docxtpl (so in the right project)
I rephrase my question
a) Is it possible to fetch (through REST API or other means) the needed data (for every table in my template) during rendering  & put in the context instead of having to fetch the data & store it in the context before start of the rendering. Something, like a dynamic context.
b) If point (a) is not possible, is there any way to indicate (syntax) the datasource (say REST API) of every table in the template so that I may get that info from template before rendering, fetch data & fill the context.

**Comment by elapouya** [comment]
docxtpl both does not have API and is not able to call an API to get context during rendering. The only way is to fill context dictionary yourself (by using an external API if you want)  then pass it to the render() method.
