### ISSUE TITLE
RichText: Keep Word font size and family

### ISSUE THREAD

**Issue by DennyWeinberg** [elapouya/python-docx-template#42]
Hi,

If I use {{r RichText('abc', bold=True) }} I have my bold text "abc" but I loose my font family and size that I used in the Word Template.

Is there any chance to keep the formatting defined in word, except if I pass it as arguments to the RichText constructor?

**Comment by DennyWeinberg** [comment]
I found it out. It takes the original style used in word.

**Comment by elapouya** [comment]
Hi,

Actually, If bold is set in RichText object, no font family nor size xml
code are generated, it should inherit from template style, but you say it
does not.
This means, some inheritance attributes is missing in generated xml code
somewhere... I have to make some research...

2016-06-17 11:13 GMT+00:00 Denny Weinberg <notifications@github.com>:

**Comment by DennyWeinberg** [comment]
Ok. Cool, so let me know if you found something.

Example: I use the normal style but I set the font size to 8. It we use the RichText the result is a text with font size 12 or so (default font size). Even if I don't apecified the font size in the RichText.

**Comment by elapouya** [comment]
The problem is in fact normal : {{r }} removes character styling : you have to specify the styling you want with 'style=xxx'.
Alternatively, you can use paragraph styling in your template : it should not be replaced
