### ISSUE TITLE
Dynamically set cellbg

### ISSUE THREAD

**Issue by SergeyZaykov** [elapouya/python-docx-template#420]
##Is your feature request related to a problem? Please describe.
I wanted to set dynamically cellbg, like this {% if x > 2 %}{% cellbg 'FFFFFF' %}{% endif%}. But it doesn't work.
[Here](https://github.com/elapouya/python-docx-template/issues/373) was recomended to use a variable in {% cellbg %} and define its value during rendering (at python side).
For nested JSON arrays this solution is tedious.
IMHO, the better way is defining cell's colour in a Word document directly.

## Describe the solution you'd like
{% cellbg 'ff0000' if x > 1 else 'ffffff' %}cell's text

## Describe alternatives you've considered
For setting background colour dynamicaly used Jinja [If Expression](https://jinja.palletsprojects.com/en/3.0.x/templates/#if-expression)
It is no way set cell's background colour if condition is true only.
You need to define background colour in both cases.

## Additional context
The 'classic' white colour is 'ffffff'.

**Comment by SergeyZaykov** [comment]
Excelent! Now it work.

I make an example of striped lines in table.

[stripe.docx](https://github.com/elapouya/python-docx-template/files/9984506/stripe.docx)

`# -*- coding: utf-8 -*-
"""Striped lines in table."""

from docxtpl import DocxTemplate

tpl = DocxTemplate("templates/stripe.docx")

context = {
    "noms": [
        {"nom": "Anton", "sexe": "masculin"},
        {"nom": "Ivan", "sexe": "masculin"},
        {"nom": "Boris", "sexe": "masculin"},
        {"nom": "et moi", "sexe": "féminin"},
        {"nom": "Rebecca", "sexe": "féminin"},
        {"nom": "Paula", "sexe": "féminin"},
        {"nom": "Johanna", "sexe": "féminin"},
        {"nom": "et moi", "sexe": "féminin"},
    ]
}
tpl.render(context)
tpl.save("output/stripe.docx")
`

**Comment by shivangi-2001** [comment]
Can you share, how to add colors when nested if the loop

**Comment by SergeyZaykov** [comment]
{% cellbg 'D9DDDC' if loop.index is divisibleby 2 else 'ffffff' %} {{ nom.sexe }}
where 'D9DDDC' is the color of the grayed row of the table and 'ffffff' is the color of the unpainted row of the table.
