### ISSUE TITLE
Using RichText for bold text + |upper filter interferes with rendering; bold text + |lower filter results in lowercase unbolded text   

### ISSUE THREAD

**Issue by boomesq** [elapouya/python-docx-template#422]
## Describe the bug

Using RichText to create bold text and {{r \<var>|upper}} tag to make uppercase results in this error if tag is in body of docx template upon trying to open with Word:
_Word experienced an error trying to open the file.
Try these suggestions.
	* Check the file permissions for the document or drive.
	* Make sure there is sufficiently free memory and disk space.
	* Open the file with the Text Recovery converter.
	(C:\...\****.docx)_

If used in header or footer, the tag results in this error in Python shell:
_lxml.etree.XMLSyntaxError: Namespace prefix W on R is not defined_

Using {{r \<var>|lower}} tag to make lowercase bold text in body, header, or footer renders openable file, but produces unbolded lowercase text. 

## To Reproduce

```
from docxtpl import DocxTemplate, RichText

doc = DocxTemplate('test_template.docx') 

context = {
            'Test_Key': 'Test_Value',
            'Test_Key_Bold': RichText('Test_Value', bold=True)
            }

doc.render(context)

doc.save('test_outcome.docx')

```

A template combining {{r \<var> }} with |lower is attached. Change |lower to |upper to reproduce bugs with latter. 

## Expected behavior
Combining {{r \<var> }} with |upper or |lower should result in openable file with bold uppercase or bold lowercase text, respectively.

[test_template.docx](https://github.com/elapouya/python-docx-template/files/8227238/test_template.docx)

**Comment by elapouya** [comment]
I modified the documentation for ``RichText`` :

``RichText`` objects are rendered into xml *before* any filter is applied
thus ``RichText`` are not compatible with Jinja2 filters. You cannot write in your template something like ``{{r <var>|lower }}``.
Only solution is instead to do any filtering into your python code when creating the ``RichText`` object.
