### ISSUE TITLE
How to insert page numbers？

### ISSUE THREAD

**Issue by lucy304** [elapouya/python-docx-template#423]
## Describe your problem
A clear and concise description of what you want to do

## More details about your problem
Steps to reproduce the behavior, expected behavior etc...

## Provide a test case
If applicable, provide minimal python code + docx template + other files (images etc...) to reproduce the behavior

**Comment by elapouya** [comment]
Page auto-number must be put in docx template footer with MSWord. This cannot be done with docxtpl as it does not know how many pages are in the generated doc.
