### ISSUE TITLE
Numbered Lists Inside {% for %} Loop Don't Restart At 1

### ISSUE THREAD

**Issue by coder0xff** [elapouya/python-docx-template#425]
## Describe the bug
When a numbered list is inside a template {% for %} loop, the first item in each list is numbered subsequent to the last item in the previous list, even when the lists are separated by other intervening content.

## To Reproduce
Make a template using a numbered list like so:

{% for i in [0, 1, 2] %}

Foobar {{ i }}

1.	Item 1
2.	Item 2

{% endfor %}

Render and save the output to file.

## Expected behavior
The expected output looks like the following:

Foobar 0
1.	Item 1
2.	Item 2

Foobar 1
1.	Item 1
2.	Item 2

Foobar 2
1.	Item 1
2.	Item 2

## Actual behavior

Foobar 0
1.	Item 1
2.	Item 2

Foobar 1
&nbsp;&nbsp;&nbsp;&nbsp;3.	  Item 1
&nbsp;&nbsp;&nbsp;&nbsp;4.	  Item 2

Foobar 2
&nbsp;&nbsp;&nbsp;&nbsp;5.	Item 1
&nbsp;&nbsp;&nbsp;&nbsp;6.	Item 2

## Screenshots
![image](https://user-images.githubusercontent.com/2261949/159800370-b7575ecf-875c-4c04-ba44-c2b1f31e2e00.png)

**Comment by elapouya** [comment]
Hello, could you give me a docx of the expected output (done by hand) and a docx of the actual output
I will have a look at the XML differences.

**Comment by coder0xff** [comment]
No problem

[actual.docx](https://github.com/elapouya/python-docx-template/files/8373486/actual.docx)

[expected.docx](https://github.com/elapouya/python-docx-template/files/8373490/expected.docx)

**Comment by elapouya** [comment]
Actually, the only difference that can explain it does not work as expected is the presence in expected.docx of this tag in paragraph properties : 

```<w:pStyle w:val="ListParagraph"/>```

It seems this tag is applied by microsoft word each time the item counter need to be resetted. that is starting from the 2nd list.
As in template.docx there is only one list, the tag is not applied.

A workaround could be to force MSWord to add the tag in template by putting your for-loop at 2nd list. 
To do so, could you add BEFORE the `{% for i in [0, 1, 2] %}` something like :

```
{%p if False %}
Dummy Foobar
    1. Item 1
    2. Item 2
{%p endif %}
 ```

And tell me what's happen...

**Comment by coder0xff** [comment]
Thank you for sharing a workaround. I settled for using bullets instead of numbers and have to work on other stuff now.

**Comment by bigNeoneo** [comment]
> No problem
> 
> [actual.docx](https://github.com/elapouya/python-docx-template/files/8373486/actual.docx)
> 
> [expected.docx](https://github.com/elapouya/python-docx-template/files/8373490/expected.docx)
> 
> Additionally:
> 
> [template.docx](https://github.com/elapouya/python-docx-template/files/8373504/template.docx)
> 
> Python code:
> 
> ```
> doc = DocxTemplate("template.docx")
> doc.render({})
> doc.save("actual.docx")
> ```

if you write this in your template.docx you will realize the problem

**Comment by elapouya** [comment]
Could you try with this template : 
[template2.docx](https://github.com/elapouya/python-docx-template/files/8884195/template2.docx)

**Comment by coder0xff** [comment]
> Could you try with this template : [template2.docx](https://github.com/elapouya/python-docx-template/files/8884195/template2.docx)

I'm not working on the project anymore. I'll trust that whatever you've got working locally is good. :)
