### ISSUE TITLE
InlineImage raise a UnrecognizedImageError with HEIC (HEIF) image

### ISSUE THREAD

**Issue by tibetoine** [elapouya/python-docx-template#426]
## Describe the bug
InlineImage raise a UnrecognizedImageError Exception when handling HEIC (HEIF) image.

## To Reproduce
Had photo.heic into templates folder (Attached file)
Had this line in tests/inline_mage.py
```
{
    'image': InlineImage(tpl, 'templates/photo.heic', height=Mm(10)),
    'desc': 'Photo HEIC.',
}
```
Run the test

**Comment by elapouya** [comment]
HEIF images are not supported, sorry.
