### ISSUE TITLE
Lambda Layer docxtpl

### ISSUE THREAD

**Issue by devneagu** [elapouya/python-docx-template#429]
## Describe your problem
I'm trying to create an archive with docxtpl library to upload it in order to generate some documents and save them into the s3 cloud.

## More details about your problem
Unable to import docxtpl after the layer has been selected.

## Provide a test case
Create a docker container. 
Create a folder
pip3 install docxtpl -t ./
zip the archive
upload it via aws layer

## Screenshots
"errorMessage": "Unable to import module 'lambda_function': No module named 'docxtpl'",

**Comment by elapouya** [comment]
I will be unable to reproduce your problem as I do not have aws access.
But the message you gave is not docxtpl related but more a python configuration problem that's leads to docxtpl module access problem.
