### ISSUE TITLE
QUESTION: How to render text in subdocument?

### ISSUE THREAD

**Issue by Wyko** [elapouya/python-docx-template#433]
## Describe your problem
I want to insert a single subdocument into a document multiple times, inserting text into the subdocument.

## More details about your problem
I would expect that it's possible to populate a subdocument with content before inserting it into the parent document. 

## How I would expect it to work

```python
from docxtpl import DocxTemplate

doc = DocxTemplate(r"master.docx")
sd = doc.new_subdoc(r"sub.docx")

sd.tpl.render({"sometext": "test"})

doc.render({"sub_tpl": sd})
doc.save("generated_doc.docx")
```

**Comment by Wyko** [comment]
Per this comment: https://github.com/elapouya/python-docx-template/issues/388#issuecomment-997377167

Rending should work when done separately. But it doesn't seem to.

**Comment by LithiumBloom** [comment]
I've run into the same problem and hopefully have suggested a successful fix with my pull request, but in the mean time a workaround that has worked for me is to set:

doc.is_rendered = False

before the 2nd doc.render().

**Comment by elapouya** [comment]
You are rendering subdoc and the doc that contains this subdoc without generating intermediate file : this is not supported.
You need to render + save the subdoc template then re-use the generated subdoc into the final doc template via another render and save.

**Comment by Tanishqmalu** [comment]
I am not sure if its possible but can't we simply extract the document part of the subdocument, then use xml_build funtion similar to that of DocxTemplate class, wherein, the whole xml tree is parsed, patched and added with context variables. This can then be added into the main document? 

Why is there a need to save the subdocument file, if we have to render some context inside it and add to the main document. Right before the saving step, the xml tree of the subdocument will be prepared, so cant we just add it to the main document?

Please let me know if this makes any sense, or it can be a completely wrong assumption?
