### ISSUE TITLE
Replace picture that was inserted using word.

### ISSUE THREAD

**Issue by bobbolous** [elapouya/python-docx-template#435]
## Describe your problem
If I insert a picture into a docx file using word (in my case word 2019) I don't know how this picture is referenced by word. Therefore i fail replacing it using `replace_pic`. Even manually editing the name in "Picture Tools"->"Selection Area" or adding an "Alternative text" does not solve the problem, as docxtpl shows error: "ValueError: Picture myPicture not found in the docx template".
Funny thing: if I open the word file in LibreOffice and save it (without actively changing anything) docxtpl can find the picture with the defined name. Is there any way I can get it to work with word alone?

**Comment by elapouya** [comment]
There is now a much better way to insert an image in a  docx : InlineImage
Please read the doc

**Comment by bobbolous** [comment]
Thanks for that suggestion. The idea of using the `replace_pic `function was to get a good preview in the template of the final document.
Do I understand your comment correct, that there is no way to do it as I intended and I should rather use a different approach?

**Comment by elapouya** [comment]
Unfortunately, InlineImage has been created beacause it has always been difficult to find image ID to replace. 
For replacement, there is an alternative : `replace_media(src_file, dst_file)` but in this case, the `src_file` must exist in order to calculate its CRC and then find it in zip file for replacement. (a .docx is a zip archive)

**Comment by bobbolous** [comment]
Thank you for suggesting `replace_media`, as the template pictures are available this may be a good idea. I run into problems when using `InlineImage`, as word2019 is telling me the file is corrupted (although it is able to open it).
