### ISSUE TITLE
New line being added somehow

### ISSUE THREAD

**Issue by almandin** [elapouya/python-docx-template#437]
Hi, I know this is a common problem and I've read other issues about this, googled a lot and read jinja formatting of newlines, the use of `{%-` and `-%}`, though I dont find a workaround in my situation :
## Describe your problem
I have a for loop which iterates over subdocuments and add each of them while handling the title of these documents. Each subdocument has a newline added in the end, even though I use the `{{p mysubdoc }}` trick.

```
{% for section, subdoc in elements -%}{% if section.level == 0 %}
1.	{{ section.title }}{% elif section.level == 1 %}
1.1	{{ section.title }}{% elif section.level == 2 %}
1.1.1	{{ section.title }}{% elif section.level == 3 %}
1.1.1.1	{{ section.title }}{% elif section.level == 4 %}
1.1.1.1.1	{{ section.title }}{% elif section.level == 5 %}
1.1.1.1.1.1	{{ section.title }}{% endif %}
{%- if subdoc is not none %}
{{p subdoc }}
{% endif %}{% endfor %}
```

![image](https://user-images.githubusercontent.com/9830129/168105969-ac238c74-7749-473d-982f-e7147c877647.png)

In my example, `section.level` is my title level, which I use to determine what style to use in the document. This results in having a line break after each subdoc, but I don't know what line break is replicated from the template into the generated document.

![image](https://user-images.githubusercontent.com/9830129/168104311-1fdb26ca-b951-4da7-8ec8-6f2ae7b6cb00.png)

I have the feeling that it has nothing to do with the use of the subdoctument as I tried replacing it by static text and the line break is still added. If I use `{%- endif %}` instead of `{% endif %}` in the last line of my template, Jinja throws an error saying that the `if` statement isnt closed. I'd like to know if I'm missing something or if this is a bug somehow. Thanks by advance.

**Comment by ILightThings** [comment]
Without knowing the context, I think you need to move 
```
{%- if subdoc is not none %}
{{p subdoc }}
{% endif %}{% endfor %}
```
to
```
{%- if subdoc is not none %}{{p subdoc }}{% endif %}
{% endfor %}
```

**Comment by ILightThings** [comment]
New line characters after end statements are treated as part of the template.

**Comment by elapouya** [comment]
You should not use `{%- -%}` this is really for very specific cases, just use a `p` like in `{%p for/if/elif/endif/endfor %}`

I would try this : 
```
{%p for section, subdoc in elements %}
{%p if section.level == 0 %}
1.	{{ section.title }}
{%p elif section.level == 1 %}
1.1	{{ section.title }}
{%p elif section.level == 2 %}
1.1.1	{{ section.title }}
{%p elif section.level == 3 %}
1.1.1.1	{{ section.title }}
{%p elif section.level == 4 %}
1.1.1.1.1	{{ section.title }}
{%p elif section.level == 5 %}
1.1.1.1.1.1	{{ section.title }}
{%p endif %}
{%p if subdoc is not None %}
    {{subdoc}}
{%p endif %}
{%p endfor %}
```

Note : do not put more then one `{%p %}` on the same line. 
The `p` means "remove the paragraph where I am".
So `{{subdoc}}` should not have a `{{p`

**Comment by almandin** [comment]
Thanks a lot for your answers, thanks @elapouya for your time for this quite common problem. I feel that I have tried that a hundred times before asking and however it works like a charm if I add a `p` to `{{p subdoc}}`. Without this last one I still have a newline after each of my subdocuments somehow ...
Anyway, fixed, thanks a lot. (docx-tpl is veery useful, thanks for your work).
