### ISSUE TITLE
Change a RichText instance's paragraph style

### ISSUE THREAD

**Issue by m-ghonim** [elapouya/python-docx-template#438]
## Description
Is there a clean way to modify the paragraph style for an instance of a RichText object using python

## More details
This would allow, for example, inserting Bullet Lists dynamically by having multiple RichText objects, each with a "List Bullet" paragraph style.
I've tried checking the API documentation but couldn't find any references.

**Comment by elapouya** [comment]
Sorry, docxtpl does not support paragraph style customizing. RichText is only for 'runs' (texts inside a paragraph).

**Comment by m-ghonim** [comment]
Thanks for the quick response.
I'm curious, Is there a technical reason for this decision, or is it just out of development scope atm?

**Comment by elapouya** [comment]
it is just out of development scope for the moment
