### ISSUE TITLE
Merging directives on both sides of whitespace result in deleted tags

### ISSUE THREAD

**Issue by danielbrauer** [elapouya/python-docx-template#444]
## Describe the bug
The manual explains that you shouldn't put text on the same line outside `{%-` or `-%}`. However, this situation can inadvertently be created by nearby merge directives

## To Reproduce
```
{% if True -%}

{%- endif %}
```

## Expected behavior
Template renders as if it read `{% if True %}{% endif %}`

## Actual behaviour
Template renders as if it read `{% if True %}`, resulting in Unexpected end of template

## Additional context
This is a contrived example because of the empty conditional, but the situation can happen between any two tags, resulting in syntax errors.

**Comment by elapouya** [comment]
Investigating...

**Comment by elapouya** [comment]
The way it is coded requires there is something to merge, here there is nothing between `-%}`and `{%-`
I will try to modify the regex so one merge is not "eating" the other...
