### ISSUE TITLE
Merging directive before table creates unreadable document

### ISSUE THREAD

**Issue by danielbrauer** [elapouya/python-docx-template#445]
## Describe the bug
A merge directive before a table creates an output which Word refuses to read, presumably because of deleted table markers.

## To Reproduce
Python example from the docs. 
[my_word_template.docx](https://github.com/elapouya/python-docx-template/files/8966598/my_word_template.docx)

## Expected behavior
Rendered document is valid

## Screenshots
Rendered document does not open in Word for Mac 16.62: `Word experienced an error trying to open the file.`

**Comment by elapouya** [comment]
For docxtpl, the merge directive is to be used inside a same run (only text). Here you have no text after, only a table.
If your goal was to not see the `set`directive, just use this alone in a line: 

`{%p set test = True %}` 

the `p` tells docxtpl to not display the paragraph where the tag is located

**Comment by danielbrauer** [comment]
Given that white space management is entirely manual in docxtpl, it would be good if this produced an error rather than a broken document.

**Comment by elapouya** [comment]
docxtpl is regex based, not node based, errors cannot be reported, sorry.
