### ISSUE TITLE
Cannot render less than sign

### ISSUE THREAD

**Issue by CppXL** [elapouya/python-docx-template#447]
## Describe the bug
docxtlp  cannot render less than sign, if template.docx reander data with `{{test}}` mark and the data like:
```
data = {"test": "100<100 "}
```
Then we will get the following result: `100100`
 
## To Reproduce
test_tpl.docx:
```
{{test}}
```
python code
```python
from docxtpl import DocxTemplate

data = {"test": "100<100 "}
doc = DocxTemplate("test_tpl.docx")
doc.render(data)
print(data)
doc.save("output/" + "test.docx")
```

## Expected behavior
I would like to get the following result: `100<100` in test.docx after render

## Others

but docxtpl can render `greater than sign`  with true reesult, such as:
```
data = {"test": "100>100 "}
```

we can get following result in test.docx:`100>100`

**Comment by elapouya** [comment]
Please use `render(context, autoescape=True)`

**Comment by alexbnlee** [comment]
> Please use `render(context, autoescape=True)`

Thanks bro, it works for me.
