### ISSUE TITLE
Error on import DocxTemplate (Python <3.9)

### ISSUE THREAD

**Issue by dave-howard** [elapouya/python-docx-template#448]
## Describe the bug
I get an error when I import DocxTemplate class in python 3.8. First noticed in 0.16.2, error does not exist in 0.16.0

## To Reproduce
`from docxtpl import DocxTemplate` in python < 3.9.

## Expected behavior
No error

## Screenshots
![image](https://user-images.githubusercontent.com/39430263/179005431-e6e10263-96f6-448b-adc2-4898d1bacf75.png)

## Additional context
Maybe related to line 39 in: https://github.com/elapouya/python-docx-template/commit/0ab1144a8d3e0a203be0010f846798bd85a98457

I have tested in Python 3.7, 3.8 (fails) and in 3.9, 3.10 (no error)

Thank you
Dave

**Comment by elapouya** [comment]
Problem was introduced with PR #442, I will provide a fix soon.

**Comment by elapouya** [comment]
fix tested from python 3.6 to 3.10

**Comment by dave-howard** [comment]
Quick fix much appreciated, thank you
