### ISSUE TITLE
Would it be possible to get a list of all the modules required?

### ISSUE THREAD

**Issue by AvilaQ8** [elapouya/python-docx-template#450]
I'm working on an offline machine and wanted to use docxtpl to help with a project I'm working on. The issue if since I'm using an offline machine I have to manually download the packages from pypi which isn't an issue, but I keep running into x module is missing, then go down lap said module to find it requires another. 

Would it be possible to get a list of required packages/modules to be able to downloaded them all at once?

**Comment by elapouya** [comment]
do something like this : 
```
virtualenv venv
cd venv
. ./bin/activate
pip install docxtpl
pip list or pip freeze like you prefer
```
