### ISSUE TITLE
Unable to open doc file after render XML code

### ISSUE THREAD

**Issue by phucdc-noob** [elapouya/python-docx-template#461]
Im trying to render XML inside my document, everything works fine, but when i tried to open Document, it show as bellow:

![image](https://user-images.githubusercontent.com/82533607/198529080-178c5865-84c2-4819-968a-62c39efe6478.png)

Maybe Word detected that XML and think it's Document's XML, then we have this error
Sorry for bad English

**Comment by elapouya** [comment]
Please use autoescape=True in render()

Cordialement,

Eric Lapouyade

------- Original Message -------

**Comment by phucdc-noob** [comment]
Thanks, that fixed.
