### ISSUE TITLE
Prevent weird spacing

### ISSUE THREAD

**Issue by mgcd-jed** [elapouya/python-docx-template#470]
## Describe your problem
When inserting text into a `{{ content }}` variable with a return to line, this will happen (with the content inserted being `Some text that will be weirdly spaced\r\nSome more text`)
![image](https://user-images.githubusercontent.com/108806857/208453802-ea0d75f1-2bbf-4c4a-8617-85d16c5b2499.png)
How can I fix this behavior ? This weird spacing probably has a name and is a feature rather then a bug, I jsut don't know what it is and how to disable it...

**Comment by Slarag** [comment]
Check the formatting of the paragraph with the `{{ content }}` variable. I get this behavior only when I set the alignment of the paragraph to "justified":
![image](https://user-images.githubusercontent.com/58182961/211152207-6c4452e1-3499-4fe8-aa1c-b27ba5208ec1.png)

**Comment by mgcd-jed** [comment]
My bad, I don't know how that got Justified in my model since it wasn't in the file I used as a base. How well, thanks Word :)
Have a great day.
