### ISSUE TITLE
Dynamic table in docx from excel

### ISSUE THREAD

**Issue by ghost** [elapouya/python-docx-template#475]
Hello, I need some help, please. I'm trying to get many word documents from a excel data frame by a variable group (Date + Topic)

![image](https://user-images.githubusercontent.com/122225314/211393785-f3cc5b5c-1857-42a0-9bef-c083caf428f8.png)

The final result that I would like to obtain is a document like this for each value of the group variable (Topic):

![image](https://user-images.githubusercontent.com/122225314/211394293-01f46ea2-3475-4aea-9b38-bffbc90d8712.png)

`from pathlib import Path

import pandas as pd
from docxtpl import DocxTemplate
from docx import Document
from datetime import datetime
import jinja2
import itertools 

base_dir =Path(__file__).parent
word_template_path = base_dir / "Word-Template.docx"
excel_path = base_dir / "Base_2020.xlsx"

output_dir = base_dir / "OUTPUT"

output_dir.mkdir(exist_ok=True)

#Excel a df
df = pd.read_excel(excel_path,sheet_name="Sheet1")

#######################

df['Date'] = df.Date.dt.strftime("%d-%m-%Y")
df['Fecha_compromiso'] = df.Fecha_compromiso.dt.strftime("%d-%m-%Y")
df['group'] = df['Date'] + "_" + df['Topic']
df['Fecha_compromiso'] = df['Fecha_compromiso'].fillna('')

for value in df['group'].unique():
    for record in df.loc[df.group == value].to_dict("records"):
        doc = DocxTemplate(word_template_path)
        jinja_env = jinja2.Environment(autoescape=True)
        doc.render(record, jinja_env)
        output_path = f"{output_dir}/{record['group']}.docx"
        doc.save(output_path)

`and my template:

![image](https://user-images.githubusercontent.com/122225314/211394714-bcd5dc7f-e221-4e5a-a18f-26dc35f67d53.png)

I obtain this:

![image](https://user-images.githubusercontent.com/122225314/211395065-232a926a-1fbe-45a2-9a30-a26e6f04fd30.png)

**Comment by elapouya** [comment]
You are rendring one record, you have to render one context which must be a dict containing a list of records at key 'Topic'.
