### ISSUE TITLE
Optional row in table?

### ISSUE THREAD

**Issue by digitaldesaster** [elapouya/python-docx-template#48]
Hi, found this project today. awesome how easy this works. great work!

i wonder if it is possible to have an optional row in a table. this row should only be shown if there is some content. i have tried {% if my_content%} {{my_content}} {% endif %}. the problem is, that there is an empty row in the table if my_content is not in the item. 

any workaround on this?

please keep on the great work
dd

**Comment by elapouya** [comment]
Hello

Please use {%tr if ... %} xxx {%tr endif %}
the 'tr' syntax should work

**Comment by digitaldesaster** [comment]
Hi, sorry, this is explained in the docs. it works as designed.. thanks so much!

just one question.. nothing to do with your library. can you recommend any library for generating a pdf file from this docx? best regards dd

**Comment by elapouya** [comment]
Sorry, I cannot recommend you any converter
