### ISSUE TITLE
Create a Docx template with both tags and values

### ISSUE THREAD

**Issue by mire22** [elapouya/python-docx-template#481]
## Describe your problem
Hi,

I would like to create a template with both tags and values in a docx document. The idea is that the user can after copy/paste the tags in his own document (an elaborated document, for example a report) and have at the same time the example of what will be the values after rendering.
Basically, I want to have in the same docx escaped tags and tags. It's working well with `{% raw %}` and `{% endraw %}` for the "simple tags" but not for the "special syntax tags" (refering to [doc](https://docxtpl.readthedocs.io/en/latest/index.html?highlight=%7B%25tr%20endfor%20%25%7D#tags)) for the tables for example. The lines `{%tr for item in table_contents %}` and `{%tr endfor %}` are disapearing.
I already tried the options of issue #355 but it's still not working.

Thank you for your help!

## Provide a test case
[automated_report_template_2.docx](https://github.com/elapouya/python-docx-template/files/10558298/automated_report_template_2.docx)
[automated_report_2.txt](https://github.com/elapouya/python-docx-template/files/10558303/automated_report_2.txt): rename extension to .py

I'm expecting to find in the rendered document the elements between `{% raw %}` and `{% endraw %}` not rendered.

**Comment by elapouya** [comment]
did you try `{%p raw %} ... {%p endraw %}` (with a 'p') ? you may have also to escape `{%` and `{{` with `{_%` and `{_{`   (see doc)

**Comment by mire22** [comment]
Thank you!
It works well with `{_%tr for item in table_contents %_}` and `{_%tr endfor %_}`. I tested `{_` before but I wasn't using it well.

**Comment by nonprofittechy** [comment]
I've noticed you have to be very careful that the escaped tags are in the same "run". So editing an existing tag and inserting a _ may not work. I had to re-type the `{_{` and `{_%` to be sure the escaped tags are properly parsed.
