### ISSUE TITLE
Unable to open generated word file (Word experienced an error trying to open the file)

### ISSUE THREAD

**Issue by stefanomattia** [elapouya/python-docx-template#489]
## Describe the bug
Unable to open generated word file

## To Reproduce
I am using the following code:
```
from docxtpl import DocxTemplate

context = {'requirements' : [{'id': '0010',
  'description': 'first requirement',
  'category': 'functional',
  'applicability': 'all',
  'justification': 'self explanatory'},
 {'id': '0020',
  'description': 'second requirement',
  'category': 'functional',
  'applicability': 'X',
  'justification': 'self explanatory'}]}

doc = DocxTemplate("gsrd_template.docx")
doc.render(context)
doc.save("generated_doc.docx")
```
The gsrd_template.docx is a simple word document with the following content:

![Screenshot 2023-04-19 at 17 53 50](https://user-images.githubusercontent.com/16152387/233132111-ef0b6491-7efb-485a-be93-2e241a72b08e.png)

## Expected behavior
I would expect the generated word document to contain two tables for each of the two defined requirements in the context dictionary. 
However, even if there are no errors during the code execution, the generated word document can't be opened (see screenshot).
![Screenshot 2023-04-19 at 17 56 34](https://user-images.githubusercontent.com/16152387/233132570-5955f64e-7f0d-44f9-b6ed-46c112426003.png)

## Additional context
I am using Python 3.9.31, docxtpl 0.11.5 (installed via conda), python-docx 0.8.11, Word for Mac 16.72

**Comment by stefanomattia** [comment]
Thank you for the quick response.

Putting the for and enfor inside the table (on a merged row) kind of works (some spurious cells at the end), but I get one table with the two requirements concatenated (see screenshot).
However, I would like to have two separate tables, hence I put the for and endfor outside the table template, is that possible?

<img width="785" alt="Screenshot 2023-04-19 at 18 09 08" src="https://user-images.githubusercontent.com/16152387/233135588-a0e4ace2-9c60-4110-9919-00165ccde2f4.png">

The template I used is:

<img width="867" alt="Screenshot 2023-04-19 at 18 10 23" src="https://user-images.githubusercontent.com/16152387/233135886-b935b489-dd53-4ce9-bd93-69b040fea1ec.png">

**Comment by elapouya** [comment]
Sorry, I haven't that point, so what you did was almost good : put `for loop` outside the table but use `{%p` instead of `{%tr`

**Comment by stefanomattia** [comment]
Awesome, this works, thanks a lot!
