### ISSUE TITLE
Section breaks change from Next page - Continously

### ISSUE THREAD

**Issue by koenvb** [elapouya/python-docx-template#49]
Hi, 
Thanks a lot for your package. Its absolutely beautiful to create documents.
I got everything working but I cannot get the section breaks properly working.

The problem is that in my template I have set some Sections -- Next page
but when running the template, It gets magically changed into Sections - continously
and I was wondering what the correct way would be to force page sections? Ideally I would just put all the sections in different documents and merge them but I have no Idea if you can do that with this package.

I don't know how docx-template is treating sections .
IT feels like word is changeing the sections type randomly?

Should I use subdocuments for this? as 
My template for one page can be multiple pages long.
As for example it contains the text in this way.

{%p if distributor %}
bla bla bla
{%p else %}
bo bo bo bo
sfdsfdsfdsfsd
{%p endif%}
------ section break - Next page

So then after this i add a section break
but looks like word does not stick to this? It kind of randomly changes this to a sectionbreak - Continously?

So I have four sections
- Intro page (a cover page with some info (1 page)
- Brief letter with some info (1 page)
- Details (Several pages, depends on generated info)
- Terms and conditions (1 page section with column layout)

As I have quite some text I was hoping I could manage all of this without having
to create a subdocument in my python code.

Is there a way to have 4 different documents, open them as a subdocument and nicely but a master file with the correct page breaks etc?

Its probably a lot but was wondering how others deal with documents with multiple sections. All the rest is working really great.

**Comment by elapouya** [comment]
Hello
Could you give me example files (template and python source)

**Comment by elapouya** [comment]
Requested files not given
Closing.
