### ISSUE TITLE
Save file as dotx?

### ISSUE THREAD

**Issue by Joe2824** [elapouya/python-docx-template#494]
## Describe your problem
Is it possible to save the generated file as a word template file (dotx, dot)

**Comment by Joe2824** [comment]
Found a solution: https://github.com/python-openxml/python-docx/issues/363#issuecomment-414454150

**Comment by luxus** [comment]
hi @Joe2824 does it work with docx-template as well?

**Comment by Joe2824** [comment]
Hi,
yes I’m using it like this:
```

tpl = DocxTemplate(template)

doc_part = tpl.part
doc_part._content_type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.template.main+xml'

document_path = os.path.join(self.output_folder, name, str(self.year),f'{template_name[:-5]}.dotx')
 
tpl.save(document_path)

```
