### ISSUE TITLE
Use with Django Template instead of Jinja2

### ISSUE THREAD

**Issue by mpvillafranca** [elapouya/python-docx-template#50]
Hey! I'm planning to use the package to render some Docx on a project but I would like to use Django tags instead of Jinja2. I think that to do it I'll need to replace an import on your library: instead of `from jinja2 import Template` -> `from django.template import Template`. And then pass the context as a `django.template` `Context` object. Is that thing possible and compatible with the project License?

Thank you.

**Comment by elapouya** [comment]
hello,

yes , this should work : just try and tell me so
you can do anything you want with the library.

rds

2016-08-24 12:37 GMT+02:00 Mariano <notifications@github.com>:
