### ISSUE TITLE
How to create a table based on a pandas DataFrame with a variable number of rows and columns

### ISSUE THREAD

**Issue by yang162132** [elapouya/python-docx-template#510]
How to create a table based on a pandas DataFrame with a variable number of rows and columns.

**Comment by marcus-hao** [comment]
Can you show an example of what you're looking to produce?

**Comment by yang162132** [comment]
![image](https://github.com/elapouya/python-docx-template/assets/71556279/eec49c02-c49b-4a01-925f-707e6b13cf4f)
like this DataFrame.The number of rows and columns is not fixed

**Comment by marcus-hao** [comment]
@yang162132 Here's an example that creates a table similar to the one you showed.

Template:
![image](https://github.com/elapouya/python-docx-template/assets/24224821/562ef7e6-e896-4383-b1cd-e787ff2bab2f)

Code:
```
from docxtpl import DocxTemplate
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randint(0, 100, size=(10,10)),
                  columns=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'target'])

# Transpose the df so that each key is an entry
df = df.T.to_dict('list')

doc = DocxTemplate('template.docx')

ctx = {
    "tbl" : df
}

doc.render(ctx)
doc.save('results.docx')
```

Results:
![image](https://github.com/elapouya/python-docx-template/assets/24224821/00e2c5c8-0977-4347-8251-3b63679d2bdf)

**Comment by yang162132** [comment]
> 
Oh！Thank you very much, this really works
