### ISSUE TITLE
how to handle images and tables

### ISSUE THREAD

**Issue by februaryfang** [elapouya/python-docx-template#517]
## Describe your problem
My document A.docx contains some images. When I use Python-docx to process documents, I can get some objects like <class 'docx.oxml.drawing.CT_Drawing'>. I want to extract these image data and save it in a new document. I don't know what function to use to obtain these image data, as like I using 'Paragraph' to extract text.

## More details about your problem
1. which function should I use to get a image ?
2. How to simply and completely read a table with NA values ?

## Provide a test case
My document content looks like this：
![image](https://github.com/elapouya/python-docx-template/assets/13863155/2ed8bb80-83c1-440f-a022-d0c87eb2322b)

## Screenshots

my command lines:
![image](https://github.com/elapouya/python-docx-template/assets/13863155/aeabff23-4183-4fe9-a08f-753c315e734f)

![image](https://github.com/elapouya/python-docx-template/assets/13863155/c6846e96-ed7f-4f15-b14d-7328089be7ef)

def get_table_dataframe(table):
    date = []
    keys = None
    for i, row in enumerate(table.rows):
        text = (cell.text for cell in row.cells)
        if i == 0:
            keys = tuple(text)
            continue
        date.append(dict(zip(keys, text)))
    df = pd.DataFrame(date)
    return df

parent_elm2 = docall.element.body
for child in parent_elm2.iterchildren():
    if isinstance(child, CT_P):
        block=Paragraph(child, doc)
        print('text : '+block.text)
    elif isinstance(child, CT_Tbl):
        block=Table(child, doc)
        df = get_table_dataframe(block)
        print('Table : '+df)
    elif isinstance(child, CT_Drawing):
        print('1')
        ''' function to get picture '''
    else:
        print('wrong , please check')

**Comment by elapouya** [comment]
You are not on the right project, for python-docx : go here https://github.com/python-openxml/python-docx
