### ISSUE TITLE
XML ilegal chars

### ISSUE THREAD

**Issue by hmilkovi** [elapouya/python-docx-template#52]
Hi there,
is RichText supporting ilegal chars like "&" if not how can I escape them?
Directly in text or?
I had a problem that many english texts in my database have that 'and' sign,
but I didn't found and documentation related to it or I missed some thing.

Thx for time.

**Comment by elapouya** [comment]
RichText automatically escapes strings (internally, & is replaced by &amp;)
Could you give me a python code and a docx template showing your problem ?

**Comment by sadnoodles** [comment]
Use cgi:
```python
In [1]: import cgi

In [2]: cgi.escape
Out[2]: <function cgi.escape>

In [3]: cgi.escape('&')
Out[3]: '&amp;'
```

**Comment by pvizeli** [comment]
That should also help: http://stackoverflow.com/questions/1556554/jinja2-html-escape-variables
