### ISSUE TITLE
Sub Doc error: TypeError: unsupported operand type(s) for -: 'Undefined' and 'Undefined'

### ISSUE THREAD

**Issue by doctorpension** [elapouya/python-docx-template#53]
Hi,
Thank you so much for this great app!
I'm attempting to insert a sub doc into a doc, using the code from subdoc.py and the sample docs.
I am able to create the sub doc, and when I print it out to the console, I see that my variables have been assigned correctly.

However, when I assign the sub doc to the context and attempt to render I get the following traceback:

      File "C:\Users\user\Dropbox\virtualenvs\wakeup27\wakeup\forms\models.py", line
     112, in generateFile
        doc.render(context)
      File "C:\Users\user\Dropbox\virtualenvs\wakeup27\lib\site-packages\docxtpl\__init__.py", line 115, in render
        xml = self.build_xml(context,jinja_env)
      File "C:\Users\user\Dropbox\virtualenvs\wakeup27\lib\site-packages\docxtpl\__init__.py", line 80, in build_xml
        xml = self.render_xml(xml, context, jinja_env)
      File "C:\Users\user\Dropbox\virtualenvs\wakeup27\lib\site-packages\docxtpl\__init__.py", line 73, in render_xml
        dst_xml = template.render(context)
      File "C:\Users\user\Dropbox\virtualenvs\wakeup27\lib\site-packages\jinja2\environment.py", line 989, in render
        return self.environment.handle_exception(exc_info, True)
      File "C:\Users\user\Dropbox\virtualenvs\wakeup27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "<template>", line 1, in top-level template code
    TypeError: unsupported operand type(s) for -: 'Undefined' and 'Undefined'

Do you have any idea how I can fix this?

**Comment by elapouya** [comment]
Hi

Looks like you have a bad .docx template. if you really are using the
sample .docs from tests/ it should be something wrong with your .py file.
Please, Send me the .py and the .docx files your are using.

2016-11-06 15:12 GMT+01:00 doctorpension <notifications@github.com>:

**Comment by doctorpension** [comment]
Thank you for answering so quickly!
I am not using the actual sample doc - as I have a real life scenario :). I tried taking out the placeholder for the sub doc and it still didn't work, so you were right about the doc.
I then tried to use a doc that I had already been successful at using for placeholders. I resaved it and added another placeholder for the subdoc, and now I get the following error:

    TemplateSyntaxError: expected token 'end of print statement', got 'child_info'

my placeholder is: {{ p child_info }}, 
[join_hishtalmut_template_children.docx](https://github.com/elapouya/python-docx-template/files/573902/join_hishtalmut_template_children.docx)

Python code:


 	        table = sub_doc.add_table(rows=len(self.children) + 1, cols=5)
		hdr_cells = table.rows[0].cells
		hdr_cells[0].text = _("First_Name")
		hdr_cells[1].text = ("Last_Name")
		hdr_cells[2].text = _("Mispar_Zehut_Darkon")
		hdr_cells[3].text = _("DOB"
		hdr_cells[4].text = _("Gender")
		for child in self.children:
			row_cells = table.add_row().cells
			row_cells[0].text = child['SHEM_PRATI_YELED']
			row_cells[1].text = child['SHEM_MISHPACHA_YELED']
			row_cells[2].text = child['MISPAR_ZEHUT_YELED']
			row_cells[3].text = child['TAARICH_LEYDA_YELED']
			row_cells[4].text = child['MIN_YELED']


    	context['child_info'] = children_doc

**Comment by elapouya** [comment]
you put a space between {{ and 'p' : this is wrong, the syntax is {{p
child_info
}} without a space.

2016-11-06 16:11 GMT+01:00 doctorpension <notifications@github.com>:

**Comment by doctorpension** [comment]
Thank you so much! It's working.
