### ISSUE TITLE
Extract all tags from docx template

### ISSUE THREAD

**Issue by ivovdongenbdo** [elapouya/python-docx-template#546]
Hi all,

I was wondering how to extract all tags (e.g. "{{title}}" from a docx template. I would prefer a docxtpl build-in method over using something like re.findall.

Many thanks in advance.

**Comment by ivovdongenbdo** [comment]
Edit: Just found that ".get_undeclared_template_variables" does the trick.

**Comment by ivovdongenbdo** [comment]
Edit: Just found that ".get_undeclared_template_variables" does the trick.

**Comment by alranel** [comment]
It would be nice to add this to the command line interface.
