### ISSUE TITLE
Memory error at root.replace(body,etree.fromstring(xml)) in doctpl\__init__.py

### ISSUE THREAD

**Issue by sadnoodles** [elapouya/python-docx-template#58]
I'm rendering a large docx about 2M+, then memory error occurred.

Use Pycharm to debug, find out this place `etree.fromstring(xml)` Use up all memory.
at function:
```
    def map_xml(self,xml):
        root = self.docx._element
        body = root.body
        root.replace(body,etree.fromstring(xml))
```

Is there any solution on this one?

**Comment by elapouya** [comment]
Hello,

What python version are you using ?
What version of lxml have you ?
Could you attach your docx, so I can do some testing ?

**Comment by sadnoodles** [comment]
I'm using 2.7.10, and etree.LXML_VERSION (3, 4, 4, 0).
But it seems python 2.7.11 and etree.LXML_VERSION (3, 4, 0, 0) has memory error too.
Is there any way to use iter mode or stream while rendering ?

I will attach a test data later, after delete sensitive data. I am still testing on it.

**Comment by elapouya** [comment]
closing as no test case to debug
