### ISSUE TITLE
Can`t load images in table or text box 

### ISSUE THREAD

**Issue by duskan** [elapouya/python-docx-template#59]
hello, 

I develope atomatical report using this docxtpl. I don`t know how to upload Image file using jinja2, so My image add function is mixed jinja2 and python-docx library function.

When i put lot`s of image files using jinja2, tag MsOffice(2010) send Error message. Message is not english, but that error message means....

"cant open 'report.docx' file becaus something wrong in files"

So i try some test.  2 or 3 image can be added in textbox. but when i try to upload more images, report send same message. 
(not onlytextbox but also tables, too)

Here`s my Testing code and docx template file. 
(python 3.5.2)
please check and, help why it happened 

Thanks!

[reporttest.txt](https://github.com/elapouya/python-docx-template/files/701568/reporttest.txt)
[test_template.docx](https://github.com/elapouya/python-docx-template/files/701562/test_template.docx)
[result.docx](https://github.com/elapouya/python-docx-template/files/701569/result.docx)

**Comment by elapouya** [comment]
I added direct support for images in docxtpl 0.3.0 : please have a try : no need to use subdoc anymore.

**Comment by DennyWeinberg** [comment]
The disadvantage is that your code needs to provide the images instead of the doc itself.

A few months ago I wrote a small function to do this:
`def __ext_image(self, image_path_or_stream, unit='cm', width=None, height=None):
    """
    Insert an image into docx
    """
    sd = self.new_subdoc()
    if unit == 'cm':
        sd.add_picture(image_path_or_stream, width=Cm(width) if width else None, height=Cm(height) if height else None)
    else:
        raise NotImplementedError('Unit %r currently not implemented!' % (unit))

    return sd
`

**Comment by elapouya** [comment]
Providing image instead of doc was the goal of the new feature because
subdoc are too heavy

Le 15 janv. 2017 12:06 PM, "Denny Weinberg" <notifications@github.com> a
écrit :

**Comment by DennyWeinberg** [comment]
Ok. So I will keep my function but replace the code by the new InlineImage Class in order to make it run faster. Thank you.

**Comment by DennyWeinberg** [comment]
Attention, python_jpeg files is referenced in the test, but the file does not exist.

**Comment by elapouya** [comment]
Sorry forgot to add to git images : I just pushed the 0.3.1 to solve the pb

2017-01-16 9:38 GMT+01:00 Denny Weinberg <notifications@github.com>:

**Comment by duskan** [comment]
Thank you for your help! 
I realy want this function!!! 
(i try to change python docx library .. but it`s failed)

After changing doctpl version, i still have same problem.
And i found why it didnt work.
In my case MS Word version makes that trouble . 
I had tested it using MS2010. But result file works in MS2007!!
I think 'python-docx library' is working on MS2007 ...

Thank you!
