### ISSUE TITLE
Headers, footers tags

### ISSUE THREAD

**Issue by magom001** [elapouya/python-docx-template#6]
Nor really an issue. I was trying to generate a doc using a template containing jinja tags in a header and it turned out that those tags were not filled in with my values. Any ideas?

**Comment by elapouya** [comment]
This is normal : I use python-docx that does not manage headers and footers.
Nevertheless, it is possible to manage them though Microsoft word : the idea is to create a variable inside word document and then use it in the header, the footer and the body. When setting it in the body, it will update headers and footers too automatically.
I do not know how to do it with microsoft word, but I already used such a document as a template and headers and footers are modified correctly
If you can find a procedure, I will be pleased to add it in the documentation.
