### ISSUE TITLE
Whitespace?

### ISSUE THREAD

**Issue by leesoh** [elapouya/python-docx-template#62]
Hi there! First off, your module is fantastic. Second, is there a way to get rid of the whitespace left after the Jinja tags are parsed and removed? Jinja docs suggest {%- tag %}{% endtag -%} but I'm not having much luck with that method.

**Comment by elapouya** [comment]
Please, could you give a test case (docx template + python script)

2017-01-19 21:10 GMT+01:00 Liam Somerville <notifications@github.com>:

**Comment by leesoh** [comment]
Good morning. As I was preparing some test files for you I thought I'd try one more thing. I was originally iterating through a list of dictionaries using a `{%p for thing in things %}` along with a conditional of `{% if 'foo' in thing.title %}` which left the whitespace each time the condition did not match. Changing the loop to `{%p for thing in things %}` seems to have fixed most of my whitespace issues, and closing out my loop and conditional on the same line resolved the others.

I'm still seeing a lot of whitespace left in tables, but I'll take another stab at it before I bug you again :)

**Comment by leesoh** [comment]
Alright, this is the feature I'm referring to: http://jinja.pocoo.org/docs/2.9/templates/#whitespace-control. Hopefully this helps:
python:
```
from docxtpl import DocxTemplate


things = [{'name': 'foo'},
          {'name': 'bar'},
          {'name': 'baz'},
          {'name': 'ralph'},
          {'name': 'foo'}]
document = DocxTemplate("template.docx")
context = {
    'things': things
}
document.render(context)
document.save("rendered.docx")
```
Word:
```
This is a test.
{% for thing in things %}
{% if thing.name == "foo" %}
{{ thing.name }}
{% endif %}
{% endfor %}
More things
```
Looking to avoid the whitespace generated by items that don't match.

**Comment by elapouya** [comment]
did you try this : 

This is a test.
{% for thing in things %}{% if thing.name == "foo" %}{{ thing.name }}
{% endif %}{% endfor %}
More things

**Comment by leesoh** [comment]
That works, but doesn't when a bulleted list or heading is used for {{ thing.name }}. When a heading is used, applying the style to the {{ thing.name }} works quite well, but I still get whitespace where {% endif %}{% endfor %} are.
I tried to have the entire for/if loop on a line, but then ran into `jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'.` errors.

**Comment by DennyWeinberg** [comment]
Not sure if i understand the question... Why don't you usw %p for for and if?

**Comment by leesoh** [comment]
I did, it didn't seem to make a difference in the whitespace, and when I combined the for/if and endfor/endif on a single line, I got the error.

What does the p tag do?

**Comment by elapouya** [comment]
the 'p' supress the paragraph where the tag is :
{%p for i in mylist %}
{{ i }}
{%p endfor %}

this supress the for and andfor tags. but the {{i}} is still in its own
paragraph, I do not thing that is what you expect.

2017-01-30 3:33 GMT+01:00 Liam Somerville <notifications@github.com>:

**Comment by leesoh** [comment]
Hmm, I had assumed the opposite. I'll do some testing with that along with your prior suggestion and see if  I can't find a solution.

**Comment by leesoh** [comment]
I didn't realize that the `p` tag could also be used in the if. Adding this seems to have solved my issue. Thanks for the help everyone!

For reference, here's what changed:
```
This is a test.
{%p for thing in things %}
{%p if thing.name == "foo" %}
{{ thing.name }}
{%p endif %}
{%p endfor %}
More **things**
```
Colocating the for and if tags seems to have caused headaches, although multiple ifs doesn't seem to.
