### ISSUE TITLE
|e and newline

### ISSUE THREAD

**Issue by DennyWeinberg** [elapouya/python-docx-template#64]
|e escapes special XML Charakters... Shouldn't it also handle \r\n?

**Comment by elapouya** [comment]
|e is part of jinja2 ...

Le 29 janv. 2017 22:05, "Denny Weinberg" <notifications@github.com> a
écrit :

**Comment by DennyWeinberg** [comment]
OK. Could you override it? It makes more sense to handle newline Charakters too.

**Comment by elapouya** [comment]
Did you tried RichText ?

2017-01-29 22:25 GMT+01:00 Denny Weinberg <notifications@github.com>:

**Comment by elapouya** [comment]
Please, could you try my new 0.3.4 version and Listing() feature

**Comment by elapouya** [comment]
No answer : should work then ...
Closing
