### ISSUE TITLE
When using R(), the formatting is reset in the .docx file.

### ISSUE THREAD

**Issue by bdlamprecht** [elapouya/python-docx-template#68]
Thanks again for this library, it is great and should prove to be very useful.

When using the RichText() or R() in front of my dict() value which is used for the "render" function, the font and size of the text is reset to the default in generated docx file, even though the template has a pre-set font and size which I'd like to maintain.

**Comment by elapouya** [comment]
Could you provide me a  simplified docx template and python code that
reproduce the problem ?

**Comment by bdlamprecht** [comment]
Yeah, see the attached "docx-creator.txt" (rename to .py)  and the template "input.tpl.docx".  When the script is run, it will automatically produce an "output.docx" file where the problem can be seen.

[docx-creator.txt](https://github.com/elapouya/python-docx-template/files/768910/docx-creator.txt)
[input.tpl.docx](https://github.com/elapouya/python-docx-template/files/768909/input.tpl.docx)

FYI, I'm using doxtpl 0.3.3.

**Comment by elapouya** [comment]
I analyzed your docx template : 
In your case, you have "characters" styling in your template : that means the style is applied at character level not at paragraph level. In such a case, the behaviour you have is normal : 
{{r }} will replace the current 'run' (style included) by the one you defined within RichText object.
As you defined none, the styling is just resetted to default (like you noticed).
2 solutions : 
1) You want to choose your style : use RichText('the text',style='the docx template style name you want')
2) You want to keep the existing style : just use {{ }} without the 'r' and do not use RichText : just use the string in your context dict (like you did for 'test1_comment' key)

**Comment by bdlamprecht** [comment]
Eric,

I re-tested using your suggested changes to my docx template file and discovered the problem I'm having appears to be that the RichText() does not appear to honor "leading spaces" in new lines correctly.

I've statically included the "problem text" I'm trying to use in the updated code and demonstrated all three options in the docx template (1: No RichText, 2: RichText with NO "style=", 3: RichText WITH "style=") as well as the output from the python interpreter for each of those options.

Ideally, I'd like to have the docx file to show the same output as the python interpreter does for "Test 1".

I'm not sure if what I'm trying to do is out of spec, not supported, or if I am trying to accomplish this the entirely wrong way.  I would appreciate any help that can be provided.

Thanks.

[docx-creator.txt](https://github.com/elapouya/python-docx-template/files/771925/docx-creator.txt)
[input.tpl.docx](https://github.com/elapouya/python-docx-template/files/771923/input.tpl.docx)

**Comment by bdlamprecht** [comment]
After learning more about Word's XML formatting, it appears that the tag "<w:t xml:space="preserve>" is applied for the first instance where the line begins with spaces, but all of the following instances they do not retain that correct tag.

As seen from the python interpreter from the my most recent code in the output for Test2:

`<w:r><w:t xml:space="preserve">    Line       User       Host(s)              Idle       Location</w:t><w:br/><w:t>*  2 vty 0     rwuser     idle                 00:00:00 9.0.49.199</w:t><w:br/><w:t></w:t><w:br/><w:t>  Interface    User               Mode         Idle     Peer Address</w:t><w:br/><w:t></w:t></w:r>`

See the first line where the text "Line       User" is shown, this has the correct "preserve" attribute.
The second line where the text "  Interface    User" is shown, this does NOT have the same "preserve" attribute.

Not being familiar with the bug reporting tools within GitHub, do I need to re-open the bug or is that something only you can do?

**Comment by elapouya** [comment]
I do not understand your problem, on my side the test 2 and 3 seems to be formatted correctly (corresponds to your "problem_text")
for test 1 everything is on the same line...
I have Word 2007, what is your MSWord version ?

**Comment by bdlamprecht** [comment]
Per corporate policies, I'm required to use Word 2016.  To keep things simple and not confuse the situation, I propose that we keep this bug closed and use the new [bug](https://github.com/elapouya/python-docx-template/issues/69) I opened to track changes.  Thanks.
