### ISSUE TITLE
The XML tag [w:t xml:space="preserve"] is only applied to the first instance of leading spaces.

### ISSUE THREAD

**Issue by bdlamprecht** [elapouya/python-docx-template#69]
This is a follow-up to the [bug](https://github.com/elapouya/python-docx-template/issues/68) I first reported concerning issues with the RichText() functions within docxtpl.

After you closed the bug, I re-tested using your suggestions and discovered that the issue was in-fact two-fold: 
1. Yes I needed to use alter my docx template which I did (thanks again for your solution).
2. The XML tag [w:t xml:space="preserve"] is applied only to the first instance of leading spaces.

As seen from the python interpreter from the my most recent code in the output for Test2:

`<w:r><w:t xml:space="preserve"> Line User Host(s) Idle Location</w:t><w:br/><w:t>* 2 vty 0 rwuser idle 00:00:00 9.0.49.199</w:t><w:br/><w:t></w:t><w:br/><w:t> Interface User Mode Idle Peer Address</w:t><w:br/><w:t></w:t></w:r>`

See the first line where the text "Line User" is shown, this has the correct "preserve" attribute.
The second line where the text " Interface User" is shown, this does NOT have the same "preserve" attribute.

[docx-creator.txt](https://github.com/elapouya/python-docx-template/files/772714/docx-creator.txt)
[input.tpl.docx](https://github.com/elapouya/python-docx-template/files/772711/input.tpl.docx)

Thanks in advance for any help you can provide in solving this issue.

**Comment by elapouya** [comment]
Please, could you try my new 0.3.4 version and Listing() feature

**Comment by bdlamprecht** [comment]
I've upgraded to 0.3.4 and I don't see a Listing() function available after importing all from docxtpl:

`bl839s@ansible:~$ pip list | grep docxtpl

docxtpl             0.3.4
`
and

`bl839s@ansible:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from docxtpl import *
>>> dir()
['Document', 'DocxTemplate', 'InlineImage', 'R', 'RichText', 'Subdoc', 'Template', '__builtins__', '__doc__', '__name__', '__package__', 'escape', 'etree', 're', 'six']`

**Comment by bdlamprecht** [comment]
Nevermind my last comment, I forgot to specify pip2 when I upgraded to docxtpl 0.3.4.  I will test if this new feature solves my problem.  Thanks.

**Comment by elapouya** [comment]
my side :

(venv) elapouya@pcubuntu:~/tmp/venv$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docxtpl
>>> dir(docxtpl)
['Document', 'DocxTemplate', 'InlineImage', 'Listing', 'NEWLINE',
'NEWPARAGRAPH', 'R', 'RichText', 'Subdoc', 'Template', '__builtins__',
'__doc__', '__file__', '__name__', '__package__', '__path__',
'__version__', 'escape', 'etree', 're', 'six']
>>>

pip freeze:

docxtpl==0.3.4
Jinja2==2.9.5
lxml==3.7.2
MarkupSafe==0.23
MySQL-python==1.2.5
plotly==1.12.12
python-docx==0.8.6
pytz==2016.10
requests==2.12.4
six==1.10.0

what docxtpl point to ?

import docxtpl
print docxtpl.__file__

Then display the file .py

2017-02-14 16:20 GMT+01:00 bdlamprecht <notifications@github.com>:

**Comment by bdlamprecht** [comment]
Your Listing() feature works perfectly.  Thanks so much for working this for me!

It also solves another issue where I needed to figure out which characters I needed to escape that were causing my script to break mid-run.

Much appreciated,
Brady
