### ISSUE TITLE
Any roadmap for adding images/pictures?

### ISSUE THREAD

**Issue by miloskv** [elapouya/python-docx-template#7]
Not really an issue as you can imagine, but I wonder if you plan adding option to insert pictures/images into docx documents? 

My use case is to generate bunch of reports for different customers and I would like to automate adding customer's logo on each and every new docx document that I am creating from a template.

Cheers,
Milos

**Comment by elapouya** [comment]
This is possible by using subdocument (see subdoc.py in tests)
just add :
sd.add_picture('the_customer_logo.png', width=Inches(1.25))
more info about add_picture in python-docx package (that I use)

**Comment by miloskv** [comment]
Thanks for your help mate. It works :) I forgot to RTFM :)
