### ISSUE TITLE
Ignore empty tables in the generated doc

### ISSUE THREAD

**Issue by maltantawy** [elapouya/python-docx-template#74]
Hi, 

Thanks a lot for your wonderful tool. Just wanted to check, if its possible to ignore any empty tables when generating the new doc ?. The tables are copied to the new generated document even if they are empty .. 

Thanks

**Comment by elapouya** [comment]
Yes

Just surround your table with {%p if rows %}  ... {%p endif %}

With rows=list of row you have in your table (or other test you want)

Le 12 mars 2017 13:46, "Mostafa Altantawy" <notifications@github.com> a
écrit :

**Comment by maltantawy** [comment]
Thanks a lot works like charm now.
