### ISSUE TITLE
support xlsx or pptx ?

### ISSUE THREAD

**Issue by simevo** [elapouya/python-docx-template#76]
Hi, great library, do you think it would work with/without some modifications for other Office Open XML formats such as xlsx or pptx ?

**Comment by elapouya** [comment]
Unfortunately there is a lot of work to do, the first would be to have a
xlsx/pptx library to read/write corresponding files. Nevertheless, the
"template" part (What I developped) should work with little work...I guess.

2017-05-05 16:23 GMT+02:00 simevo <notifications@github.com>:

**Comment by simevo** [comment]
OK, many thanks!
