### ISSUE TITLE
Bug in fix_tables

### ISSUE THREAD

**Issue by dalai4git** [elapouya/python-docx-template#77]
I think there is a bug in fix_tables introduced in 90e6dc12c3a593684ab97c8435ba8e63eaac9b79. 

The loop at the end that adjusts the column widths should run only if the calculated table width is larger than zero. Otherwise the variable `new_average ` is `None ` and an exception is thrown.

**Comment by elapouya** [comment]
Could you give me a test case (minimal docx template and python file) to reproduce your problem ?

**Comment by dalai4git** [comment]
Unfortunately I don't remember what I happened to be doing at the time, but it is quite obvious that the following two lines are misaligned: 
https://github.com/elapouya/python-docx-template/blob/master/docxtpl/__init__.py#L177-L178
If you don't follow the if branch on line 170, then you get an exception on line 178.

**Comment by elapouya** [comment]
Good pick : fixed that in 0.3.9
Thank you.
