### ISSUE TITLE
Raise KeyError if missing variable

### ISSUE THREAD

**Issue by adamboche** [elapouya/python-docx-template#79]
If I run `doc.render({context})` on a document that requires `'key'` but `context` has no `key`, I want it to raise `KeyError`, so it doesn't silently produce a document missing text. How can I do this?

**Comment by elapouya** [comment]
Could you try a custom jinja2 environment to ask for an exception if
something missing (with undefined=jinja2.StrictUndefined as parameter):

    from docxtpl import DocxTemplate
    import jinja2

    doc = DocxTemplate("my_word_template.docx")
    context = { ... }
    jinja_env = jinja2.Environment(undefined=jinja2.StrictUndefined)
    doc.render(context,jinja_env)
    doc.save("generated_doc.docx")


2017-05-26 5:12 GMT+02:00 adamboche <notifications@github.com>:

**Comment by adamboche** [comment]
Sounds good, thanks!
