### ISSUE TITLE
Make a hyperlink

### ISSUE THREAD

**Issue by adamboche** [elapouya/python-docx-template#80]
How can I create a hyperlink like [this popular site](google.com), where I can adjust the text and destination dynamically?

**Comment by elapouya** [comment]
This is note coded yet, it is a good idea
I put that in my todo list...

**Comment by labsolution** [comment]
+1

**Comment by Guts** [comment]
I'm interested too by this feature.
In python-docx, it's not implemented but [there is a workaround described here](https://github.com/python-openxml/python-docx/issues/74#issuecomment-261169410).

**Comment by serdanilov** [comment]
Was this ever actioned? I'm reaaaaaally interested in this :)

**Comment by scm95** [comment]
There is some temporary way to do this, I urgently need it.

**Comment by elapouya** [comment]
I have added hyperlink feature : could you test it by cloning this repo (not yet pushed on pypi)

You can add an hyperlink to a text by using a Richtext with this syntax :

   tpl=DocxTemplate('your_template.docx')
   rt = RichText('You can add an hyperlink, here to ')
   rt.add('google',url_id=tpl.build_url_id('http://google.com'))

Put rt in your context, then use {{r rt}} in your template

**Comment by scm95** [comment]
Perfect man thank you very much for your collaboration I work excellent

**Comment by Spoonrad** [comment]
Hi there @elapouya, I was wondering when you intended to push this to pypi?

I would like to use this feature, though I find the current way it is made a little impractical. Adding a custom jinja filter could be interesting, like {{r Click here|hyperlink("https://google.com")}} or {{r Click here|hyperlink(link_value)}} where "link_value" can be in the render dict.

**Comment by elapouya** [comment]
@Spoonrad : Sorry, I won't do a jinja filter because Richtext object must be defined at python side, so it will be the same for the url.
Nevertheless, the url_id feature is already in pypi since version 0.5.0
