### ISSUE TITLE
can python-docx-template generate row span within tables?

### ISSUE THREAD

**Issue by haoziyeung** [elapouya/python-docx-template#84]
i want to merge cells in table like this:
![row_span_tables](https://user-images.githubusercontent.com/16606564/27327004-c11ebdc6-55df-11e7-8cf5-aa40a769f533.png)

i can't find solutions in manual,can anyone tell me how to solve this?

thanks a lot.....

**Comment by elapouya** [comment]
There is no rowspan feature in docxtpl... sorry.
