### ISSUE TITLE
how can i add another docx file to a existed docx file?

### ISSUE THREAD

**Issue by WUWEIREN** [elapouya/python-docx-template#87]
there have tow docx files,named A.docx and B.docx,and now,I want to add A.docx to the B.docx,not the content of the A.docx, it just like a link,a attachemnt inside in B.docx,but question is how can i do it?
please help me, thanks!!

**Comment by elapouya** [comment]
Could you give me an exemple of a final docx file you want to be generated ?

**Comment by WUWEIREN** [comment]
![20170906112259](https://user-images.githubusercontent.com/22806435/30093109-c6efe510-92f5-11e7-8d47-27b3a245a3f7.png)

Just like the display of that photo,this red arrows  that appoint is a docx file named test2.docx embeded inside the current docx file, but that is generated by using the office software mannually,and how can i use python-dcox-template to do that,thakns!

**Comment by elapouya** [comment]
I need the corresponding docx file so I can say if it is possible to
implement that

**Comment by WUWEIREN** [comment]
before deal it,it like this:
[test222.docx](https://github.com/elapouya/python-docx-template/files/1279783/test222.docx)
after altered it,it like this:
[test222.docx](https://github.com/elapouya/python-docx-template/files/1279778/test222.docx)
this is the result docx file, but how can i do it by python-docx-template,thaks very much!

**Comment by elapouya** [comment]
It is not possible actually, but I could code it in the next releases.

2017-09-06 6:41 GMT+02:00 wuweiren <notifications@github.com>:

**Comment by WUWEIREN** [comment]
but could you tell me the fundamental theory about achive it?,i want to tyr, thank you very much!

**Comment by elapouya** [comment]
Actually, I have to add and customize such a xml code in world/document.xml
:

<w:r><w:object w:dxaOrig="1520" w:dyaOrig="937"><v:shapetype
id="_x0000_t75" coordsize="21600,21600" o:spt="75" o:preferrelative="t"
path="m@4@5l@4@11@9@11@9@5xe" filled="f" stroked="f"><v:stroke
joinstyle="miter"/><v:formulas><v:f eqn="if lineDrawn pixelLineWidth
0"/><v:f eqn="sum @0 1 0"/><v:f eqn="sum 0 0 @1"/><v:f eqn="prod @2 1
2"/><v:f eqn="prod @3 21600 pixelWidth"/><v:f eqn="prod @3 21600
pixelHeight"/><v:f eqn="sum @0 0 1"/><v:f eqn="prod @6 1 2"/><v:f eqn="prod
@7 21600 pixelWidth"/><v:f eqn="sum @8 21600 0"/><v:f eqn="prod @7 21600
pixelHeight"/><v:f eqn="sum @10 21600 0"/></v:formulas><v:path
o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/><o:lock
v:ext="edit" aspectratio="t"/></v:shapetype><v:shape id="_x0000_i1025"
type="#_x0000_t75" style="width:76.2pt;height:46.8pt" o:ole=""><v:imagedata
r:id="rId8" o:title=""/></v:shape><o:OLEObject Type="Embed"
ProgID="Word.Document.12" ShapeID="_x0000_i1025" DrawAspect="Icon"
ObjectID="_1566201902"
r:id="rId9"><o:FieldCodes>\s</o:FieldCodes></o:OLEObject></w:object></w:r>

then create a file in the docx archive directory word/embeddings/
containing the docx to embed
then create a new relationship in word/_rels/document.xml.rels pointing to
the embded docx

The only missing part is the icon representing the embded document : on
libreoffice it is blank in the file you gave me, I will on MSWord when
possible...

This is my theory, it is to be tested...



2017-09-06 8:41 GMT+02:00 wuweiren <notifications@github.com>:

**Comment by WUWEIREN** [comment]
wow,that's cool!
thansk very much again,elapouya!
i will try it next ...thanks!!!!

**Comment by WUWEIREN** [comment]
it woked,thanks again!

**Comment by elapouya** [comment]
Do you mean you developped some python code ??

2017-09-07 8:28 GMT+02:00 wuweiren <notifications@github.com>:

**Comment by WUWEIREN** [comment]
not exactly,firstly,i tested it by your menas,after i have a mean that would be a little circuitous ,this steps is:

1. use the python-docx-template replace a {{ <var>}} in A.docx by your have give me that customize xml code

2.and,change the A.docx to A.zip, and  uncompress A.zip,that a directory A
3.then,use your means to  embed the B.docx to A/document/embeddings/B.docx by python-package subprocess executing the shell command lines
4,after,i have to change the word/_rels/document.xml.rels
5,finally,using python-package create a new zipfile named C.docx,and add content fo the directory A to 
the C.docx rerecursion
this is only my approach,but there is also have a problem -  it cnat't show the image,except a blank!!!!
so,what a circuitous way it is!!But thanks for your help,thank you!!

**Comment by elapouya** [comment]
I would be pleased if you rate & share the project here :
http://rate.re/github/elapouya/python-docx-template  ;)

2017-09-07 9:33 GMT+02:00 wuweiren <notifications@github.com>:

**Comment by WUWEIREN** [comment]
It's also my pleasure! I will do it!but not now, because this project is not perfect currently,i think i should do it more better,!next i will do it more better,and i will to share it also when i finishe my goal!!!

**Comment by elapouya** [comment]
OK, tell me if I can help.

2017-09-07 16:31 GMT+02:00 wuweiren <notifications@github.com>:

**Comment by WUWEIREN** [comment]
the problem is,just you tell me your theory, "missing part is the icon representing the embded document",and could you tell me how can i embed the attachment's icon to the document?

**Comment by elapouya** [comment]
I don't know : I didn't know it was possible to embed docx in docx, so I am
discovering your docx...and when displaying your docx on linux there is no
icon.
I have to investigate.

**Comment by WUWEIREN** [comment]
ok!I hope you can investigate it,and i will look forward to your reply next,thanks!

**Comment by elapouya** [comment]
Could you tell me, step-by-step, how do you embedded the docx in the docx in order to get the picture you gave me in your 2nd post ?
My side, I only succeeded to get the text of the embedded docx, not an icon pointing to it like in your picture.

**Comment by WUWEIREN** [comment]
I'm sorry,I don't know how embed can the icon of docx into another docx by coding,
I want to ask you about the solution,  but about you said the second post by mine,
it just did by the office of windows,not by coding,it just by the mouse,and dargging the
one docx to the target that the docx i want,not by coding!

but i tested the theory you gave me,there didn't had a icon,also, just a blank it had a width and longth,
I have tried to solve it,but it was failure,so I want to seek advice from you,please !!

**Comment by elapouya** [comment]
OK, I found a solution to get all right, stay tuned !

2017-09-09 10:30 GMT+02:00 wuweiren <notifications@github.com>:

**Comment by WUWEIREN** [comment]
well！good luck!

**Comment by elapouya** [comment]
Just have to write the doc and then I push the whole thing

2017-09-09 11:28 GMT+02:00 wuweiren <notifications@github.com>:

**Comment by WUWEIREN** [comment]
do you mean you have the ways to solve it,by coding,not mannually?

**Comment by elapouya** [comment]
Yep

**Comment by elapouya** [comment]
new docxtpl v0.4.0 is now online on pypi

read tests/embedded.py to see how to embedded the document you want.

**Comment by WUWEIREN** [comment]
You are wonderful!Thanks again for you help me!thanks!
 I have read your source code,that's method is so smartly! but i think there is a little question, list:
![default](https://user-images.githubusercontent.com/22806435
/30245780-2360a0d6-9617-11e7-8ba4-18b60abdd4cc.png)

![default](https://user-images.githubusercontent.com/22806435/30245810-13896872-9618-11e7-882f-54631cb01123.png)

**Comment by elapouya** [comment]
This is normal, docxtpl only change the content, not the icon filename.
Files names given to the method are only use to find the old content and
replace it with the new one. Files names can be anything and can be
different than the icon name. For the first argument of the method, just a
give a file that has the same content than the one you embedded manually in
the docx (the file itself or a copy with another name)

To custmoize the icon name, Just give the icon the final name you want in
the template (it is possible to rename it in MSWord)

Do you really need the icon name to be dynamic ?

**Comment by WUWEIREN** [comment]
not exactly! I'm just curious about that, and want to know whether there have a way to make the icon and it's name dynamicly,could you tell me somthing about it?thank you,again!

**Comment by elapouya** [comment]
The problem is that the icon name is not a text, but it is included in icon
picture ! So if you want to modify the icon you have to :
- extract the .emf file from the docx archive (word/medias/ directory)
corresponding to the icon (let says 'image1.emf'), so replace_media() will
be able to find it in the docx archive.
- create a new one with a python library (Pillow etc...), with PNG format
- convert it to .emf format (which is quite difficult on linux :
 libreoffice --headless --convert-to emf image1_new.png, that generates a
very very very big image1_new.emf file, but it works)
  you can also use 'pyemf' python package to generate a .emf from scratch.
- Then do a tpl.replace_media('image1.emf','image1_new.emf')

2017-09-10 10:56 GMT+02:00 wuweiren <notifications@github.com>:

**Comment by WUWEIREN** [comment]
Wow,you are **AWESOME!**
And thanks for your help during this time!Thank you!!
I will try it ...next

**Comment by mothesh-kumar** [comment]
using docxtpl can we add a excel file or pdf file in the output document ?
