### ISSUE TITLE
tr endfor is not always recognized

### ISSUE THREAD

**Issue by tenshis** [elapouya/python-docx-template#9]
I have a table that looks like this:
![image](https://cloud.githubusercontent.com/assets/2423660/10825596/07786c48-7e66-11e5-972e-54478142a755.png)

And by the love of Zeus, it will not let me process it. It keeps saying "TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'."

**Comment by elapouya** [comment]
Your loop seems correct, the problème should be somewhere else in the .docx
:
Could you give me your code and your .docx, so I can reproduce the problem
at home ?

2015-10-29 17:55 GMT+01:00 tenshis <notifications@github.com>:

**Comment by tenshis** [comment]
Hi,

Thanks a lot for helping! The files are attached.

**Comment by elapouya** [comment]
please, send your infos to ericdupo@gmail.com

**Comment by elapouya** [comment]
You wrote that it works now with a new template and the 'for' (not 'tr for')

You should use the 'tr for' : by this way, the row where is the 'tr for' and 'tr enfor' will desappear because useless in the final document.
I used the 'tr for' with .docx you sent me : it works also and as expected.
When using 'for' without 'tr' in tables, your document may be corrupted internally.
I think your original docx had something wrong in it : are you using openoffice or something else than original Microsoft word ?

**Comment by tenshis** [comment]
No, I'm using MS Word docx. The 'for' without tr is of course around the
table, not as part of the table. As I said, I could not get tr-for to work,
so I experimented with it.

**Comment by elapouya** [comment]
For me it works with 'tr for' (I rewrite a little the files), I run Office 2007.

[autoprofil_template_small.docx](https://github.com/elapouya/python-docx-template/files/24204/autoprofil_template_small.docx)
[generated_doc_small.docx](https://github.com/elapouya/python-docx-template/files/24205/generated_doc_small.docx)

Code I used :
    from docxtpl import DocxTemplate, RichText
 
    doct = DocxTemplate("autoprofil_template_small.docx")
 
    context = {
    'Projekte' : [
            {'ProjektName' : 'Projekt1',
            'ProjektZeitraum' : 'Juni 2014 - Oktober 2015',
            'ProjektRolle':'Trainer',
            'ProjektTechnologie':'MS SQL Server 2008 R2',
            'a':'Aufgabe1 \nAufgabe2'
            },
            {'ProjektName' : 'Projekt2',
            'ProjektZeitraum' : 'Juni 2014 - Oktober 2015',
            'ProjektRolle':'Trainer',
            'ProjektTechnologie':'MS SQL Server 2008 R2',
            'a':'Aufgabe1'
            }
             ]
    }
    doct.render(context)
    doct.save("generated_doc_small.docx")
