### ISSUE TITLE
In Python 3 .iteritims in __init__.py break code; solution provided

### ISSUE THREAD

**Issue by mzaanen** [elapouya/python-docx-template#94]
Changing ".iteritems()" to ".items()" in 2 places in "def pre_processing" in __init__.py will fix the problem.

This should work for both Python 2 and 3 (http://python-future.org/compatible_idioms.html).

Let me take this opportunity for  "One big thanks" for this project.

Kind regards,
Maarten Zaanen

**Comment by elapouya** [comment]
I used six.iteritems() instead.
Fixed in 0.4.4
