### ISSUE TITLE
Replace picture works in header, not in body

### ISSUE THREAD

**Issue by mzaanen** [elapouya/python-docx-template#95]
I can run the "replace_picture.py" with the corresponding "test_files/replace_picture_tpl.docx"; it works fine. In the XML of the document.docx I see:
`<pic:cNvPr name="python_logo.png" id="0"/>`
          

I have a test.docx with a .png in the header and a .png in the body. In the document.XML I see:
`<pic:cNvPr name="pagina_1_picture.png" id="1"/>`

Using the following script (very similar to the test script):

```
from docxtpl import DocxTemplate
tpl=DocxTemplate('c:/temp/test.docx')
context = {}
tpl.replace_pic('header_picture.png', 'c:/temp/header_empty.png')    # works fine
tpl.replace_pic('pagina_1_picture.png', 'c:/temp/pagina_1_empty.png')  # gives error
tpl.render(context)
tpl.save( 'c:/temp/replace_picture3.docx' )
```

I get the error:
`ValueError: Picture "pagina_1_picture.png" not found in the docx template`

A picture in the header does do the replace correctly.

I have tried to debug what is going on, so far, no joy.

Kind regards,
Maarten Zaanen

![header_empty](https://user-images.githubusercontent.com/6717620/31503575-4fca9934-af70-11e7-8f84-52e7bdddd6b1.png)
![pagina_1_empty](https://user-images.githubusercontent.com/6717620/31503577-5006abfe-af70-11e7-83ba-93d728552c8f.png)
[test.docx](https://github.com/elapouya/python-docx-template/files/1379745/test.docx)

**Comment by elapouya** [comment]
in  docxtpl/__init__.py could you add following trace and tell me what is
displayed :

replace :

def pre_processing(self):

    if self.pic_to_replace:

        pic_map={}

        # Main document
        part=self.docx.part
        pic_map.update(self._img_filename_to_part(part))

        # Header/Footer
        for relid, rel in self.docx.part.rels.iteritems():
            if rel.reltype in (REL_TYPE.HEADER,REL_TYPE.FOOTER):
                pic_map.update(self._img_filename_to_part(rel.target_part))

        # Do the actual replacement
        for embedded_file,stream in self.pic_to_replace.iteritems():
            if embedded_file not in pic_map:
                raise ValueError('Picture "%s" not found in the docx
template' % embedded_file)
            pic_map[embedded_file][1]._blob=stream

by

def pre_processing(self):

    if self.pic_to_replace:

        pic_map={}

        # Main document
        part=self.docx.part
        pic_map.update(self._img_filename_to_part(part))

        # Header/Footer
        for relid, rel in self.docx.part.rels.iteritems():
            if rel.reltype in (REL_TYPE.HEADER,REL_TYPE.FOOTER):
                pic_map.update(self._img_filename_to_part(rel.target_part))

        #Debug :
        for k,v in pic_map.items():
            print '%s => %s' % (k,v)

        # Do the actual replacement
        for embedded_file,stream in self.pic_to_replace.iteritems():
            if embedded_file not in pic_map:
                raise ValueError('Picture "%s" not found in the docx
template' % embedded_file)
            pic_map[embedded_file][1]._blob=stream


2017-10-12 17:04 GMT+02:00 Maarten <notifications@github.com>:

**Comment by mzaanen** [comment]
The answer is:
`header_picture.png ('media/image2.png', <docx.parts.image.ImagePart object at 0x042FEB70>)`

**Comment by elapouya** [comment]
could you give me your docx template file ?

**Comment by mzaanen** [comment]
In my initial comment included the minimal "test.docx" for your convenience. It shows up right at the bottom of the comment, you may have missed it.

**Comment by elapouya** [comment]
the xpath request was too narrow.
Fixed into docxtpl v0.4.3 that I just released
Could you test ?

**Comment by mzaanen** [comment]
Tested: perfect !
Thank you so much for the incredibly speedy solution !

If I can be of help at any time for this project let me know. I would be happy to help with documentation, proofreading, testing etc. I am afraid that, when I look at the internals (only 467 lines of code... amazing), I would be of little help in coding at this moment in time; it does seem to require intimate knowledge how .docx xml works. Do not hesitate to ask.

**Comment by elapouya** [comment]
You're welcome. thanks for your proposal.

**Comment by nma971** [comment]
The replace_pic is only for replacing header/footer images not for body, since there is no other way around.
